### ISSUE TITLE
#VideoAdServer - Disable Skip Ad

### ISSUE THREAD

**Issue by gregorymcewanmarriot** [YouPHPTube/YouPHPTube#1568]
How can i disable the Skip Ad button, the progress bars and the text that says this is an Advert on all ads? - Basically I don't want users to see anything BUT the actual ad video - so no overlays?

**Comment by DanielnetoDotCom** [comment]
If you are using a Ads company, you have to ask them (the ads company)

If you are using our Ad_server plugin set the skipoffset to 0

![image](https://user-images.githubusercontent.com/18009293/54474327-44805780-47c2-11e9-899a-09ba3ef3bb70.png)

**Comment by DanielnetoDotCom** [comment]
I guess 0 should do the trick.
if does not work try -1 instead

**Comment by gregorymcewanmarriot** [comment]
aaaaargh...... cant get this to work at all - have a valid campaign added 5 local video files to it, set settings as above, no ads show at all... log file in db empty.... struggling here, tried reinstalling adserver files few times... and tables....

I want to be able to display local mp4 ads in one random location eg mid file and one at end... or show an advert for every say 3 other videos watched...

Before it stopped working i saw a message about media file not supported or something to that effect, yet the ad video files play fine if i direct view them from server... must they be in a playlist? (the ad files), must they have a category? Must they be public? - as i tried all the above

**Comment by DanielnetoDotCom** [comment]
I am not sure what are you missing, but can you reproduce it on demo site?

**Comment by mrtick2002** [comment]
I've tried both ways you said (setting to 0 or to 1) and when the ad comes up, the "skip ad" still comes up immediately.

**Comment by mrtick2002** [comment]
Figured it out. Change it to 100%.
![index](https://user-images.githubusercontent.com/42279109/62478139-fb7c7000-b76f-11e9-8839-dfccd2b11ce2.png)
