### ISSUE TITLE
How to convert YouPHPTube into DASH/ HLS player?

### ISSUE THREAD

**Issue by iamgmujtaba** [YouPHPTube/YouPHPTube#1617]
Hi There,
I think YouPHPTube is very amazing open source tool. I just want to know is it possible to convert YouPHPTube into DASH/ HLS streaming protocols.  Like this [DASH](https://github.com/Dash-Industry-Forum/dash.js?) player.

Thanks

**Comment by DanielnetoDotCom** [comment]
Yes, it is. check out the demo site.

All videos are HLS.

the thing is, HLS videos, for now, is only working if you store your videos locally. it does not work with S3 or B2 storages; that is why it is not for sale yet.

If you want this plugin I can sell it for you, just email me developer@youphptube.com

**Comment by iamgmujtaba** [comment]
Thank you for your kind replay. I have already bought a video thumbnail plugin, and it is a really great feature. I need the DASH plugin instead of HLS, so I might think about purchasing that plugin at a reasonable price.

**Comment by iamgmujtaba** [comment]
Thank you for your kind replay. I have already bought one plugin, and it is a really great feature. I need the DASH plugin instead of HLS, so I might think about purchasing that plugin at a reasonable price.
