### ISSUE TITLE
Plugins list empty??

### ISSUE THREAD

**Issue by kaptkrunch** [YouPHPTube/YouPHPTube#1629]
Hi, 
I run phptube and have purchased many extra plugins for it. The plugins themselves are working correctly, but when i go to installed plugins its empty. So I cant edit them, like advanced header and such. Thanks in advance.

**Comment by DanielnetoDotCom** [comment]
Looks like something is crashed, can you please check your log file?

**Comment by kaptkrunch** [comment]
Hi,
I got it figured out, everything working great again!thanks

    On Sunday, April 7, 2019, 7:38:03 AM CDT, YouPHPTube <notifications@github.com> wrote:  
 
 
Looks like something is crashed, can you please check your log file?

**Comment by SubjectXXX** [comment]
What did you do to fix it?
And close the ticket..

**Comment by Martinsco12** [comment]
Site?

**Comment by kaptkrunch** [comment]
Medifrenzy.ninja

Sent from Yahoo Mail on Android 
 
  On Sun, Nov 17, 2019 at 4:49 AM, Martinsco12<notifications@github.com> wrote:   
Site?

**Comment by kaptkrunch** [comment]
This qas 8 months ago, i cant even begin to remember. Sorry
