### ISSUE TITLE
String problem configuration.php

### ISSUE THREAD

**Issue by TLCReuver** [YouPHPTube/YouPHPTube#1663]
The script in configuration.php is stripping the string not good for http://media.beesel-reuver.nl/
I had to force it at the bottom line.

if(!empty($_SERVER['SERVER_NAME'])){
    // get the subdirectory, if exists
    $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
    $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
    $global['webSiteRootURL'] = '';
}
$global['webSiteRootURL'] = 'http://media.beesel-reuver.nl/';  <=== forced

**Comment by DanielnetoDotCom** [comment]
sorry, I just found a bug on the last update.

also, your solution may work as well.

thanks

**Comment by gamalkamal** [comment]
> The script in configuration.php is stripping the string not good for http://media.beesel-reuver.nl/
> I had to force it at the bottom line.
> 
> if(!empty($_SERVER['SERVER_NAME'])){
> // get the subdirectory, if exists
> $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), **FILE**);
> $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
> }else{
> $global['webSiteRootURL'] = '';
> }
> $global['webSiteRootURL'] = 'http://media.beesel-reuver.nl/'; <=== forced

it doesnt work for me ..
bug reveals my root path folder instead of url

**Comment by nightstryke** [comment]
> sorry, I just found a bug on the last update.
> 
> also, your solution may work as well.
> 
> thanks

Have you fixed the bug?
Because I updated last night and my site isn't working with https or the encoder, but the site is working with http just not https/ssl.

**Comment by nightstryke** [comment]
> > The script in configuration.php is stripping the string not good for http://media.beesel-reuver.nl/
> > I had to force it at the bottom line.
> > if(!empty($_SERVER['SERVER_NAME'])){
> > // get the subdirectory, if exists
> > $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), **FILE**);
> > $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
> > }else{
> > $global['webSiteRootURL'] = '';
> > }
> > $global['webSiteRootURL'] = 'http://media.beesel-reuver.nl/'; <=== forced
> 
> it doesnt work for me ..
> bug reveals my root path folder instead of url

I think what @DanielnetoDotCom mean was just comment out or remove the string code and just use:
`$global['webSiteRootURL'] = 'http://www.yourdomainnamehere.com/';`
As the workaround until he can fix it. That's what I did since I use https primarily and it works. If your site doesn't use the www don't add it, but if it does use the www you need to add it.

**Comment by gamalkamal** [comment]
it works for my like this .. 

<?php
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;

$global['webSiteRootURL'] = ''; ==> dont insert link 
$global['systemRootPath'] = '/[root bath folder]/';
$global['salt'] = '5cb0d6652e22f';
$global['enableDDOSprotection'] = 0;
$global['ddosMaxConnections'] = 40;
$global['ddosSecondTimeout'] = 5;
$global['strictDDOSprotection'] = 0;

$mysqlHost = 'localhost';
$mysqlPort = '3306';
$mysqlUser = '[rootuser]';
$mysqlPass = '[sqlpassword]';
$mysqlDatabase = '[dbname]';

/**
 * Do NOT change from here
 */

require_once $global['systemRootPath'].'objects/include_config.php';

**Comment by nightstryke** [comment]
@DanielnetoDotCom Have  you fixed this issue yet?

**Comment by DanielnetoDotCom** [comment]
Yes, I guess so.

Sorry for not tell you before
