### ISSUE TITLE
If I use bulk upload my language breaks up.

### ISSUE THREAD

**Issue by jaewoo0** [YouPHPTube/YouPHPTube#1671]
![스크린샷, 2019-04-16 06-54-25](https://user-images.githubusercontent.com/49477718/56167932-8c3e0d00-6014-11e9-8507-6ccb0e02c8a8.png)
My language Korean breaks up. And I can't upload because of language breakup. If I change file name to English, it works fine. Is there anyway to use Korean? Thank you.

**Comment by jaewoo0** [comment]
changed listFiles.json.php file to
                $obj->path = $value;
                $obj->name = $path_parts['basename'];
and now it's not broken but 2/6 won't upload.

**Comment by DanielnetoDotCom** [comment]
@jaewoo0 is complicated to deal with those different charsets

I really recommend you to use just regular English characters
