### ISSUE TITLE
Only verified users can upload

### ISSUE THREAD

**Issue by Puyodead1** [YouPHPTube/YouPHPTube#1680]
![image](https://user-images.githubusercontent.com/14828766/56597414-65597b00-65c0-11e9-8f45-37ef7ef580fb.png)
Keeps saying "Only verified users can upload", The user is verified though...

**Comment by DanielnetoDotCom** [comment]
not sure what is happening, can you reproduce it on demo site?

**Comment by Puyodead1** [comment]
Doesn't look like I can reproduce it on the demo site. It seems to be working for now.
