### ISSUE TITLE
site is banned

### ISSUE THREAD

**Issue by jaewoo0** [YouPHPTube/YouPHPTube#1681]
Why is my site banned? They are not porn just sexy videos with no nudity.

**Comment by DanielnetoDotCom** [comment]
What is your site URL, we will review it

**Comment by jaewoo0** [comment]
https://videeo.club
https://www.videeo.club

**Comment by DanielnetoDotCom** [comment]
Your site is so close to a porn site, besides what is most disgusting is the pedophilia content.

pedophilia is worse than pornographic content. I'm sorry but I will never allow it.

![image](https://user-images.githubusercontent.com/18009293/56657011-52e94b00-666d-11e9-87e6-c9e7245d40ed.png)
