### ISSUE TITLE
Can't save Site Settings at all

### ISSUE THREAD

**Issue by reltek** [YouPHPTube/YouPHPTube#1685]
Hello,

I recently downloaded youphptube script and started a website. Right now, I am going through its Site Settings and trying to make changes. However, my changes don't get saved. Yes, I have run up and down the Internet and on this forum for similar issues and I still can't fix my issue. Please, help... thank you.

**Comment by reltek** [comment]
I wish someone could give me some idea why my changes to the site settings is not being saved. I am sitting here hacking the PHP files and resetting the default values to get I what I want shown on the website. Thanks in advance.

**Comment by DanielnetoDotCom** [comment]
Check your log file , it may also be a permission problem

**Comment by reltek** [comment]
Hi Daniel,

Thank you for your reply and Thank for this awesome script.

I did look at the log file youphptube.log file and this is what I saw. These lines are last few of them.

**
[28-Apr-2019 21:28:41 America/Chicago] [ERROR] Error saving plugin CustomizeAdvanced data. Maybe plugin is not enabled?
[28-Apr-2019 21:28:47 America/Chicago] [ERROR] Error saving plugin CustomizeUser data. Maybe plugin is not enabled?
[28-Apr-2019 21:28:51 America/Chicago] [ERROR] Error saving plugin CustomizeUser data. Maybe plugin is not enabled?**

What does it mean "Maybe plugin is not enabled?" Is there is a plugin I need to download for me to be able to save configuration settings.

**Comment by reltek** [comment]
COOOL... Thank you for your suggestion Daniel... Now I solved this issue.
For those who might come across this problem in the future, If you find yourself not being able to save configuration settings, first check your log file... it is located in the video folder with your www or public_html folder in there you will find youtubephp.log. In there look at the last few lines or the latest log. If it says **Error saving plugin CustomizeUser data. Maybe plugin is not enabled?**, then login as an admin on your website, go to plugin page and enable customsizerAdvanced and customsizerUser plugins. DONE! :)
