### ISSUE TITLE
How to encode/upload MKV file with Dual Audio and Subtitle tracks?

### ISSUE THREAD

**Issue by honeyfairy** [YouPHPTube/YouPHPTube#1688]
I tried uploading an MKV file that has dual audio, English and Japanese and an English Subtitle track.

But after encoding i can watch it only in english audio and I do not see where I can change the audio track nor how I can display the subtitle track.

**Comment by DanielnetoDotCom** [comment]
there is no option to switch the audio track

**Comment by gamersalpha** [comment]
why close is a features
please
it' was so cool to add this
