### ISSUE TITLE
Streamer direct upload hanging...

### ISSUE THREAD

**Issue by codelance** [YouPHPTube/YouPHPTube#1692]
Running into a bit of trouble trying to do a direct upload. 

I've installed streamer using the dockerfile within the repository. 

Streamer is currently pointed at the public encoder. 

When clicking direct upload I get the following screen below that just hangs:

<img width="1422" alt="Screen Shot 2019-04-29 at 1 13 54 AM" src="https://user-images.githubusercontent.com/882897/56881017-36a62f00-6a1c-11e9-9eac-495d8af81507.png">

The following logs were in the javascript console:

```
An invalid form control with name='' is not focusable.
GET https://<streamer-server-url>/view/img/image404.php?notFound=1 404 (Not Found)
```

No new logs in youphptube.log.

Wondering if I might be missing something or if you could point me in the right direction to troubleshoot further.

**Comment by DanielnetoDotCom** [comment]
Please check your YouPHPTube error log

check this https://github.com/YouPHPTube/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by codelance** [comment]
I was able to figure it out. The video tags plugin was generating a warning that came back in the 

```objects/videoAddNew.json.php``` ajax request. 

I fixed the code to remove get rid of the warning and things started working.
