### ISSUE TITLE
Infinite Loading

### ISSUE THREAD

**Issue by Puyodead1** [YouPHPTube/YouPHPTube#1693]
After turning on the SecureVideosDirectory, the site won't load, it sits loading infinitely. Not sure what to do, there is nothing in apache2 access logs or error logs or any youphptube logs.

Edit: i should also mention that i'm using a cloud mounted google drive for the videos directory, it has access, there are no errors in the logs, but it just wont load. if i move it to a local videos directory it works fine

**Comment by DanielnetoDotCom** [comment]
I am not sure what happened. It must be something on your log file.

If you can try to inactive are securevideosdirectory plugin direct into the database , and your site should come back

Also check if you properly configure the xsendfile

**Comment by Puyodead1** [comment]
> I am not sure what happened. It must be something on your log file.
> 
> If you can try to inactive are securevideosdirectory plugin direct into the database , and your site should come back
> 
> Also check if you properly configure the xsendfile

So, i removed all the logs from YouPHPTube and apache2, started apache and triedto connect.
Logs from ``youphptube.log``:
```[29-Apr-2019 11:06:45 America/New_York] user::login: noPass = , encodedPass = 1, this->user, Puyodead1 xxx.xxx.xxx.xxx
[29-Apr-2019 11:06:47 America/New_York] encryptPasswordVerify: do not encrypt
[29-Apr-2019 11:06:49 America/New_York] user::login: Do login without cookie
[29-Apr-2019 11:06:50 America/New_York] user::login: noPass = , encodedPass = 1, this->user, Puyodead1 xxx.xxx.xxx.xxx
[29-Apr-2019 11:06:52 America/New_York] user::recreateLoginFromCookie: do cookie-login: Puyodead1   result: 0
[29-Apr-2019 11:06:54 America/New_York] encryptPasswordVerify: do not encrypt
[29-Apr-2019 11:06:54 America/New_York] success 1
[29-Apr-2019 11:06:57 America/New_York] user::login: Do login without cookie
[29-Apr-2019 11:06:59 America/New_York] user::recreateLoginFromCookie: do cookie-login: Puyodead1   result: 0
[29-Apr-2019 11:07:00 America/New_York] success 1
```
Apache error log:
```[Mon Apr 29 11:06:32.732375 2019] [mpm_prefork:notice] [pid 12587] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.0g configured -- resuming normal operations
[Mon Apr 29 11:06:32.732468 2019] [core:notice] [pid 12587] AH00094: Command line: '/usr/sbin/apache2'
```

Apache access log: 
```xxx.xxx.xxx.xxx - - [29/Apr/2019:11:12:55 -0400] "GET / HTTP/1.1" 200 240 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36"
```

Apache directory config:
```<Directory /var/www/html/YouPHPTube>
    Options Indexes FollowSymLinks
    XSendFile on
    XSendFilePath /var/www/html/YouPHPTube
    AllowOverride All
    Require all granted
    Order Allow,Deny
    Allow from All
</Directory>
```

SecureVideosDirectory plugin and Cache plugin have been disabled in mysql
Not sure if it makes a difference but when i enabled securevideosdirectory, it tried to pull resources from https://mydomain/var/www/drive/videos/ so i had to edit the config file and remove the sub directory checks

**Comment by Puyodead1** [comment]
This is what i mean with the sub directory issue: 
```<url>
<loc>https://sqlinjection.tk/var/www/drive/help</loc>
<lastmod>2019-04-29T11:26:54+00:00</lastmod>
<changefreq>monthly</changefreq>
<priority>0.50</priority>
</url>```
https://sqlinjection.tk/sitemap.xml

**Comment by Puyodead1** [comment]
So now I removed all the videos from the mysql table (backed up the table), and now the page loads, but its not loading any assets (js, css, etc)
![image](https://user-images.githubusercontent.com/14828766/56908584-94666580-6a74-11e9-8327-aba7b6242254.png)

also, i as able to play the videos directly via /videos/videosname_HD.mp4

**Comment by Puyodead1** [comment]
This is weird. If i remove all the videos from mysql and edit the config (removing the else statment for the subdirectory) i can access the site just fine. I have uploaded one, 15 second video and i still am seeing slow response times with YouPHPTube only. I also am seeing this:
![image](https://user-images.githubusercontent.com/14828766/56927076-3d2aba00-6aa1-11e9-84ea-28bde319c37e.png)

**Comment by DanielnetoDotCom** [comment]
Hi

1 - make 2 things, make sure you have the latest version of youphptube
2 - remove the option for auto create URL from your **videos/configuration.php** file
replace

` if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) { `

for this

 if(**false &&** !empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) { 

```
<?php
$global['configurationVersion'] = 2;
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
if(false && !empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) { 
    // get the subdirectory, if exists
    $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
    $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
    $global['webSiteRootURL'] = 'http://gdrive.local/YouPHPTube/';
}
$global['systemRootPath'] = '/home/daniel/htdocs/YouPHPTube/';
$global['salt'] = '5c518c20e172c';
$global['enableDDOSprotection'] = 1;
$global['ddosMaxConnections'] = 40;
$global['ddosSecondTimeout'] = 5;
$global['strictDDOSprotection'] = 0;

$mysqlHost = 'localhost';
$mysqlUser = '*****';
$mysqlPass = '********';
$mysqlDatabase = 'youPHPTube';

/**
 * Do NOT change from here
 */

require_once $global['systemRootPath'].'objects/include_config.php';

```

**Comment by Puyodead1** [comment]
I am running the latest version, reinstalled even yesterday. 
I have changed the line in the config.

**Comment by Puyodead1** [comment]
I can now access the site with this:
```if(false && !empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) { 
    // get the subdirectory, if exists
    $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
    $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
    $global['webSiteRootURL'] = 'http://gdrive.local/YouPHPTube/';
}``` I was using ``$global['webSiteRootURL'] = 'http://gdrive.local/YouPHPTube/';`` before. Still having some slowness issues

**Comment by DanielnetoDotCom** [comment]
did you changed the URL correct?

this is for my local server only

**$global['webSiteRootURL'] = 'http://change.it/';**

**Comment by Puyodead1** [comment]
> did you changed the URL correct?
> 
> this is for my local server only
> 
> **$global['webSiteRootURL'] = 'http://change.it/';**

Yes, i did

```if(false && !empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) {
    // get the subdirectory, if exists
    $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
    $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
    $global['webSiteRootURL'] = 'https://sqlinjection.tk/';
}
```

**Comment by DanielnetoDotCom** [comment]
and is it working now?

what problem are you having now?

another thing you can do, re-download the SecureVideosDirectory plugin from the website https://www.youphptube.com/plugins/. some times there are updates

**Comment by Puyodead1** [comment]
I will try redownloading it, the issue right now is slow response from YouPHPTube, other pages i have running on the site work/respond pretty quick. YouPHPTube is taking ~15 seconds to load a page

**Comment by Puyodead1** [comment]
I re-downloaded the plugin, same issue. Slow loading times for all YouPHPTube pages. 
https://sqlinjection.tk/

**Comment by DanielnetoDotCom** [comment]
If you disable the SecureVideosDirectory does the script work correctly?

did you install the apache xsendfile?

**Comment by Puyodead1** [comment]
I think I fixed the slowness, My guess is a combination of using a cloud mounted GDrive and permission issues
