### ISSUE TITLE
0 Video in Myvideo and 852 in the system.

### ISSUE THREAD

**Issue by TLCReuver** [YouPHPTube/YouPHPTube#1695]
Hello Daniel,

Because i couldn't upgrade to sql 5,7 i moved ypt to another system with betters specs.
The whole YouPHPTube is 1:1 copied as well as the youtube.sql with Php7.3 and everything seem te be allright. All 852 videos i can see, edit & uploading are no ploblem.

But... in my dashboard i see 0 videos an 0 users as wel as in myvideos. I tried to restore with the backup-plugin and go back to 7.0 but without any result.

What can be wrong ? 

![Snap1](https://user-images.githubusercontent.com/39981177/56906082-d528a380-6aa1-11e9-927c-c487c1097282.jpg)
![Snap2](https://user-images.githubusercontent.com/39981177/56906102-dc4fb180-6aa1-11e9-936b-3afda7c8bac4.jpg)

![Snap3](https://user-images.githubusercontent.com/39981177/56906315-41a3a280-6aa2-11e9-9b57-eeb4bab32a02.jpg)
![Snap4](https://user-images.githubusercontent.com/39981177/56906326-45cfc000-6aa2-11e9-9d9b-c3260145bd15.jpg)

**Comment by DanielnetoDotCom** [comment]
check the error log https://github.com/YouPHPTube/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by TLCReuver** [comment]
I allready looked at the logs and in the Web Developer menu from Firefox i see nothing special.

Due importing i become an error in 3 different  PHP-versions an 2 different SQL-versions, maybe is there the solution ?!
![Snap5](https://user-images.githubusercontent.com/39981177/56962041-ce5b6880-6b55-11e9-9b48-64af012bf717.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, I am not talking about the firefox error, I am talking about your server error.

**Comment by TLCReuver** [comment]
Hi,
No server errors from YPT, apache, SQL, PHP & firefoxplugin i used for tracing & logging de sources and of course not for firefox errors. Problem solved to backup imported sql with 0 files in myvidos (with backup plugin) and restore it back.  Very strange behaviour but it's solved. Thanks.

**Comment by DanielnetoDotCom** [comment]
Great
