### ISSUE TITLE
Is there a way to reset the site configuration?

### ISSUE THREAD

**Issue by reltek** [YouPHPTube/YouPHPTube#1696]
I made some changes and the site is acting weird. I can't access site settings. So, is there a easy way to reset to the old or default settings for the script?

**Comment by DanielnetoDotCom** [comment]
Hi, try to truncate the plugins table

**Comment by reltek** [comment]
Thank you, Daniel. The more I work with your script the more I learn. I simply truncated the plugins table and the site was back square one... Thanks.
