### ISSUE TITLE
view/include/social.php title error

### ISSUE THREAD

**Issue by nfsiv** [YouPHPTube/YouPHPTube#1699]
good day Daniel,

today i found there is a title typo mistake in the soical.php, line 18, the linkedin was titled as Twitter.

<li><a href="<?php echo $linkedin; ?>" target="_blank"  class="icoLinkedin" title="Twitter"><i class="fab fa-linkedin-in"></i></a></li>

thank you very much.

**Comment by DanielnetoDotCom** [comment]
Thank you so much
