### ISSUE TITLE
Undefined variable getCN

### ISSUE THREAD

**Issue by Puyodead1** [YouPHPTube/YouPHPTube#1701]
``PHP Notice:  Undefined variable: getCN in /var/www/html/YouPHPTube/view/trending.php on line 66``

``PHP Warning:  http_build_query(): Parameter 1 expected to be Array or Object.  Incorrect value given in /var/www/html/YouPHPTube/objects/video.php on line 2234
``

Is this an issue on my end?

**Comment by DanielnetoDotCom** [comment]
> PHP Notice: Undefined variable: getCN in /var/www/html/YouPHPTube/view/trending.php on line 66

this should not be a problem, but anyway I sent a fix to not see it anymore

> PHP Warning: http_build_query(): Parameter 1 expected to be Array or Object. Incorrect value given in /var/www/html/YouPHPTube/objects/video.php on line 2234 

this may be a problem, when does this happen?

**Comment by Puyodead1** [comment]
Okay cool.

I'm seeing if i can find where the error first occurs. Will let you know if when/if I can.

**Comment by Puyodead1** [comment]
Can't get it again so I'm going to close this.
