### ISSUE TITLE
Do I have to purchase and install MP4thumbnailGif plugin to show thumbnails for the videos?

### ISSUE THREAD

**Issue by reltek** [YouPHPTube/YouPHPTube#1703]
Hi Daniel,

I did read an earlier questions posted by others users regarding this issue. I uploaded a video and uploaded a thumbnail to go along with that video. After it was uploaded, I saw my video with the thumbnail I uploaded it with under my account. However, when I go to the main page, that same video has 404 Not Found Error thumbnail. Is that mean I MUST purchase the PLUGIN to get rid of that 404 error thumbnail? Thanks again for this awesome script, Daniel.

**Comment by DanielnetoDotCom** [comment]
Hi

The MP4thumbnailGif is only for automatic extract images from a directly uploaded video.

if you use encoder, it will be automatically extracted.

if you directly upload it without the plugin you will get the 404 image, but you can change this image on the videos manager and upload your custom image

**Comment by reltek** [comment]
I don't know what you mean by video manager. Do you mean Video Form (video manager) that pops up when you directly upload a video with meta data, images and upload tabs? if that is what you mean, image tab gives you the option to upload your own thumbnail for the video. However, thumbnail for the video only shows up within the video list page not the main page where the video is displayed. 

I tried to install the encoder on the webhosting webpace I purchased, but it turns out that the company don't allow such installation especially ffmpeg. So, for now I am stuck with public encoder until I setup my own webserver and install the script.

**Comment by reltek** [comment]
Hi Daniel,
It is interesting that now I am able to change the thumbnail and even the public encoder that linked to my website is working too... before my videos would be stuck on encoding status for days... :) So, maybe there was no problem. It was just the fact that the public encoder was having an issue. :)
