### ISSUE TITLE
Typo in TopMenu plugin

### ISSUE THREAD

**Issue by brandonjohnson** [YouPHPTube/YouPHPTube#1714]
should be

"Edit Menu Items"

not

"Edit Menu Itens"
<img width="601" alt="Screen Shot 2019-05-07 at 2 11 27 PM" src="https://user-images.githubusercontent.com/667375/57333630-39ff8180-70d2-11e9-98c1-6714a0073d92.png">

**Comment by DanielnetoDotCom** [comment]
Thanks I will send a fix for that
