### ISSUE TITLE
Does YouPHPTube support PHP 7.3.x?

### ISSUE THREAD

**Issue by ScottCrumpler** [YouPHPTube/YouPHPTube#1719]
I'm excited to try out YouPHPTube, but based on the Readme it looks like the server requirements are PHP 5.6+  Has it been tested with PHP 7.3.x?  I wouldn't want to install it using a deprecated version of PHP.

Cheers,
Scott

**Comment by DanielnetoDotCom** [comment]
Hi

I have teste it untill 7.2 but I can see no reason to not work on 7.3

**Comment by TLCReuver** [comment]
No problems in 7.3.4

![Snap6](https://user-images.githubusercontent.com/39981177/57517579-74a62b80-7317-11e9-9c91-8d183308a4f9.jpg)

**Comment by DanielnetoDotCom** [comment]
Great, thanks for the update
