### ISSUE TITLE
User page not loading any user

### ISSUE THREAD

**Issue by opmat** [YouPHPTube/YouPHPTube#1723]
Hi!

Thanks for the great work you have done with youphptube.
However, I discovered that clicking on the user page, no user was listed.

What can be the issue?

**Comment by DanielnetoDotCom** [comment]
Hi how are you?

thanks

does it happen on demo site?

what do you see on your log file?

**Comment by opmat** [comment]
Hi 

I have been able to resolve this. My last Pull was March 24, I simply ran git pull and updated the db.

Thanks once again
