### ISSUE TITLE
Inline video player on Iphones 

### ISSUE THREAD

**Issue by partystreamsk** [YouPHPTube/YouPHPTube#1728]
Hi , how can i do that player will be inline on iphones? when i try to play my live stream on iphone ,the video go in full screen. thanks. than i wanna know how can i list my livestream on home page because its only accessible from LIVE URL and stream is offline by the way. Thank you for this great project.

**Comment by DanielnetoDotCom** [comment]
Hi

VOD videos are fine on iOS?

Only Live are going full screen?

**Comment by partystreamsk** [comment]
Booth are going in full screen

**Comment by DanielnetoDotCom** [comment]
Are you running version YouPHPTube 7.2?

**Comment by partystreamsk** [comment]
Yes ,Its the latest

**Comment by DanielnetoDotCom** [comment]
I guess the inline attribute is there, I am not sure why is not working.

what iOS version and iPhone model are you using?

**Comment by partystreamsk** [comment]
Its 12.3 and iPhone x. I dont know. Can you tell me where i can check/add this attribute? Btw on android works fine

**Comment by DanielnetoDotCom** [comment]
search the code for the <video> tags inside the YouPHPTube/view/ directory.

**Comment by partystreamsk** [comment]
Can you tell me which file is related ti the live stream view? Thanks

**Comment by DanielnetoDotCom** [comment]
Live stream should be inside the Live plugin

https://github.com/YouPHPTube/YouPHPTube/blob/f57484953e38924ecec049b1beb4e9663a75716d/plugin/Live/view/liveVideo.php#L15

**Comment by partystreamsk** [comment]
Hi, sorry. I was on the phone so now i see that i have youphptube version 7.0. I thought that i have latest update because after click on "Update version" i get message "Your system is up to date". Now im on pc and see that. Than the uploaded videos are runing fine in inline player so issue is only on live stream.

**Comment by partystreamsk** [comment]
Ok solved. Added "playsinline" before controls on Line 15. Now it works on iOs too.Thank you
