### ISSUE TITLE
Locale Translator: Website not opening

### ISSUE THREAD

**Issue by Commifreak** [YouPHPTube/YouPHPTube#1729]
When I access /locale/ to start translation, FireFox does not show any content. It just discard the web-page.

tl;dr

Via curl, I figured out, that the script set hundreds of `Set-Cookie: PHPSESSID=ipghe17m6930s2eck2u211nghe; expires=Wed, 15-May-2019 05:52:20 GMT; Max-Age=3600; path=/` which is too large for an answer Header.

The cause must be this: `url_get_contents` @ https://github.com/YouPHPTube/YouPHPTube/blob/master/locale/index.php#L18

Simply replacing this with `file_get_contents` fixed the error for me.

Another thing: Why can't I just update an existing translation? With this tool I have an empty translation textarea - but I want to update an existing language. How to proceed?

**Comment by DanielnetoDotCom** [comment]
Hi
the locale script was disabled due to the number of files we have to scan.

the best way now is to copy an existing file and copy it. then edit it with your translation

**Comment by Commifreak** [comment]
The locale script is not yet disabled. I fixed it to work again in #1744 . This PR includes german updates and enhancewments to locale translator. Feel free to edit/comment as you need ;)

**Comment by DanielnetoDotCom** [comment]
Merged, thanks
