### ISSUE TITLE
LiveChat Problem

### ISSUE THREAD

**Issue by partystreamsk** [YouPHPTube/YouPHPTube#1731]
Hi , when i try use the command for chat:
 "nohup php /var/www/vhosts/partystream.sk/httpdocs/plugin/LiveChat/chat-server.php &"
 i get error : 
"nohup: ignoring input and appending output to ‘nohup.out" 

when i open file "nohup.out" i see message inside : 
"Could not open input file: /var/www/html/YouPHPTube/plugin/LiveChat/chat-server.php"

Can you help me with that? thanks

**Comment by DanielnetoDotCom** [comment]
try to run without nohup to see if you can get any other clue

I am not sure where this address are comming from " /var/www/html/YouPHPTube/plugin/LiveChat/chat-server.php"

**Comment by partystreamsk** [comment]
In my case i tried run" sudo php /var/www/vhosts/partystream.sk/httpdocs/plugin/LiveChat/chat-server.php & "
i get: [6] 26999 
and when i press enter i get: [6]+  Stopped                 sudo php /var/www/vhosts/partystream.sk/httpdocs/plugin/LiveChat/chat-server.php

**Comment by DanielnetoDotCom** [comment]
Question: are you using https?
if yes you need to configure proxy_wstunnel

`sudo nano /etc/apache2/mods-available/proxy.conf`

```
<IfModule mod_proxy.c>
        ProxyPass /wss/ ws://127.0.0.1:8888/
</IfModule>
```

`sudo a2enmod proxy_wstunnel && sudo /etc/init.d/apache2 restart`

if you start the chat with nohup what is on your erro.log?

**Comment by partystreamsk** [comment]
So, i fixed proxy_wstunnel. 
Now when i run : " sudo php /var/www/vhosts/partystream.sk/httpdocs/plugin/LiveChat/chat-server.php & " i get no output,its like ok but nothings happen.
When i add "nohup" i get this : 

"[dbarancik@server ~]$ sudo nohup php /var/www/vhosts/partystream.sk/httpdocs/plugin/LiveChat/chat-server.php &
[1] 9683
[dbarancik@server ~]$ nohup: ignoring input and appending output to ‘nohup.out’

[1]+  Exit 255                sudo nohup php /var/www/vhosts/partystream.sk/httpdocs/plugin/LiveChat/chat-server.php
[dbarancik@server ~]$
"

**Comment by DanielnetoDotCom** [comment]
It should output nothing 

Now you have to check your plugin configuration and js errors

Also try to run a telnet on port 8888 to see if the chat is running.

Also check the Youphptube error log

**Comment by partystreamsk** [comment]
I really tried everything but without success.. Its possible that i have this issue because im using centos 7? Im really desperate. Can you help me or i must look for any external chat ? thanks

**Comment by DanielnetoDotCom** [comment]
Maybe is centos, we really only test it on Ubuntu

**Comment by partystreamsk** [comment]
I solved it by installing 3rd party chat in live. I dont know why but i have problems with websocket. But thanks
