### ISSUE TITLE
[BUG] Queue Log Always Empty --- even on your demo site

### ISSUE THREAD

**Issue by bloomberg21** [YouPHPTube/YouPHPTube#1738]
As titled the **Queue Log is Always Empty** --- even on your demo site located at:

https://network.youphptube.com/

Yet in your marketing materials you show it fully populated which is a little misleading?

![image](https://user-images.githubusercontent.com/50684644/58002354-f7a35080-7a92-11e9-82aa-943a9a1797e5.png)

**Comment by DanielnetoDotCom** [comment]
Sorry, I can not see any issue on that?
