### ISSUE TITLE
[BUG] Bulk Encode Buttons unusable

### ISSUE THREAD

**Issue by bloomberg21** [YouPHPTube/YouPHPTube#1739]
When in the encoder and selecting >>>  BULK ENCODE.

**LIST FILES PULLDOWN**
_Actual:_ does nothing when clicked. 
_Expected Result:_ When clicked , show options for different possible views
**IF not... recommended to remove as it is useless.**

**CHECK BOX** 
_Actual:_ Can't uncheck or do anything with this at all including the useless box beside it to the right.
_Expected Result:_ Toggle check mark ON or OFF and to have some function associated with it.
**IF not... recommended to remove as it is useless.**

![image](https://user-images.githubusercontent.com/50684644/58002613-a9428180-7a93-11e9-95ad-b9b7e7bf9269.png)

**Comment by DanielnetoDotCom** [comment]
you need to add a valid local absolute path, before click on List Files

**Comment by bloomberg21** [comment]
so don't show it unless a path is given maybe?

Really the admin should be the only one to see this as it is an internal [LOCAL] path no?

**Comment by bloomberg21** [comment]
would be better served to have the ability to upload a CSV containing bulk links to videos imo

**Comment by DanielnetoDotCom** [comment]
nitpicker message, NOT a bug
