### ISSUE TITLE
[Question] How to increase Streamer Max File Size 

### ISSUE THREAD

**Issue by bloomberg21** [YouPHPTube/YouPHPTube#1741]
How to increase Streamer Max File Size ?

![image](https://user-images.githubusercontent.com/50684644/58005343-4f918580-7a9a-11e9-92fa-e05b3f01f2b8.png)

**Comment by bloomberg21** [comment]
I believe that it is root cause of this issue I am experiencing:

![image](https://user-images.githubusercontent.com/50684644/58009548-8ae48200-7aa3-11e9-8355-3db0bd4c60e9.png)

**Comment by nfsiv** [comment]
in my mind, it is in the php.ini (in my computer, /etc/php/7.2/apache2/php.ini

**Comment by bloomberg21** [comment]
@nfsiv 

First place I went... No love. :(

**Comment by bloomberg21** [comment]
ok...... DUH@me

I am running one server for the encoder and one for the webserver.

Yes, it was in the php.ini BUT on the webserver (aka web streamer)

Success.... closing.

![image](https://user-images.githubusercontent.com/50684644/58016156-ce45ed00-7ab1-11e9-9035-bfda3288de0a.png)
