### ISSUE TITLE
video ads can not click

### ISSUE THREAD

**Issue by gchenfly** [YouPHPTube/YouPHPTube#1747]
hi.
my web can show video ads. but it can not click.

**Comment by DanielnetoDotCom** [comment]
Sorry I dont understand

**Comment by gchenfly** [comment]
please see the attach photo.
there is ad mark, i want to click the ad mark, and jump to ads content web.
<img width="883" alt="屏幕快照 2019-05-22 19 58 09" src="https://user-images.githubusercontent.com/34537998/58172848-4e479f00-7ccc-11e9-91de-0e511281465e.png">

**Comment by gchenfly** [comment]
this is youtube ads.
and i can click the ad website link.
<img width="784" alt="屏幕快照 2019-05-22 20 07 08" src="https://user-images.githubusercontent.com/34537998/58173208-594eff00-7ccd-11e9-93b7-0527df8ef2fa.png">

**Comment by DanielnetoDotCom** [comment]
I sill do not get where do you want to click

**Comment by gchenfly** [comment]
oh, it is strange.
I check the demo site, i can click the full ads screen.
but why i can not click in my web.

**Comment by gchenfly** [comment]
here is my draft web:http://34.80.250.65/YouPHPTube.
Could you check it for me?

**Comment by gchenfly** [comment]
ha, i find the problem!
i make a simple mistake.:)

**Comment by gchenfly** [comment]
another question, how i can set two ads like this.
<img width="879" alt="屏幕快照 2019-05-22 20 39 27" src="https://user-images.githubusercontent.com/34537998/58175018-c795c080-7cd1-11e9-8b6c-081230200c47.png">

**Comment by DanielnetoDotCom** [comment]
On the GoogleAds_IMA plugin check the preAdTagUrl

![image](https://user-images.githubusercontent.com/18009293/58180451-82956e00-7c80-11e9-933e-d5ddb44f93d3.png)
