### ISSUE TITLE
[BUG] Sub categories not showing up as useful

### ISSUE THREAD

**Issue by bloomberg21** [YouPHPTube/YouPHPTube#1748]
If you create a CATEGORY and then CREATE Sub Categories nested within the parent Category... when a user uploads a video.... he is not shown the nested category as nested but as a main category.

**Categories Examples:**

Wowza [parent]
Hello [parent]
Something [parent]
          |
          |----- else [child]
          |----- hello [child]
          |----- wowza [child]

The list of categories when uploading will look like:

else
hello
Hello
Something
Wowza
wowza

There is no way to distinguish between a parent or child in that view.

It should look like:

Hello [parent]
**+**Something [parent] -- the + expands the parent category and signifies there are child categories
          |
          |----- else [child]
          |----- hello [child]
          |----- wowza [child]

Wowza [parent]

**Comment by DanielnetoDotCom** [comment]
Are you sure it is a bug?
