### ISSUE TITLE
[BUG] dashboards alignment

### ISSUE THREAD

**Issue by bloomberg21** [YouPHPTube/YouPHPTube#1749]
While I appreciate a good dashboard in any app.

The Rule of thumb is at the least it must look professional with useful metrics  and not appear hacked together because a competitor has one.

Misalignment makes the dashboard appear as a hack job.

![image](https://user-images.githubusercontent.com/50684644/58210548-8afca180-7c9e-11e9-8b93-6b45e17871ef.png)

**Expected:**  The boxes should be same size and in alignment with each other to offer an aesthetically pleasing view.

**Comment by DanielnetoDotCom** [comment]
nitpicker message, NOT a bug
