### ISSUE TITLE
[BUG] Chromecast plugin enabled so... where is it?

### ISSUE THREAD

**Issue by bloomberg21** [YouPHPTube/YouPHPTube#1750]
Chromecast plugin is enabled but does not show up on the player.

**Plugin enabled:**
![image](https://user-images.githubusercontent.com/50684644/58211133-f4c97b00-7c9f-11e9-98a3-55415242a516.png)

Player on YouPHPtube website with no icon displayed:

![image](https://user-images.githubusercontent.com/50684644/58211204-1f1b3880-7ca0-11e9-8f30-eee8c99029f0.png)

Player on YouTube showing actual icon:

![image](https://user-images.githubusercontent.com/50684644/58211253-4245e800-7ca0-11e9-829b-ad315e775446.png)

**Comment by bloomberg21** [comment]
David I hope when you QA the app you just don't QA it from your phone ...*sigh*

**Comment by DanielnetoDotCom** [comment]
nitpicker message, NOT a bug
