### ISSUE TITLE
S3 Plug installed; deletion of files

### ISSUE THREAD

**Issue by spqr1** [YouPHPTube/YouPHPTube#1756]
I have the AWS s3 plugin installed and can now upload and download after  digging through many files and everything not documented but...

My Q is:

When a user DELETES a video on the websever side.... does it delete the file in S3 too?

Or will this just become a heap of garbled unknown videos that no one will know is actually valid or not?

**Comment by DanielnetoDotCom** [comment]
If you delete using the YouPHPTube videos manager, yes, it will also delete on  S3

**Comment by spqr1** [comment]
mine does not delete the s3 files...

**Comment by spqr1** [comment]
does this look right?

-rw-r--r--  1 www-data www-data 15384 May 23 06:19 Livesearch.php
-rw-r--r--  1 www-data www-data 36536 May 23 06:19 footer.php
-rw-r--r--  1 www-data www-data 20664 May 23 06:19 myVideos.json.php

**Comment by DanielnetoDotCom** [comment]
It should delete. I just try here and it works
 can you check on your log file is there is an error when you delete the video?

**Comment by spqr1** [comment]
from the weberver:

[24-May-2019 13:57:54 America/Los_Angeles] PHP Fatal error:  Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/html/plugin/AWS_S3/aws/Aws/Api/Parser/$
Stack trace:
#0 /var/www/html/plugin/AWS_S3/aws/Aws/Api/Parser/RestXmlParser.php(33): Aws\Api\Parser\RestXmlParser->parseXml(Object(GuzzleHttp\Psr7\Stream))
#1 /var/www/html/plugin/AWS_S3/aws/Aws/Api/Parser/AbstractRestParser.php(62): Aws\Api\Parser\RestXmlParser->payload(Object(GuzzleHttp\Psr7\Response), Object(Aws\A$
#2 /var/www/html/plugin/AWS_S3/aws/Aws/S3/RetryableMalformedResponseParser.php(37): Aws\Api\Parser\AbstractRestParser->__invoke(Object(Aws\Command), Object(Guzzle$
#3 /var/www/html/plugin/AWS_S3/aws/Aws/S3/AmbiguousSuccessParser.php(58): Aws\S3\RetryableMalformedResponseParser->__invoke(Object(Aws\Command), Object(GuzzleHttp$
#4 /var/www/html/plugin/AWS_S3/aws/Aws/S3/GetBucketLocationParser.php(30): Aws\S3\AmbiguousSuccessParser->__invoke(Object(Aws\Command), Object(GuzzleHttp\Psr7\Res$
#5 /var/www/html/pl in /var/www/html/plugin/AWS_S3/aws/Aws/Api/Parser/PayloadParserTrait.php on line 39

**Comment by spqr1** [comment]
also many many  tmpFile's left behind in /videos DIR

ie.

.
-rw-r--r--  1 www-data www-data 1494008465 May 24 04:01 89_tmpFile_converted_SD.   
-rw-r--r--  1 www-data www-data  423489707 May 24 04:02 90_tmpFile.mp4

**End result:** Filling op the drive very quickly

**Comment by DanielnetoDotCom** [comment]
Hi did you fix the fatal error? 

`PHP Fatal error: Uncaught Error: Class 'SimpleXMLElement' not found`

About the tmpFile it looks like an encoder file, am I correct?

make sure you have the autodelete enabled on the encoder.

**Comment by spqr1** [comment]
no this error persists

PHP Fatal error: Uncaught Error: Class 'SimpleXMLElement' not found

**Comment by DanielnetoDotCom** [comment]
Hi

This is a php server problem , not a script problem .

Try to Google a solution  for that

**Comment by spqr1** [comment]
got it working...

**solution:** 
autodelete enabled on the encoder
