### ISSUE TITLE
Live search PAID plugin issues

### ISSUE THREAD

**Issue by spqr1** [YouPHPTube/YouPHPTube#1757]
I installed this plugin and it works fine in desktop browser... wish I could remove the BLUE highlight or change the color, ugh and the scroll bar.... but....

When i load the site on an actual mobile device (running android)... the search does not accept any input at all making it tough. :(

**Comment by DanielnetoDotCom** [comment]
Hi, I am aware the live search needs improvements, I just sent few, can you please download it again and check?

**Comment by spqr1** [comment]
I literally d/l'd it  a few hrs ago... when was your last commit to it?

**Comment by DanielnetoDotCom** [comment]
Just now, I start to modify after your post

**Comment by spqr1** [comment]
do i just install on top or is there an uninstall procedure?

**Comment by spqr1** [comment]
version #'s on files would be most helpful

**Comment by spqr1** [comment]
upgraded/uploaded newest version...

Better.... 

Drop down shows of results now but...

Is the intention that that is the ONLY way to select from search results..... 

What if the user doesnt select any of the drop results and just presses enter.

Do they not get ALL results on another page or are they only getting the drop down search results?

**Comment by DanielnetoDotCom** [comment]
Thanks , I just sent a new update, please check it

**Comment by spqr1** [comment]
same issues as my last post.... no change

**Comment by DanielnetoDotCom** [comment]
hi, I am not sure what you are getting.

can you please test the demo site?

we have the latest livesearch version there, and looks lite it is working fine for me.

**Comment by spqr1** [comment]
nope... mine doesnt work the same I guess.

What permissions are needed on the plugin files?

**Comment by spqr1** [comment]
does this look right?

-rw-r--r-- 1 www-data www-data 15384 May 23 06:19 Livesearch.php
-rw-r--r-- 1 www-data www-data 36536 May 23 06:19 footer.php
-rw-r--r-- 1 www-data www-data 20664 May 23 06:19 myVideos.json.php

**Comment by DanielnetoDotCom** [comment]
Hi, the permissions look right for me.

Did you try to reproduce it on demo site?

maybe I misunderstand you, what issue are you seeing an what is expected?

**Comment by spqr1** [comment]
works now.

if anybody else runs into this

**solution:**

Clear cache on site and browser
