### ISSUE TITLE
Live search plugin should upgrade like searching on youtube

### ISSUE THREAD

**Issue by xemtube** [YouPHPTube/YouPHPTube#1758]
Live search plugin should upgrade like searching on youtube. Should produce an approximate result if the person who recorded the video's name is incorrect.
The first photo does not work when I write Vietnamese without accents

![2](https://user-images.githubusercontent.com/50126312/58296671-d0d07b80-7dfe-11e9-814c-d19199d974d7.png)

When I write correctly, it will work.
![1](https://user-images.githubusercontent.com/50126312/58296796-6966fb80-7dff-11e9-892e-04d6f93349cf.png)

It is great to edit it so it works like YouTube
![3](https://user-images.githubusercontent.com/50126312/58296858-ae8b2d80-7dff-11e9-9e72-d06778dc62c1.png)

**Comment by DanielnetoDotCom** [comment]
Thanks for your post, I just sent an update to make the search accent insensitive.

also I update your website, please try now

**Comment by xemtube** [comment]
Great, it worked better. Thank you very much !
