### ISSUE TITLE
Video Thumnails Plugin

### ISSUE THREAD

**Issue by JDucommun** [YouPHPTube/YouPHPTube#1760]
Video Thumbnails doesn't work, hasn't worked since I got it.

![Screenshot_3](https://user-images.githubusercontent.com/5632064/58339730-3c731280-7e18-11e9-9f58-8af21b41e64e.jpg)

**Comment by JDucommun** [comment]
Bump.

**Comment by DanielnetoDotCom** [comment]
Please check your encoder and streamer log file, should be some clue there.

for now, just delete the log files and try to access the video again.
also, make sure you have the latest encoder and streamer

**Comment by JDucommun** [comment]
Where are the log files I need to look at?

**Comment by JDucommun** [comment]
[27-May-2019 04:53:58 UTC] PHP Warning:  Invalid argument supplied for foreach() in /home/yourfamn/public_html/tube/plugin/VideoTags/VideoTags.php on line 38
[27-May-2019 04:56:28 UTC] PHP Warning:  Invalid argument supplied for foreach() in /home/yourfamn/public_html/tube/plugin/VideoTags/VideoTags.php on line 38
[27-May-2019 04:56:43 UTC] PHP Warning:  Invalid argument supplied for foreach() in /home/yourfamn/public_html/tube/plugin/VideoTags/VideoTags.php on line 38
[27-May-2019 04:56:46 UTC] Resize JPG /home/yourfamn/public_html/tube/videos/_YPTuniqid_5ceb6dfb7fcfb0.34607168.jpg, /home/yourfamn/public_html/tube/videos/_YPTuniqid_5ceb6dfb7fcfb0.34607168_thumbsV2.jpg
[27-May-2019 04:56:49 UTC] Resize Small JPG /home/yourfamn/public_html/tube/videos/_YPTuniqid_5ceb6dfb7fcfb0.34607168.jpg, /home/yourfamn/public_html/tube/videos/_YPTuniqid_5ceb6dfb7fcfb0.34607168_thumbsSmallV2.jpg

**Comment by DanielnetoDotCom** [comment]
You need to provide us a more complete log.

also as I mention above **delete the log files and try to access the video again**.
also, make sure you have the latest encoder and streamer

**Comment by JDucommun** [comment]
Its all up to date.

This might be a clue - I did delete the logs, they havent made any new logs as of this moment.

![Screenshot_1](https://user-images.githubusercontent.com/5632064/58572801-622e5c00-820a-11e9-885b-32a76f07b5dd.jpg)

**Comment by JDucommun** [comment]
These commands DO not work on a CPanel server in bash.

Are there alternates?

sudo apt-get install python-pip

sudo pip install youtube-dl

To upgrade youtube-dl to the latest version:

sudo pip install --upgrade youtube-dl

**Comment by DanielnetoDotCom** [comment]
Your pasted log was incomplete, try to grab the full log file, also you have a problem on the youtube-dl

and sorry we support Ubuntu only. we do not support CPanel/Centos

**Comment by JDucommun** [comment]
Its Centos server.

**Comment by JDucommun** [comment]
CENTOS 7.6 virtuozzo

**Comment by DanielnetoDotCom** [comment]
As I mentioned above we do not support centos installation.

**Comment by DanielnetoDotCom** [comment]
You will need to google an alternative way to install the latest youtube-dl
Is possible to make it work, we just do not support.

**Comment by JDucommun** [comment]
I just tried an embed and an encode, its not generating any new log files in either video directory of encoder or streamer.

**Comment by DanielnetoDotCom** [comment]
check the directory permissions, it should generate.

also try to replace your encoder with the public encoder https://encoder.youphptube.com/

just to check if will all works fine

**Comment by JDucommun** [comment]
Using your encoder works "better" other than not displaying the jpegs on site.

![Screenshot_2](https://user-images.githubusercontent.com/5632064/58574435-f6e68900-820d-11e9-949d-374d2720fb8c.jpg)

**Comment by JDucommun** [comment]
I used this btw,  doing some tests now.

https://www.tecmint.com/install-youtube-dl-command-line-video-download-tool/

**Comment by JDucommun** [comment]
Is there location to imput a specific path to youtube-dl in the scripts?

**Comment by DanielnetoDotCom** [comment]
sorry, we do not have that option

**Comment by JDucommun** [comment]
Ok so what path does the youtube-dl use in the scripts?

**Comment by JDucommun** [comment]
Because it installs here /usr/local/bin/youtube-dl

**Comment by DanielnetoDotCom** [comment]
I guess youtube-dl is a global script, works from anywhere

**Comment by JDucommun** [comment]
Ok, I've basically given up trying to use my own encoder.  So, lets move on, your public encoder works fine, but when I import a link or a file while the perview shows up fine in the "My Videos" section , on the live site it does not, looks like this ...

![58574435-f6e68900-820d-11e9-949d-374d2720fb8c](https://user-images.githubusercontent.com/5632064/58606267-c4b64500-8268-11e9-8071-1bbe9c347ad0.jpg)

Not sure what to do/check to fix this?

**Comment by DanielnetoDotCom** [comment]
what is that video source?

how are you submitting them?

**Comment by JDucommun** [comment]
Embed YouTube link.

**Comment by DanielnetoDotCom** [comment]
as long as it works on demo site, check your streamer log

**Comment by JDucommun** [comment]
Would this be a clue?
[29-May-2019 20:01:40 UTC] PHP Warning:  exec() has been disabled for security reasons in /home/yourfamn/public_html/tube/objects/functions.php on line 985

**Comment by DanielnetoDotCom** [comment]
Yes, it is a clue, looks like you are using a shared server what is NOT recommended .

That is why Encoder and other features are not working.

This is very common on a CPanel installation. that is one of the reasons we do not support it.

**Comment by JDucommun** [comment]
shell_exec has been enabled and no change.  Thanks for the help irregardless.

I'm over it.

Moving on.  

[PlayTube](https://codecanyon.net/item/playtube-the-ultimate-php-video-sharing-platform/20759294) - does everything I needed YouPHPTube to do and has built in ffmpeg encoder, and installs in 10 minutes.

Chiao.

**Comment by JDucommun** [comment]
Well, that wasn't very Christian of you.  LOL
