### ISSUE TITLE
PURCHASE

### ISSUE THREAD

**Issue by bigdread** [YouPHPTube/YouPHPTube#1768]
i just purcahse your Mobile + Web
Full Installation on your server + VPS Server + All Plugins + Android + iOS Version from your website,  via paypal whats next... please help i just payed $846.84

**Comment by DanielnetoDotCom** [comment]
I am sending you an info email now.

thanks

**Comment by DanielnetoDotCom** [comment]
Please check your email 

youb******sed@yahoo.*m
--

**Comment by bigdread** [comment]
ok thank you
    On Friday, May 24, 2019, 9:21:43 PM EDT, YouPHPTube <notifications@github.com> wrote:  
 
 
Please check your email

youb******sed@yahoo.*m

**Comment by DanielnetoDotCom** [comment]
Hi, 

When you can please answer my other emails so we can proceed. thanks

**Comment by bigdread** [comment]
NameServer: ns1.bluehost.comNameServer: ns2.bluehost.com
truutube.com    Yellow-Tape09    On Saturday, May 25, 2019, 6:06:41 AM EDT, YouPHPTube <notifications@github.com> wrote:  
 
 
Hi,

When you can please answer my other emails so we can proceed. thanks

**Comment by DanielnetoDotCom** [comment]
Hi

For security reasons let's keep this conversation on email ok?

So we do not share details server here

**Comment by DanielnetoDotCom** [comment]
Please send an email to developer@youphptube.com

**Comment by bigdread** [comment]
ok
    On Saturday, May 25, 2019, 11:17:59 AM EDT, YouPHPTube <notifications@github.com> wrote:  
 
 
Please send an email to developer@youphptube.com
