### ISSUE TITLE
Encoder Mysql error?

### ISSUE THREAD

**Issue by BartManX** [YouPHPTube/YouPHPTube#1770]
Was working fine ... Encoder error on pageload: SELECT f.*, e.* FROM encoder_queue e LEFT JOIN formats f ON f.id = formats_id WHERE (status = 'encoding' OR status = 'downloading' OR status = 'queue' OR status = 'error') ORDER BY priority ASC, e.id ASC \nError : ()

http://video.bartswebsolutions.com/encoder/

**Comment by spqr1** [comment]
log at your logs

http://video.bartswebsolutions.com/encoder/videos/

**Comment by BartManX** [comment]
hey i fixed it ... reformated vps and decided not to use youphptube  ... no errors now ... thanks for all the help!
