### ISSUE TITLE
Verification email always being sent even when sendVerificationMailAutomaic is disabled

### ISSUE THREAD

**Issue by chipowski** [YouPHPTube/YouPHPTube#1771]
Hi.
I've installed the CustomUser plugin to change user settings and have set sendVerificationMailAutomaic to off but on registering a new user a verification email is still sent out. I've set the options to the same in the user panel and the sign in/up panel. Are there settings that override sendVerificationMailAutomaic that would cause this to happen?

**Comment by chipowski** [comment]
Hi. Can anyone help with this? I don't want a verification email to be sent out automatically when a user signs up.

**Comment by DanielnetoDotCom** [comment]
Not sure what plugin is sending this email.

can you please paste the text of the email here, then we can search on the code where this coming from?

**Comment by chipowski** [comment]
Cool thanks. 
This is the full text:

"Hi merlin

Just a quick note to say a big welcome and an even bigger thank you for registering.

Cheers, FullKelv Team.

You are just one click away from starting your journey with FullKelv!

All you need to do is to verify your e-mail by clicking the link below

Verify"

I ran a quick search for the key text from that and found it in these 3 files:

./objects/user.php
./locale/il.php
./locale/de.php

In user.php it is part of the function "sendVerificationLink" but I don't know how the plugins interact with that function. Hope that helps.

**Comment by DanielnetoDotCom** [comment]
Do you have this option checked on CustomizeAdvanced plugin? **unverifiedEmailsCanNOTLogin**

**Comment by chipowski** [comment]
Hi.
Yes I do have that checked.

I've done that because I want to handle verification manually.

**Comment by DanielnetoDotCom** [comment]
If you have it checked it will always send the email.

that is how the code is done now, to be able to do what you want it will require some code change.

**Comment by chipowski** [comment]
ah ok thanks for letting me know.
i'll try and figure out a workaround.

thanks for your help.
