### ISSUE TITLE
loading error, Slow, Sluggish, non responsive 

### ISSUE THREAD

**Issue by CorpCaleCloud** [YouPHPTube/YouPHPTube#1772]
since updating the OS the system so not work, site not working correctly, its slow to respond even when trying to load from local server not externally. its utterly useless now

![tube error](https://user-images.githubusercontent.com/25417743/58616975-e3432d00-82b6-11e9-95b2-3d6b3afc0c96.PNG)

this is what i now see, crazy any ideas

**Comment by DanielnetoDotCom** [comment]
try to delete your cache directory 

If does not work
check the HTML source code just for a clue.

also check your error log.

**Comment by spqr1** [comment]
it looks like your css and image paths are broken... 

Are your paths in /videos/configuration.php still valid?

**Comment by spqr1** [comment]
I literally just ran into this by adding SSL to the mix.

As I suspected, you need to make corresponding changes in the /videos/configuration.php file to match with SSL as I suspected.

Mine DID look like yours at first after I added  SSL but after making a few changes in the config file to match SSL... seems to be working so far for me.

**Comment by CorpCaleCloud** [comment]
resolved. it was internal issues as i update my domain/dns/ etc and didnt relefect those changes on the server so DNS so slow to find and respond. 
After updating the NIC config and restarting the server issues resolves
