### ISSUE TITLE
The Demo site has errors

### ISSUE THREAD

**Issue by spqr1** [YouPHPTube/YouPHPTube#1773]
I loaded the YouPHPTube Demo site and noticed some pretty major errors in console:

`cast_framework.js:60 [Deprecation] document.registerElement is deprecated and will be removed in M73, around **March 2019.** Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.`

`VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead`

` VIDEOJS: ERROR: videojs-contrib-ads has not seen a loadstart event 5 seconds after being initialized, but a source is present. This indicates that videojs-contrib-ads was initialized too late. It must be initialized immediately after video.js in the same tick. As a result, some ads will not play and some media events will be incorrect. For more information, see http://videojs.github.io/videojs-contrib-ads/integrator/getting-started.html`

Is there a plan in place to help correct some of these findings or?

**Comment by spqr1** [comment]
![image](https://user-images.githubusercontent.com/50933643/58694570-24cfe880-8348-11e9-8f95-490c62dd466c.png)

**Comment by DanielnetoDotCom** [comment]
All Javascript warnings and errors above are expected

and the video works here 

![image](https://user-images.githubusercontent.com/18009293/58703577-7f386b80-837f-11e9-9e67-cdaaf3db82d7.png)

**Comment by DanielnetoDotCom** [comment]
All Javascript warnings and errors above are expected

and the video works here 

![Uploading image.png…]()
