### ISSUE TITLE
CentOS 7 installation is it possible?

### ISSUE THREAD

**Issue by CorpCaleCloud** [YouPHPTube/YouPHPTube#1779]
I have a new web server which is uses centos 7 and vesta.  I have a new for which i want to use for youphptube e.g. zxytube.co.uk and it's managed through vesta on the new server which runnuning on CentOS7 however my question is can i install youphptube on CentOS 7 which is my new web servers OS? it has Apaches, PHP, etc and this will make adding lets encrypt for SSL much easier.

i just need to know if i can be done as i want a single point of management for all my websites

**Comment by DanielnetoDotCom** [comment]
It is possible, but we do not support it.

I have installed a couple of them but the installation is a bit different.

**Comment by CorpCaleCloud** [comment]
I manged to get it work how do i change the DB password or where do i change the Database password

**Comment by CorpCaleCloud** [comment]
once this is done i can close the issue

**Comment by CorpCaleCloud** [comment]
close got to work however issues with DB i'll open a new issues
