### ISSUE TITLE
How do i change / specify the Database password in the configuration file?

### ISSUE THREAD

**Issue by CorpCaleCloud** [YouPHPTube/YouPHPTube#1782]
I have moved the server on to CentOS7 and MariaDB and need to amend the DB password in the config file. where is the config file located. I had help from another Linux engineer whom is on holiday so cannot help. This is all i need to get it working as its using a another DB admin account with a different password so need to amend to give it its own DB admin credentials

![DB error php](https://user-images.githubusercontent.com/25417743/59016458-29f5d180-8839-11e9-8f26-8f05882a2c08.PNG)
.

**Comment by DanielnetoDotCom** [comment]
hi, the configuration is inside your videos directory

videos/configuration.php

**Comment by CorpCaleCloud** [comment]
Worked perfectly booooom nuff love

**Comment by DanielnetoDotCom** [comment]
Great !
