### ISSUE TITLE
How  im install this  script  from ziro ? 

### ISSUE THREAD

**Issue by siphax** [YouPHPTube/YouPHPTube#1783]
hola  . 
how  i can install  the  scripte  ?

**Comment by DanielnetoDotCom** [comment]
This may help you https://github.com/YouPHPTube/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-YouPHPTube-version-4.x-or-newer

**Comment by polfejs** [comment]
Not able to install sscript. 

Sorry!
Connect Error (2002) php_network_getaddresses: getaddrinfo failed: Name or service not known

**Comment by DanielnetoDotCom** [comment]
I do not think this error is related to the script, it is related to your server installation.

please google for this error, and you may find a solution.
