### ISSUE TITLE
How can I add a external plugin?

### ISSUE THREAD

**Issue by Ganofins** [YouPHPTube/YouPHPTube#1785]

**Comment by DanielnetoDotCom** [comment]
What do you mean external plugin?

If you are talking about our plugins, please check it: https://github.com/YouPHPTube/YouPHPTube/wiki/How-To-Install-a-new-Plugin

**Comment by Ganofins** [comment]
Ok
Sorry I am new to this. So can I also add my WordPress plugins to it?

**Comment by DanielnetoDotCom** [comment]
No, you can not use Wordpress plugins outside a wordpress installation

**Comment by Ganofins** [comment]
Ok thanks
