### ISSUE TITLE
Feature Request:  Custom Channels

### ISSUE THREAD

**Issue by everyonecodesnoonequits** [YouPHPTube/YouPHPTube#1786]
Are there any plans to create organizational channels?  The channel seems to be tied to the user ID.  

Wondering the developers can add a channel for groups that are created?  Create a group, set the channel, add the user IDs to the group so they are allowed to modify the channel.

**Comment by DanielnetoDotCom** [comment]
Hi

That is a great Idea, but we do not have plans for that right now.
