### ISSUE TITLE
My Live Streaming did not work

### ISSUE THREAD

**Issue by xemtube** [YouPHPTube/YouPHPTube#1787]
My Live Streaming did not work. Before that it was still working normally, but now it is not connected. I try to download the link https://xemtube.online:444/stat, the report cannot access the website this. Did something happen to my website. Please help me check for help.

**Comment by DanielnetoDotCom** [comment]
Hi

Looks like for some reason your Nginx stops

try to run this command

`/usr/local/nginx/sbin/nginx`

**Comment by xemtube** [comment]
I actually ran the command / usr / local / nginx / sbin / nginx. But it seems to indicate an error and still does not work. Thanks for your help.
![1](https://user-images.githubusercontent.com/50126312/59148328-b36ff400-8a31-11e9-96f0-20d0b7b4e5d4.png)

**Comment by DanielnetoDotCom** [comment]
Ok, looks like your nginx is working, so you have your ports blocked, probably a firewall 

check what ports you will need here https://github.com/YouPHPTube/YouPHPTube/wiki/YouPHPTube-hadware-requirements#what-ports-do-i-need-to-open

**Comment by DanielnetoDotCom** [comment]
Your nginx server was stopped, next time try to run this command on your SSH terminal

 `/usr/local/nginx/sbin/nginx`
