### ISSUE TITLE
Bug: My Videos shows ALL users videos

### ISSUE THREAD

**Issue by republicus** [YouPHPTube/YouPHPTube#1789]
I would consider this a bug even if it may be a feature request.
Admins see ALL user videos under "My Videos".... Since it is labeled **MY** Videos it should only show video's that belong to that user.  The name is false.

The location admins should be able to administer other user videos already exists under **Admin > Content > Videos** 

It's my request that the "My Videos" be true to its name and be simplified to show only current user videos.

**Comment by DanielnetoDotCom** [comment]
I see, it may be improved in the future.

it is a good observation.
