### ISSUE TITLE
Bug: duplicate "Only Paid Users Can Watch" on video edit

### ISSUE THREAD

**Issue by republicus** [YouPHPTube/YouPHPTube#1790]
When editing a video there are two entries for "Only Paid Users Can Watch" and where only one responds to changes/adjustments.

![dual-paid-watch](https://user-images.githubusercontent.com/47370709/59155280-b085fb00-8a53-11e9-8290-ec4f61c92e21.PNG)

**Comment by DanielnetoDotCom** [comment]
Thanks for notice that.

I am sending a fix now
