### ISSUE TITLE
LiteSpeed

### ISSUE THREAD

**Issue by LIONHAERT** [YouPHPTube/YouPHPTube#1793]
What solved the problem LiteSpeed hosting manager did not respond to solve the problem

![22222222222](https://user-images.githubusercontent.com/45375562/59306730-9e030000-8ca5-11e9-890e-fa117c173bf6.png)

**Comment by DanielnetoDotCom** [comment]
This is what is recommended, but is not mandatory.

all tests we made was on Apache

**Comment by LIONHAERT** [comment]
The script does not work Centos I have hosting

**Comment by LIONHAERT** [comment]
The script does not work Centos I have hosting

**Comment by republicus** [comment]
@LIONHAERT It definately will work on CentOS. I just installed it onto two CentOS systems tonight. I will be writing up some instructions and sharing it on their install docs.

**Comment by DanielnetoDotCom** [comment]
@republicus that will be wonderfull.
