### ISSUE TITLE
Importing Videos With Only Non-Latin Characters in the Title

### ISSUE THREAD

**Issue by Jyt6Sham1** [YouPHPTube/YouPHPTube#1796]
If the title has at least one Latin letter in it, the video gets imported just fine, except that the non-Latin letters disappear, but if it does not have any Latin letters, there is no way to import it. Is there a way to work around it by prompting the user to specify a new title?

Thank you for the wonderful software!

**Comment by DanielnetoDotCom** [comment]
I just tried locally and even if the file has all characteres latin it works fine.

can you try it on demo site?

what video are you trying to submit?

**Comment by Jyt6Sham1** [comment]
The problem is the opposite: if there are *no* Latin letters, it doesn't work. (After more testing, I found out that numbers and punctuation are fine too.)

For example, I tried this video with only Chinese in the title (寶貴十架): https://youtube.com/watch?v=tglTyo85OtY

**Comment by Jyt6Sham1** [comment]
Same problem on the demo site:
![screenshot20190618](https://user-images.githubusercontent.com/51840075/59685342-8af4b080-920e-11e9-8e32-e4e0a1e1c054.jpg)

**Comment by DanielnetoDotCom** [comment]
I just sent a fix, please update your files

**Comment by Jyt6Sham1** [comment]
Thank you so much! It works now!

**Comment by linuxbabe** [comment]
I can upload non-latin videos to YouPHPTube just fine, but if I try to import Chinese titled videos from local folders on the server, YouPHPTube will translate the title. Then the title just become gibberish and the videos can't be imported. 

![Selection_002](https://user-images.githubusercontent.com/15121670/62898584-6dfcd980-bd88-11e9-81a8-68b679b7c45f.png)
