### ISSUE TITLE
Video filtering function does not work

### ISSUE THREAD

**Issue by xemtube** [YouPHPTube/YouPHPTube#1797]
![loi](https://user-images.githubusercontent.com/50126312/59564092-a32cca00-906c-11e9-9eb5-56c887d2d93c.png)
The video filtering function does not work or when it is not, Please check this feature to help me. I attach an image of the error function to make it easier to visualize the test.

**Comment by DanielnetoDotCom** [comment]
Thanks for notice it. 

I just sent some fix and improvements.

To update your files try this https://github.com/YouPHPTube/YouPHPTube/wiki/How-to-Update-your-YouPHPTube
