### ISSUE TITLE
Videos are being saved to both Backblaze AND my local server

### ISSUE THREAD

**Issue by soapstreams** [YouPHPTube/YouPHPTube#1800]
I purchased the B2_Backblaze plugin. When I encode a video, 3 are saved to my backblaze account (low, SD, HD), but all three are also being saved in my ../videos/ directory. I can't have them stored locally, too. I will run out of space too quickly. That is why I purchased the backblaze plugin. Any idea what I need to do to fix this? Thanks.

Soapstreams

**Comment by DanielnetoDotCom** [comment]
Hi, it not suppose to save the video on your local disk.

B2 saves only a dummy file with 10b file size

please confirm the local video file size. it is not a real video, it is just a dummy file.

**Comment by soapstreams** [comment]
Confirmed. Thanks. Closing this one out.
