### ISSUE TITLE
More Questions . . .

### ISSUE THREAD

**Issue by soapstreams** [YouPHPTube/YouPHPTube#1806]
1) Any plans for a plugin to turn site into Roku channel? Is that even possible? 

2) I am hosting old (cancelled) soap opera episodes on my site, soappirat.es. The episodes, however, are out of order. Is there a way to order them by original air date? I have next video set up for each one, but that doesn't seem to do it.

**Comment by DanielnetoDotCom** [comment]
1. Sure, in the future, it is not on the schedule yet, but we will build it.

2. try to use a playlist feature. to do so, enable the playlist plugin. on the playlists, you can sort the episodes.

**Comment by soapstreams** [comment]
Ok. 

Are you available to do custom work? Maybe I could pay you to bump the Roku plugin up your todo list? Do you know of anyone else available for such work? Thanks.

**Comment by DanielnetoDotCom** [comment]
@soapstreams for custom work, please email me at developer@youphptube.com
