### ISSUE TITLE
MySQL Server Adress

### ISSUE THREAD

**Issue by spacejohannes** [YouPHPTube/YouPHPTube#1815]
I just installed YouPHP and noticed that you have to replace the default "localhost" variable to "127.0.0.1" for a MySQL server, in order to complete the Installation. Otherwise, an unknown error shows up.

**Comment by DanielnetoDotCom** [comment]
Sorry I dont understand what do you mean.

**Comment by lunar54** [comment]
Not able to install with root user or created user because you should never use root user using localhost or 127.0.0.1. even when changing mysql bind from 127.0.0.1 to 0.0.0.0 Keep getting Sorry! Unkown Error!

**Comment by DanielnetoDotCom** [comment]
I am lost here, I have never got such error

**Comment by spacejohannes** [comment]
> Sorry I dont understand what do you mean.

To make this clear:
I was installing YouPHPTube on a fresh server and couldn't submit the setup because "Unkown Error".
I figured out that you have to replace the "localhost" placeholder in the MySQL Setup From to "172.0.0.1" in ordert to submit the setup and let everything install.

**Comment by DanielnetoDotCom** [comment]
I see, understood now.
