### ISSUE TITLE
LiveLinks function with .u3m8 link cannot view videos emitted from mobile phones

### ISSUE THREAD

**Issue by xemtube** [YouPHPTube/YouPHPTube#1819]
Why do I use the LiveLinks function with the link .u3m8 on the web https://xemtube.online, the video is only viewable on desktop or laptop. If using a mobile phone to watch, it is impossible to load the video to watch. I tried 4 phones and used wifi or 3G, all of the above situations happened. is not ?

**Comment by DanielnetoDotCom** [comment]
can you please give me a LiveLink example?

**Comment by xemtube** [comment]
https://xemtube.online/plugin/LiveLinks/view/Live.php?link=13

**Comment by DanielnetoDotCom** [comment]
this link is not working for me

I got this 

`Access to XMLHttpRequest at 'https://ul.cdn946.net:8443/hls/5trobz6.m3u8?s=lnvSx-jz3nXhQDwFDpTxyA&e=1561611386' from origin 'https://xemtube.online' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

means you are not allowed to use this link

**Comment by xemtube** [comment]
But on the desktop browser, stop watching normally. I send you desktop screenshots that are watching live links.

![1](https://user-images.githubusercontent.com/50126312/60223180-63ef4c00-98aa-11e9-9862-7e27a2cb48f0.png)

**Comment by DanielnetoDotCom** [comment]
It does not work here, maybe is something on your PC that authorizes it to work, try in another PC. it may fail
