### ISSUE TITLE
Page not loading properly 

### ISSUE THREAD

**Issue by akhilleusuggo** [YouPHPTube/YouPHPTube#1821]
Hello , after a successful installation , the site does not load properly . Here is a screenshot of the page .

![image](https://user-images.githubusercontent.com/52116577/60301922-6abda380-992a-11e9-84cf-5623b922f189.png)

**Comment by DanielnetoDotCom** [comment]
what do you have in your HTML source code?

how is your path to the images and css?

also check your configuration.php file

**Comment by akhilleusuggo** [comment]
> what do you have in your HTML source code?
> 
> how is your path to the images and css?
> 
> also check your configuration.php file

Hello , thanks for the reply. This is happening to me already 5 installation in arrow . ( the encoder it's working fine , and I'm running on SSL )

-Sr , you haven't gave me enough information to answer you about the question you're asking me . About the HTML source code , please check my site tube.akhilleusuggo.com
-Patch to the images and css ( please tell me where is that )
-Configuration.php  ( I'm replacing sensible information with ''xxxx" )

`<?php
$global['configurationVersion'] = 2;
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) { 
    // get the subdirectory, if exists
    $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
    $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
    $global['webSiteRootURL'] = 'https://tube.akhilleusuggo.com/';
}
$global['systemRootPath'] = '/var/www/tube.akhilleusuggo.com/web/';
$global['salt'] = 'xxxx';
$global['enableDDOSprotection'] = 1;
$global['ddosMaxConnections'] = 40;
$global['ddosSecondTimeout'] = 5;
$global['strictDDOSprotection'] = 0;

$mysqlHost = 'localhost';
$mysqlPort = '3306';
$mysqlUser = 'xxxx';
$mysqlPass = 'xxxx';
$mysqlDatabase = 'xxxx';

/**
 * Do NOT change from here
 */

require_once $global['systemRootPath'].'objects/include_config.php';

Thanks for the help and your time Sr
`

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom ok , I have found a solution ( but still not working well ) . The problem comes from the ''type'' of PHP from the panel . Could you tell me which one is the most optimal for the script of YouPHPTube ?
![image](https://user-images.githubusercontent.com/52116577/60393253-3d2f5080-9b0a-11e9-9b13-72d096c5c7a1.png)

I was using Fast-CGI , and on the first comment you can see how the site was looking like . With CGI looks normal ; but some options are missing .

**Comment by akhilleusuggo** [comment]
Another problem found 
![image](https://user-images.githubusercontent.com/52116577/60396910-2b1bd500-9b3f-11e9-960b-ea355d5181ff.png)

The video got downloaded from youtube , encoded , than deleted automatically or not sent to the /video location....

And when I go to admin area I can not click any of the option ...

**Comment by republicus** [comment]
1) I think your PHP mode should be set to Apache (Mod-PHP)

2) Check your logs at videos/youphptube.log
Are you using your own encoder?
Try encoding a short 1-2 minute video and look at your logs on both streamer and encoder (if youre using your own).

3) I assume you are talking about not being able to expand these options:
![adminpanel](https://user-images.githubusercontent.com/47370709/60400954-f57be980-9b48-11e9-9dd8-92a5617bc4fe.PNG)

I noticed the same problem before upgrading to PHP 7+
I presume you are running PHP version 5.6 or less.

I am curious if you can confirm this as it is either a bug or the installer should require php 7+ and not be satisfied with PHP 5.6 as it currently is.

**Comment by akhilleusuggo** [comment]
@republicus Hello man , thank you for the answer . Regardless to the PHP version , I'm using 7.2 version . The expansion option now it's ok ( I really don't know what thing fixed it ) , but now not even the video start downloading . Before it start downloading , and encoding , now not even downloading . Anyway to debug this ?
Yes I'm using my own encoding . I'm trying google cloud with 8 cores 16gb ram , so I don't think I'm having a resources problem . On the PHP.ini I've gave memory_limit= 2048M , and I the videos that I have uploaded are not more than 200-300mb . 

![image](https://user-images.githubusercontent.com/52116577/60401117-b5326080-9b74-11e9-9799-756c4ee6e02e.png)

Thanks for any help tip
