### ISSUE TITLE
Erro ao subir vídeo (Encoder e Streamer).

### ISSUE THREAD

**Issue by jadirj** [YouPHPTube/YouPHPTube#1822]
Olá.

Estou com o seguinte problema em minha instalação. Ao tentar subir uma gravação do próprio YouPHPTube (flv ~2,3 GB), através da opção Bulk Encode, somente as versões SD (mp4 ~800MB) e LOW (mp4 ~400MB) vão para o streamer. A versão em HD (mp4 ~1,3 GB) não vai para a pasta vídeo do streamer. Porém ela foi gerada na pasta vídeo do Encoder.
![Capturar1](https://user-images.githubusercontent.com/52298160/60300991-a8103a00-9906-11e9-91e0-cff655a558ae.PNG)

Quando tento subir o mesmo arquivo (flv ~2,3 GB), pela opção From File do Encoder, também aparece um pop-up de erro com a seguinte mensagem: Array ( [upl] => Array ( [name] => 24_tmpFile.flv [type] => [tmp_name] => [error] => 7 [size] => 0 ) )
![Capturar](https://user-images.githubusercontent.com/52298160/60300677-de00ee80-9905-11e9-8048-4a5e04785cef.PNG)

Ao tentar o mesmo arquivo pela opção Direct upload do streamer, o vídeo fica sempre com o Status: Encoding em Meus vídeos:
![Capturar2](https://user-images.githubusercontent.com/52298160/60300887-62ec0800-9906-11e9-9313-b0f7552d9086.PNG)

As configurações, tanto do streamer quanto do encoder estão para 4,88GB:
![Capturar3](https://user-images.githubusercontent.com/52298160/60301107-ea397b80-9906-11e9-9f1c-a520fde49e7c.PNG)

Nos arquivos de logs, aparentemente não há erro algum. Somente percebi a falta da linha de transferência do arquivo em HD no log do streamer (trecho logado: youPHPTubeEncoder.json: receiving video upload to...)

A máquina virtual está configurada com 6GB de RAM que, pela orientação, é suficiente para um vídeo de 2GB.

O streamer e o encoder estão na mesma máquina sobre o mesmo apache. Porém, tenho outra intalação, em máquinas distintas, e o comportamento permanece.

Tentei fazer o upload somente com a opção em HD ativada e o mesmo aconteceu. Só que dessa vez, nenhum vídeo foi para a pasta video do streamer.

Já conferi os arquivos de logs, inclusive do apache, e não achei nada que possa estar ocasionando esse comportamento.

Segue os logs do Encoder e do Streamer:

[logEncoder.txt](https://github.com/YouPHPTube/YouPHPTube/files/3336666/logEncoder.txt)
[logStreamer.txt](https://github.com/YouPHPTube/YouPHPTube/files/3336667/logStreamer.txt)

Outros arquivos, de tamanhos menores, funcionam normalmente. A plataforma será usada em um ambiente corporativo onde normalmente teremos gravações das transmissões que serão arquivos com tamanhos consideráveis.

Parabéns pela ótima ferramenta e trabalho.

Desde já agradeço o apoio.

**Comment by DanielnetoDotCom** [comment]
O erro 7 significa que o PHP nao pode escrever o arquivo no disco.

Array ( [upl] => Array ( [name] => 24_tmpFile.flv [type] => [tmp_name] => **[error] => 7** [size] => 0 ) )

`UPLOAD_ERR_CANT_WRITE Value: 7; Failed to write file to disk. Introduced in PHP 5.1.0.`

aparentemente a transferencia foi OK, mas não foi possivel escrever. provavelmente alguma limitação em seu sistema de arquivos

**Comment by jadirj** [comment]
Obrigado pela rápida resposta Daniel.

Sim, realmente era uma limitação/configuração em nosso ambiente.

O problema era na pasta /tmp, que é utilizada pelo PHP no processo de upload. Ela não tinha espaço suficiente para a operação.

Configuramos outra pasta temporária, parâmetro upload_tmp_dir no php.ini, para ser utilizada pelo PHP. Dessa maneira, esse problema deixou de existir.

**Comment by DanielnetoDotCom** [comment]
Fico feliz que tenha solucionado
