### ISSUE TITLE
Enabling a Playlist plugin causes Uncaught Error: Using $this when not in object context

### ISSUE THREAD

**Issue by ICWiz** [YouPHPTube/YouPHPTube#1823]
I have a Fresh install of YouPHPtube.  After uploading videos and looking around.  I activated the Hotkeys plugin. This worked with no problems. Then I activated the Playlist plugin. When I refreshed the main page, i got a 500 error

youphptube.log showed this

PHP Fatal error:  Uncaught Error: Using $this when not in object context in /var/www/html/YouPHPTube/plugin/YouPHPTubePlugin.php:34
Stack trace:
#0 /var/www/html/YouPHPTube/routes.php(8): YouPHPTubePlugin::addRoutes()
#1 /var/www/html/YouPHPTube/index.php(131): include('/var/www/html/Y...')
#2 {main}
  thrown in /var/www/html/YouPHPTube/plugin/YouPHPTubePlugin.php on line 34

`In this block of code code for YouPHPTubePlugin.php: 

    public static function addRoutes() {
        $plugins = Plugin::getAllEnabled();
        foreach ($plugins as $value) {
            self::YPTstart();
            $p = static::loadPlugin($value['dirName']);
            if (is_object($p)) {
                //$this->start();
                $p->addRoutes();
                self::YPTend("{$value['dirName']}::".__FUNCTION__);
            }
        }
        return false;
`

I searched for a reason for $this. Its not supposed to be in a static ruction. I also searched for start() in the included files but i couldn't find it.   So i ended up commenting it out.

This seemed to work, and the Playlist plugin works too. 

Just wanted to report to see if anyone knows a better solution.

--ICWiz

**Comment by DanielnetoDotCom** [comment]
Thank you, it will be fixed
