### ISSUE TITLE
Check the uniqueness of the email user site

### ISSUE THREAD

**Issue by itdoka** [YouPHPTube/YouPHPTube#1826]
Hi! Need to check the uniqueness of the email address of users. One user = one email address. Make sure you exclude multiple registrations with the same email address.

**Comment by DanielnetoDotCom** [comment]
Hi

try to check this

![image](https://user-images.githubusercontent.com/18009293/60391110-b8b6e080-9abd-11e9-85f3-50051af754e3.png)
