### ISSUE TITLE
Wallet history

### ISSUE THREAD

**Issue by chinobaingo** [YouPHPTube/YouPHPTube#1830]
Hello

When I have blockonomics and wallet enabled.

Any user can see history for of all transactions for all users. This is not good.

Right now ANY user can click “history” and see all transactions for all users including $ amount. 

It should only show history for current logged in user. Unless admin right?

**Comment by DanielnetoDotCom** [comment]
I guess only admins can see all transactions

Users can only see the transactions that he is transferring o receiving balance

**Comment by chinobaingo** [comment]
Well when I create a new user with no admin rights and then click history in the wallet menu I can see all transactions for all users. Multiple pages.

**Comment by chinobaingo** [comment]
Is there any way to simply disable the history?

I’ve tried multiple users and it’s all the same everybody can all see transaction history this is really bad for privacy.

**Comment by DanielnetoDotCom** [comment]
I see, that means, users that has not any transaction is seen all transactions correct?

If is that I should send a fix

**Comment by chinobaingo** [comment]
Correct! :):):):)

Users who have no transactions can still see all transactions of everybody else.

**Comment by DanielnetoDotCom** [comment]
I am sending a fix, can you please update and confirm if it is fixed?

**Comment by chinobaingo** [comment]
no noticeable change.

New users are still able to see entire transaction history for entire site

**Comment by DanielnetoDotCom** [comment]
Sorry, I sent a new fix. try again

**Comment by chinobaingo** [comment]
WHOO hoo!

Fixed!

Please close ticket 

YOU
ARE
THE
BEST!

**Comment by DanielnetoDotCom** [comment]
Thanks for the feedback :)
