### ISSUE TITLE
 Turn off the file saving function on service when live streaming

### ISSUE THREAD

**Issue by xemtube** [YouPHPTube/YouPHPTube#1831]
Currently when I live streaming, all live videos are saved in the service with the .flv format, which leads to the server memory being full. Can I turn off the not-save function when live? Thanks for guiding me to turn off this function. Sorry because my english is not good. Thank you !

**Comment by DanielnetoDotCom** [comment]
hi

Sorry for the delayed answer.

For now, you will need to edit the conf file

`sudo nano /usr/local/nginx/conf/nginx.conf`

and then add those lines on your file

Comment the line **record all;**

It will look like this

```
recorder video{
    #record all;
    record_path /tmp;
    record_notify on;
    record_max_size 2048M; 
    #will produce files of the form yourUserKey-24-Apr-13-18:23:38.flv
    record_suffix -%d-%b-%y-%T.flv;
}
```
