### ISSUE TITLE
Changing Logo Link

### ISSUE THREAD

**Issue by KoShawlu** [YouPHPTube/YouPHPTube#1832]
Hi,
How can I change logo link for my sites. As for me, I change document root to /var/www/html/YouPHPTube . So I can call my site only my IP. And I create dns record for my site. Then, I change my logo. But when I click on my logo, it goes to 192.168.1.4/YouPHPTube. It is not working because of changing document root. So I would like to change logo link. Please help me.

**Comment by akhilleusuggo** [comment]
Why don't you change change logo from the panel ?

**Comment by KoShawlu** [comment]
Yah, I can change logo. But I would like to change logo link. When I click
on logo, the default link is 192.168.0.4/YouPHPTube. I want to change that
link.

**Comment by DanielnetoDotCom** [comment]
Hi, 

Please check this 

![image](https://user-images.githubusercontent.com/18009293/60724988-5111f280-9f0e-11e9-908a-2b63c7320572.png)

**Comment by KoShawlu** [comment]
Ok sir. I got it. Thank you so much.
