### ISSUE TITLE
Comments Not Posting From App

### ISSUE THREAD

**Issue by KenRHill** [YouPHPTube/YouPHPTube#1833]
Greetings Daniel,

I just want to report that comments are not posting to videos when trying to leave the comments from the mobile apps.  

Specifically what I mean is... If I am logged into the mobile app and I am watching a video and if I decide I want to leave a comment on that video, and I press on the comment button in the app and then I type out a comment and press the Submit Comment button,  the comment shows up in the app for a few seconds, until I press the back button to go back and watch the video again.  When I do this, the comment is gone.  

It is almost as if I never had left a comment at all.  I even tried double checking to see if the comments were posting by logging in on a computer and checking the actual website to see if my comments are being posted on the videos pages from the mobile app, and they are not.

**Comment by DanielnetoDotCom** [comment]
I just sent a fix for this.

But you will need to update your mobile app and your streamer.

I will send the iOS app soon

**Comment by KenRHill** [comment]
Greetings @DanielnetoDotCom 

Comments are still not posting from the Android mobile app.  Please advise.

**Comment by DanielnetoDotCom** [comment]
did you update your mobile and streamer app?

can you confirm that if you use our public app and the demo site?

**Comment by KenRHill** [comment]
Greetings @DanielnetoDotCom 

I just finished updating my streamer site using git pull.  As far as updating the mobile apps, you have always been the one that has provided any updating to our mobile apps for both Android and iOS platforms.  Can you update our mobile app to the latest version since you have credentials on both our Google Play & Apple App Store?  Please and thank you.  I can email you if you prefer.

**Comment by DanielnetoDotCom** [comment]
Hi

Looks like your whitelabel needs an update.

please email developer@youphptube.com for this.
