### ISSUE TITLE
Disable Subscription, Comments, Thumbs Up and Down, and Sign Up

### ISSUE THREAD

**Issue by angelawong** [YouPHPTube/YouPHPTube#1834]
I am having trouble locating where I need to go to do the following:

1. Disable subscription (remove Subscribe button)
2. Disable people from commenting
3. Disable ability to rate (thumbs up and down)
4. Disable people from signing up (remove Sign Up button)

Any help would be most appreciated. Thank you.

Version 7.2

Thanks,
Angela

**Comment by akhilleusuggo** [comment]
On admin functions . I'm sure about this for :
Disable people from commenting
Disable people from signing up 

The others I have to take a look

**Comment by angelawong** [comment]
Thanks akhilleusuggo. Items (2) and (4) are resolved. (1) and (3) have yet to be resolved. I can't seem to find any plugin options that would disable them. Thanks.

**Comment by akhilleusuggo** [comment]
@angelawong I took a look , and all of them are on the plugin CustomizeAdvanced (CustomizeAdvanced) and CustomizeUser (CustomizeUser) ;take a deep look .

**Comment by DanielnetoDotCom** [comment]
I am sending an update that adds options 1 and 3 on advanced custom

**Comment by angelawong** [comment]
Thanks so much, Daniel. You are awesome! I was using CSS to hide those buttons. Thanks so much for updating the CustomizedAdvance. Cheers! :-)
