### ISSUE TITLE
Password check new hash pass does not match, trying MD5

### ISSUE THREAD

**Issue by akhilleusuggo** [YouPHPTube/YouPHPTube#1837]
[06-Jul-2019 10:09:48 Europe/Helsinki] user::login: noPass = , encodedPass = 1, this->user, admin xx.xx.xx.xx
[06-Jul-2019 10:09:48 Europe/Helsinki] encryptPasswordVerify: do not encrypt
[06-Jul-2019 10:09:48 Europe/Helsinki] Password check new hash pass does not match, trying MD5
[06-Jul-2019 10:09:48 Europe/Helsinki] Password check Old encoded pass
[06-Jul-2019 10:09:48 Europe/Helsinki] Password check Old not found
[06-Jul-2019 10:09:48 Europe/Helsinki] ReceiveImage: Permission denied to receive a file: Array
(
    [duration] =&gt; 0:03:40
    [videos_id] =&gt; 
    [user] =&gt; admin
    [password] =&gt; c93cf27fc1eaa828087b4f8011033e9e
    [redirectUri] =&gt; 
)

I'm trying to fix this error already 1 week , I don't understand where the error is coming from . All the files I encode get deleted and I can't log into my site properly . Everytime I have to close the browser/clear the cache to proceed . On Plugins I have the cache disabled

**Comment by DanielnetoDotCom** [comment]
Hi, where are you clicking to generate this?

anyway, you can try to reset your password to generate the proper hash 

https://github.com/YouPHPTube/YouPHPTube/wiki/Reset-a-Password

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Hello man. I'm not clicking anywhere . I checked the logs when I saw that all my videos are getting denied after ending the encoder queue . The videos are from Youtube

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I need to mention something as well . Since I have multiple VPSs ( 4 ) I have set network encoder . All the external Encoders works perfectly , only the local Encoder gives this error ( I'm talking about the encoder built on the same installation ) .
I didn't lost my password , I'm able to login and logout without any problem . It's just the system it self not recognizing the password for some reason .

One last problem ( not a big one ) but the server don't show the ping error: Searching Ping ...

**Comment by DanielnetoDotCom** [comment]
I am also not sure what is happening.

can you confirm if that is your user pass hash? c93cf27fc1eaa828087b4f8011033e9e

About the ping, your servers probably do not respond ping.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Is not . By the way , I just saw that on the DB it creates a new user , with the username admin , with a new password . I have deleted it , few seconds later , recreated . Is that the user admin that use the encoder ?

**Comment by DanielnetoDotCom** [comment]
encoder, will always use the streamer user.

the hash must be the same.

can you disable your streamer cache and see if it is working?

**Comment by akhilleusuggo** [comment]
already disabled , cause I got tired of it . I mean , you should add an option : NoCacheAdmin
It get stuck every time on admin pages , or just shows the wrong options 
About the Ping ; It doesn't even shows the ping of the encoder built into the same streaming server //
