### ISSUE TITLE
notification plugin not working

### ISSUE THREAD

**Issue by gujarraju** [YouPHPTube/YouPHPTube#1839]
Hi Daniel,
Today i buy notification plugin successfully installed but if i upload any video or comment i didn't received any email.

**Comment by DanielnetoDotCom** [comment]
Hi, do you have your email properly configured?

Please check here: https://github.com/YouPHPTube/YouPHPTube/wiki/Setting-up-YouPHPTube-to-send-emails

If the error persist, please check your log file

**Comment by gujarraju** [comment]
Yes i have configured email working fine but notification plugin not working.

**Comment by DanielnetoDotCom** [comment]
there are any errors on the log file?

remember, only subscribers receive emails.

**Comment by gujarraju** [comment]
only direct upload video notification getting
embed video notification not working

**Comment by DanielnetoDotCom** [comment]
I see, I just sent a fix, can you please update your streamer files and try again?

**Comment by gujarraju** [comment]
yes working fine..
Thanks

**Comment by DanielnetoDotCom** [comment]
That is great
