### ISSUE TITLE
Multiple Users Can Use The Same Email

### ISSUE THREAD

**Issue by akhilleusuggo** [YouPHPTube/YouPHPTube#1842]
I've been testing this , and I saw that I was able to create as many accounts as I wanted with the same email . This will conduct to an big issue when resetting the password or notification thu email.

**Comment by DanielnetoDotCom** [comment]
the notification sends only one notification per email.

even multiple users have the same email.

if you want to make sure the email is unique, please check this https://github.com/YouPHPTube/YouPHPTube/issues/1826
