### ISSUE TITLE
Error with encoder relating to ffmpeg

### ISSUE THREAD

**Issue by sipero** [YouPHPTube/YouPHPTube#1847]
My encoder was working but now I am seeing this error. How do I fix this

ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Unrecognized option 'max_muxing_queue_size'.
Error splitting the argument list: Option not found

**Comment by akhilleusuggo** [comment]
I think this error is related to videos x265 , I'm not sure . But make sure you're uploading files that matches the extension allowed by your config . Try uploading an MP4 x264 from youtube , then take a look if the problem persists.

**Comment by DanielnetoDotCom** [comment]
@sipero , update your FFMPEG to ver. 4.x+

do this ...

`sudo add-apt-repository ppa:jonathonf/ffmpeg-4 && sudo apt-get update -y && sudo apt-get install  ffmpeg`

and enjoy it!

**Comment by sipero** [comment]
I needed to add this package first software-properties-common What I did notice that the instructions for the encoder only includes this is the command line but not in the combined installer for for both YouPHPTube and YouPHPTube-Encoder
