### ISSUE TITLE
What file do I need to edit

### ISSUE THREAD

**Issue by sipero** [YouPHPTube/YouPHPTube#1848]
I was looking through some of the old posts and found one that related to editing the video resolutions created.

Can someone tell me which file I need to edit please. This was the changes someone else made but they did not say the file they edited. I check a few but was not able to find this.

MP4 Low: ffmpeg -i {$pathFileName} -vf scale=1280:720 -movflags faststart -preset ultrafast -vcodec h264 -acodec aac -strict -2 -y {$destinationFile}

MP4 SD: ffmpeg -i {$pathFileName} -vf scale=1920:1080 -movflags faststart -preset ultrafast -vcodec h264 -acodec aac -strict -2 -y {$destinationFile}

**Comment by akhilleusuggo** [comment]
There's 2 ways to edit it. 
From the encoder , on the configuration option
or you can change it from the DB of the encoder, witch is the same basically .

**Comment by sipero** [comment]
Thanks, what do you mean the configuration option?

I can see the information in the mysql database

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/60930111-0e546f80-a2ac-11e9-8044-8d1871839500.png)

**Comment by sipero** [comment]
I do not see that page on my encoder I only have the sharing queue and the queue log and then the Share videos on the right. What is the url to see those configuration options

**Comment by sipero** [comment]
![image](https://user-images.githubusercontent.com/14201860/60966750-da5f6580-a310-11e9-9d7d-247c20b89e74.png)

Mine does not have the 3 options marked in this image

**Comment by DanielnetoDotCom** [comment]
Please check those 

https://github.com/YouPHPTube/YouPHPTube-Encoder/issues/145

https://github.com/YouPHPTube/YouPHPTube-Encoder/issues/124

**Comment by akhilleusuggo** [comment]
@sipero You need to set the user as admin. This has been made to not allow normal users/uploaders to edit the settings of ffmpeg
Make sure that on your DB the value of the user you're using ( by default it's ''admin'' got the value "1" and not "0"

**Comment by sipero** [comment]
I had to install phpmyadmin but after that it is OK I think my suggestion would be it creates two users when the software is installed. One with be the default without admin access and the 2nd one with admin access that way phpmyadmin or command line changes to the database would not be required

**Comment by akhilleusuggo** [comment]
Ofc , that's what all does . The admin account are for admin tasks . The uploader can can be a normal user if you wish
