### ISSUE TITLE
video not uploading

### ISSUE THREAD

**Issue by sambhuva** [YouPHPTube/YouPHPTube#1849]
![image](https://user-images.githubusercontent.com/3104324/60950806-7be8b600-a315-11e9-833e-b91495b37329.png)

**Comment by sambhuva** [comment]
[10-Jul-2019 13:24:03 Asia/Calcutta] Trying again: [1] => Execute code error "Array\n(\n)\n" 
 Code: ffmpeg -i /var/www/html/1Rivetsight-Encoder/videos/8_tmpFile.mp4 -vf scale=-2:360 -movflags faststart -preset ultrafast -vcodec h264 -acodec aac -strict -2 -max_muxing_queue_size 1024 -y /var/www/html/1Rivetsight-Encoder/videos/8_tmpFile_converted_Low.mp4

**Comment by DanielnetoDotCom** [comment]
I guess you are using an old FFMPEG version.

try to execute your code 

`ffmpeg -i /var/www/html/1Rivetsight-Encoder/videos/8_tmpFile.mp4 -vf scale=-2:360 -movflags faststart -preset ultrafast -vcodec h264 -acodec aac -strict -2 -max_muxing_queue_size 1024 -y /var/www/html/1Rivetsight-Encoder/videos/8_tmpFile_converted_Low.mp4`

if you get the error `Unrecognized option 'max_muxing_queue_size'.`

Update your FFMPEG to ver. 4.x+

do this ...

`sudo add-apt-repository ppa:jonathonf/ffmpeg-4 && sudo apt-get update -y && sudo apt-get install  ffmpeg`

and enjoy it!

**Comment by sambhuva** [comment]
yes, it is working fine. Thank you.
