### ISSUE TITLE
Site doesn't refresh 

### ISSUE THREAD

**Issue by akhilleusuggo** [YouPHPTube/YouPHPTube#1851]
Site don't refresh , don't go further to any location . Clicking everywhere , site just loading loop

[11-Jul-2019 13:45:34 Europe/Helsinki] user::login: noPass = , encodedPass = 1, this->user, admin xxx.xxx.xxx.xx
[11-Jul-2019 13:45:34 Europe/Helsinki] encryptPasswordVerify: do not encrypt
[11-Jul-2019 13:45:34 Europe/Helsinki] user::login: Do login without cookie
[11-Jul-2019 13:45:34 Europe/Helsinki] user::recreateLoginFromCookie: do cookie-login: admin   result: 0
[11-Jul-2019 13:45:34 Europe/Helsinki] success 1

**Comment by DanielnetoDotCom** [comment]
where is it?

check the error.log, also the javascript console for errors

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom What do you mean with JavaScript console ?
The logs you see on my first comment are from the video/youphptube.log

**Comment by DanielnetoDotCom** [comment]
ctrl+shift+i on your browser window

usually, you get a screen like that

![image](https://user-images.githubusercontent.com/18009293/61053777-94fc7000-a3c4-11e9-9978-9938693e70c7.png)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Yes , you mean the inspect , I got you :
![image](https://user-images.githubusercontent.com/52116577/61057144-98a3ed00-a3ec-11e9-9249-54515c34e833.png)

**Comment by akhilleusuggo** [comment]
ok , I have disabled the ads plugin . but I had this problem even before I activated this ads system . How to clear the cache manually ? Deleting all what inside the cache directory ?

**Comment by DanielnetoDotCom** [comment]
I mean console, inspect you will verify the HTML and the CSS code.

I can see an error on the videojs-overlay above, I am not sure where does it come from.

but you can clear your cache here 

![image](https://user-images.githubusercontent.com/18009293/61057709-376c2180-a3cc-11e9-8e61-a2cdfbf93a47.png)

you may also want to disable the cache plugin to find the error.

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/61057771-e0774400-a3ed-11e9-985f-f0b61a824987.png)

I can't get to that directory , the site just don't load . I need to open it on a new browser , it works ; but when I log into the admin account , just pressing enter to login it's doesn't load .

**Comment by DanielnetoDotCom** [comment]
try to delete the cache deliting the ...YouPHPTube/videos/cache

this directory will be auto recreated

if you need to reset your plugins use MySQL to truncate your plugins table


the code 403 on your ads means the company , probably google, reject you.

you should remove this code. I am not sure where did you put.

check if you have ad plugins enabled

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Thank you for your time Sr !
