### ISSUE TITLE
Live stream not being encoded as HLS

### ISSUE THREAD

**Issue by sipero** [YouPHPTube/YouPHPTube#1854]
Hi,

I am using the HLS plugin together with the plugin that sends live streams to the encoder.

This works fine if I upload a video to the encoder it creates the .m3u8 file as I would expect but not with live streams as you can see the format is MP4
![image](https://user-images.githubusercontent.com/14201860/61123066-4968c580-a49b-11e9-884c-5807e7c84ed6.png)

**Comment by DanielnetoDotCom** [comment]
I am reviewing it.

**Comment by DanielnetoDotCom** [comment]
I just sent an update, can you please update your streamer and try again?

**Comment by sipero** [comment]
Thanks, It seems to be working now

**Comment by DanielnetoDotCom** [comment]
Great !
