### ISSUE TITLE
Questionis

### ISSUE THREAD

**Issue by soapstreams** [YouPHPTube/YouPHPTube#1855]
I use the subscription plugin to charge for access to videos. I need all uploaded videos to automatically belong to the "Subscribers" group. Is that possible? Or do I have to manually add each one?

Can I change the name "Categories" to something more relevant to my site like "Show" instead?

The Playlist maker is in bad shape. Assigning a number to it does NOT result in it being placed in that sequence. Further dragging and dropping is clumsy and difficult to navigate. Is there a way to make playlist creation more user-friendly, or at least more like YouTube?

**Comment by DanielnetoDotCom** [comment]
Hi

> I use the subscription plugin to charge for access to videos. I need all uploaded videos to automatically belong to the "Subscribers" group. Is that possible? Or do I have to manually add each one?

You need to manually add them. we are already working in something to auto add new videos in a usergroup

> Can I change the name "Categories" to something more relevant to my site like "Show" instead?

Try this: 

![image](https://user-images.githubusercontent.com/18009293/61172057-eab45200-a555-11e9-857b-029770faee1b.png)


> The Playlist maker is in bad shape. Assigning a number to it does NOT result in it being placed in that sequence. Further dragging and dropping is clumsy and difficult to navigate. Is there a way to make playlist creation more user-friendly, or at least more like YouTube?

I guess you need to change and then press enter or click on the confirm button on the right of the box.
it is working here

But anyway, can you please screenshot the playlist from youtube, so we can have an idea what do you mean?

**Comment by soapstreams** [comment]
Glad to know auto-add to user groups is in the hopper.

I knew there was a way to change labels. Thanks for reminding me where to find it.

I will create a short screencast/video of how the playlist behaves.

**Comment by DanielnetoDotCom** [comment]
Sorry I just realize we already have the option to auto add videos on user group on the PredefinedCategory plugin

![image](https://user-images.githubusercontent.com/18009293/61234660-07918680-a70a-11e9-91d7-4f6b3bd465c4.png)
