### ISSUE TITLE
Not admin accounts stucked 

### ISSUE THREAD

**Issue by akhilleusuggo** [YouPHPTube/YouPHPTube#1860]
@DanielnetoDotCom Hello .

[13-Jul-2019 13:43:06 Europe/Helsinki] Start Login Request
[13-Jul-2019 13:43:06 Europe/Helsinki] redirectUri: 
[13-Jul-2019 13:43:06 Europe/Helsinki] sane redirectUri: https://tube.akhilleusuggo.com/
[13-Jul-2019 13:43:06 Europe/Helsinki] Start Login Request
[13-Jul-2019 13:43:06 Europe/Helsinki] redirectUri: 
[13-Jul-2019 13:43:06 Europe/Helsinki] sane redirectUri: https://tube.akhilleusuggo.com/
[13-Jul-2019 13:43:06 Europe/Helsinki] user::login: noPass = 1, encodedPass = , this->user, xxxxx@xxxx.com xxx.xxx.xxx.xxx
[13-Jul-2019 13:43:06 Europe/Helsinki] user::login: Do login without cookie
[13-Jul-2019 13:43:18 Europe/Helsinki] Start Login Request
[13-Jul-2019 13:43:18 Europe/Helsinki] redirectUri: 
[13-Jul-2019 13:43:18 Europe/Helsinki] sane redirectUri: https://tube.akhilleusuggo.com/

Do you see any error here ? I'm really not able to log in only with admins accounts . Normal user can log normally

**Comment by DanielnetoDotCom** [comment]
I can not see any error

try to recover the password https://github.com/YouPHPTube/YouPHPTube/wiki/Reset-a-Password

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I did it at the least 5 times ... From the SSH

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Look , just changed right now , this is what happens
![image](https://user-images.githubusercontent.com/52116577/61176276-dd2eb480-a5b5-11e9-8cf0-1e92361f0c4f.png)
When I F5 , just the site doesn't load . Need to open incognit page , loads normal , but again , type and stuck

**Comment by DanielnetoDotCom** [comment]
Can you please update your site with the latest code?

also check for php and javascript errors.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Trying to update it with command . Error 
`fatal: not a git repository (or any of the parent directories): .git`  ( just to let you know , on the installation I have downloaded the master file and updated it with FTP )
On my server files I can see : .github and .gitignore

Where to check the PHP and Javascripts errors ?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom on .gitignore :

```
/nbproject/private/
/videos/
/nbproject/
/plugin/LiveOnlineUsers/
/plugin/LiveUsers/
/plugin/VideoResolutionSwitcher/
/plugin/AudioTrackSwitcher/
/plugin/Customize/
/plugin/VideoThumbnails/
/plugin/MP4ThumbsAndGif/
/plugin/MP4ThumbsAndGifLocal/
/plugin/PayPalToWatch/
/plugin/predefinedCategory/
/plugin/SecureVideosDirectory/
/plugin/PointsSystem/
/plugin/GoogleAds_IMA/
/plugin/LoginLDAP/
/plugin/SendRecordedToEncoder/
/plugin/SupportAuthor/
/plugin/CountryRedirect/
/plugin/SubtitleSwitcher/
/plugin/AWS_S3/
/plugin/SignUpAgreement/
/plugin/PromoteVideos/
/plugin/Livesearch/
/plugin/AudioVisualizer/
/plugin/Notifications/
/plugin/DIY/
/plugin/AutoShare/
/plugin/LiveCountdownEvent/
/plugin/ReturnToLastPosition/
/plugin/SecondWatch/
/plugin/Tecorio/
/plugin/AD_Server_Promote_Videos/
/plugin/Blackblaze_B2/
/plugin/VideoDocuments/
/plugin/VideoSpeed/
/plugin/FTPAutoImport/
/plugin/IPDirectConnect/
/plugin/Bookmark/
/plugin/Subscription/
/plugin/LifeStreamLayout/
/plugin/Backup/
/plugin/FTP_Storage/
/plugin/SecondLife/
/plugin/YouPHPTV/
/plugin/CreateUserManager/
/plugin/ImportFromOtherVideoPlatform/
/plugin/PayPerView/
/plugin/VideoHLS/
/plugin/Chat2/
/plugin/User_Controll/
/plugin/FlixHouse/
/plugin/Video_Location_Block/
```

**Comment by akhilleusuggo** [comment]
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=<remote>/<branch> master

**Comment by akhilleusuggo** [comment]
If I do the manual upload via FTP , Am I going to lose all parameters and videos ?

**Comment by DanielnetoDotCom** [comment]
Hi

yes, you did thru FTP, we highly recommend you to use git clone to get the latest files, is a lot faster and easier to update.

I asked you to update your files, because you may be missing something.

can you make a git clone on your terminal?

You should make the command on the terminal inside your apache directory.

`cd /var/www/html && sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube.git`

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom The problem is that the github downloads it on this way, /htmp/YouPHPTube/Public_html , and I want it to be on /html/public_html ... Anyway to do it on this way ?

**Comment by DanielnetoDotCom** [comment]
2 ways ...

1. Use apache virtual hosts (recommended)

To find how to configure it you will need to google.

2. Rename the directory.

- go to the html directory `cd /var/www/html` or whatever it is
- make the git clone command
- you will have a directory called YouPHPTube
- rename the directory to the public_html `mv YouPHPTube public_html`

**Comment by akhilleusuggo** [comment]
I've got your idea ( the second one sound easy with the full permission to change name directories
