### ISSUE TITLE
Smarty (?) tag compatibility

### ISSUE THREAD

**Issue by soapstreams** [YouPHPTube/YouPHPTube#1864]
Do I have to manually change the copyright year I placed at the bottom or does the footer take "smarty" tags or something similar to automate that copyright message?

**Comment by d0773d** [comment]
There is a plugin available to do just that.

**Comment by soapstreams** [comment]
I use the custom plugin. Does it accept special tags?

**Comment by soapstreams** [comment]
I use the custom plugin. Does it accept special tags?

**Comment by DanielnetoDotCom** [comment]
Sorry, the customize plugin only takes html tags.
