### ISSUE TITLE
Can't get email to work

### ISSUE THREAD

**Issue by soapstreams** [YouPHPTube/YouPHPTube#1865]
I can't seem to get email to work. I am using gmail, but I get an error: "Your message could not be sent! Message could not be sent SMTP connect() failed." How do I get this to work?

**Comment by DanielnetoDotCom** [comment]
Did you follow this? https://github.com/YouPHPTube/YouPHPTube/wiki/Setting-up-YouPHPTube-to-send-emails

If very important for you to Allow less secure apps to access your Gmail account

To make Gmail allow you to use your account as an SMTP server, disable this security feature:

1. Sign in to Gmail
1. Click [here](https://myaccount.google.com/u/3/lesssecureapps) to access Less Secure App Access in My Account.
1. Next to “Allow less secure apps: OFF,” select the toggle switch to turn ON.

**Comment by soapstreams** [comment]
Yes, I read your instructions and followed them, but I still can't seem to get it to work. I have to have email working before I can go live. Any other thoughts?

Please know that I am always willing to compensate you for your time when/if you help get my site working. I know you do offer paid services. Let me know if there is a way you can look at my email settings on my tube site and how much it would cost for you to fix this. Thanks.

**Comment by sipero** [comment]
Using gmail is probably not a good option as frequently it fails but addionally they only allow you to send 99 emails per day with this method. I would suggest you get a free account with mailgun. I can help you configure this is required.

**Comment by DanielnetoDotCom** [comment]
@soapstreams please contact me on the email developer@youphptube.com
