### ISSUE TITLE
Changing vid settings

### ISSUE THREAD

**Issue by soapstreams** [YouPHPTube/YouPHPTube#1867]
What can stop my subscribers from just moving the videos from the subscriber (paid access) group to the public group?

**Comment by DanielnetoDotCom** [comment]
What do you mean? only admin and video owner can do this correct?

**Comment by soapstreams** [comment]
Right. What's to stop video owner from setting their videos to public and letting users view them for free. I want only subscribers to be able view video content. Is there a way to keep videos in the subscriber user group?

**Comment by DanielnetoDotCom** [comment]
I see, for now I do not have this option to hide the visibility from users.
