### ISSUE TITLE
Bulk Embed nice plugin

### ISSUE THREAD

**Issue by Andiweb87** [YouPHPTube/YouPHPTube#1869]
Hi Daniel just test the last great plugin you have added in the demo site but after i use the embed option the video show this  No compatible source was found for this media. Maybe is still demo i think ? 

thank you great plugin :)

**Comment by DanielnetoDotCom** [comment]
The plugin still in beta, I did not find any problem related to this.

I just send an update to filter non-embeddable videos.

Not all videos on youtube are allowed to be embeddable

can you please update your files and try again?

**Comment by Andiweb87** [comment]
understand, just tested in my site and is ok, another thing is the thumbnail of the video show in the main , see the diference ? thank you again for this work

https://snag.gy/N74Mkx.jpg

**Comment by DanielnetoDotCom** [comment]
Sorry, I dont understand what do you mean.

the thumbs are the same as youtube provide.

**Comment by Andiweb87** [comment]
there are not show full like the arrow red , can you see the  diference between ?

**Comment by DanielnetoDotCom** [comment]
We use as the default image, the image youtube provide to us. 

it probably provides an image with the black border.

**Comment by Andiweb87** [comment]
Please can you fix the search button because is not working, i can't click the button

**Comment by DanielnetoDotCom** [comment]
this should be trigged by pressing enter. If is not returning anything check your javascript console for errors

**Comment by Andiweb87** [comment]
with enter works
