### ISSUE TITLE
 automatically delete .ts files on live users

### ISSUE THREAD

**Issue by xemtube** [YouPHPTube/YouPHPTube#1870]
Currently the u3m8 link files are saved a lot on live stream accounts. It is taking up a lot of service memory. There is something that will be automatically deleted after the live is done. Thanks for your help and support. Thanks!

**Comment by DanielnetoDotCom** [comment]
Please edit your conf file 

`sudo nano /usr/local/nginx/conf/nginx.conf`

comment the line 

`# hls_cleanup off;`

and restart your nginx
```

 sudo /usr/local/nginx/sbin/nginx -s stop

 sudo /usr/local/nginx/sbin/nginx 

```

**Comment by xemtube** [comment]
![1](https://user-images.githubusercontent.com/50126312/61219904-66252780-a73f-11e9-8105-2c17e381f7ff.png)
Please give me a detailed guide to help me with milk. I send the current snapshot of my nginx.conf. Thank you !

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/61220587-00a84b00-a6ed-11e9-8452-1e538f829462.png)

remove or put a hashtag before this command: `hls_cleanup off;` 

save and restart your nginx
```

 sudo /usr/local/nginx/sbin/nginx -s stop

 sudo /usr/local/nginx/sbin/nginx 
```

**Comment by xemtube** [comment]
It worked well. Thanks very much !
