### ISSUE TITLE
Only images without sound in live streaming video.

### ISSUE THREAD

**Issue by xemtube** [YouPHPTube/YouPHPTube#1875]
I am currently using the tool for live stream, but live videos only play images without the accompanying sound. My source link is still full of audio and images. Is there any other way to fix this? The link that is playing directly has no sound 
https://xemtube.online/plugin/Live/?c=NEXTSPORTS

I send the image of my streaming stream parameters.

![1](https://user-images.githubusercontent.com/50126312/61304182-f2544f00-a812-11e9-9ea8-66b697295918.png)

**Comment by DanielnetoDotCom** [comment]
can you try to play it on VLC?

grab the play link here 
![image](https://user-images.githubusercontent.com/18009293/61314836-e1d0b400-a7d3-11e9-8899-1e669fd3f6f9.png)


I guess the problem is not on the player. 

maybe is a misconfiguration on your RTMP publisher
