### ISSUE TITLE
user background image  showing on gallery page

### ISSUE THREAD

**Issue by k7n2g** [YouPHPTube/YouPHPTube#1877]
https://www.screencast.com/t/TdoRUiqiWt

Hi how and where do i stop this image from user background showing on page when video is selected please

**Comment by DanielnetoDotCom** [comment]
what image? the flag?

check this

![image](https://user-images.githubusercontent.com/18009293/61393711-efe80880-a897-11e9-80a4-c28bc2ec9f1c.png)

**Comment by k7n2g** [comment]
Thank you guys changed  sorry not an issue just didnt know where else to post for info
