### ISSUE TITLE
 Error not automatically obtained  video titles and images when embedding videos from Youtube

### ISSUE THREAD

**Issue by xemtube** [YouPHPTube/YouPHPTube#1879]
Now when I embed all the videos on YouTube, it is not automatically getting the title and image of the video. This error has just happened, it used to work normally. I tried demo.youphptube.com, the same error occurred as above. Is there any way to make it work normally like before. Thank you !

![2](https://user-images.githubusercontent.com/50126312/61424274-2a57b100-a93d-11e9-89c7-d95fc15b670a.png)

**Comment by DanielnetoDotCom** [comment]
Hi

the old embed feature still there, the bulk embed is a new feature, different than the old one.

Can you please describe what steps did you make to get this error?

we can try to fix it.

**Comment by xemtube** [comment]
I am using the old video embedding feature. Embed each video 1 on Youtube.

Right now it is working normally again. I don't know what happened before. The error appears even on demo.youphptube.com web.

**Comment by DanielnetoDotCom** [comment]
But is the error on the old embed or on the new embed?
