### ISSUE TITLE
twitter share button not working probably due to their new theme 

### ISSUE THREAD

**Issue by joey2354** [YouPHPTube/YouPHPTube#1881]
Hi, the twitter share button just opens twitter page without sharing, i think it's their new theme :/

![7MSIiou](https://user-images.githubusercontent.com/25159595/61458195-d3b09e00-a961-11e9-9472-e83c1aef4dcf.png)

**Comment by DanielnetoDotCom** [comment]
Not sure, but I guess that is why https://marketingland.com/twitter-loses-ability-to-let-users-auto-post-tweets-retweets-to-facebook-245398

If that is true I will need to remove the button

**Comment by joey2354** [comment]
no this link you gave is from 2018, and it's just about facebook, we can't autoshare to facebook profile as rss anymore but we can twitter, don't remove the button as this has nothing to do with me wanting to share to twitter as i auto post to twitter now with no problem ... thank you

**Comment by joey2354** [comment]
hi danielson

i think this has something to do with twitter login to new twitter theme, sometimes i still see old theme, when i press share from phptube it says error on twitter sometimes, then sometimes it asks to login, but still can't share ........ 90% of time i can share using twitter share button from other sites if this helps.

hope this helps

**Comment by mj1985** [comment]
Fixed it:
in /view/include/social.php
replace the Twitter line with:
`$twitterURL = "http://twitter.com/intent/tweet?text={$title}+{$url}";`

**Comment by DanielnetoDotCom** [comment]
Wow, thanks, I will approve this PR.
