### ISSUE TITLE
 How to have a Bulk Embed button appear but in the picture

### ISSUE THREAD

**Issue by xemtube** [YouPHPTube/YouPHPTube#1886]
How to have a Bulk Embed button appear but in the picture. I installed Bulk Embed Plugins on XemTube.Online web and turned it on but it does not appear like on the picture. Please support me. Thank you !
![demo](https://user-images.githubusercontent.com/50126312/61510786-93632580-aa1e-11e9-9ecf-587f09c7d13e.png)

**Comment by DanielnetoDotCom** [comment]
Hi, do you mean the button?

you need to update all your files

https://github.com/YouPHPTube/YouPHPTube/wiki/How-to-Update-your-YouPHPTube

**Comment by xemtube** [comment]
Tks!
