### ISSUE TITLE
 Fix some Plugins Livesearch errors

### ISSUE THREAD

**Issue by xemtube** [YouPHPTube/YouPHPTube#1890]
Livesearch plugins are not working properly and I need to fix some of the following errors:

1. How to hide the Category block in search results. Details are in the attached photo
![1](https://user-images.githubusercontent.com/50126312/61586456-adc40d00-ab9e-11e9-84fa-da64a5d4d341.png)

2. Video titles are available on the web but not in search results.
![2](https://user-images.githubusercontent.com/50126312/61586493-d4cf0e80-ab9f-11e9-83f4-22617cfa7e5b.png)

3. After completing the search keyword, you cannot press Enter to get more results.
![3](https://user-images.githubusercontent.com/50126312/61586534-1318fd80-aba1-11e9-8ac8-0740dd941a48.png)

**Comment by DanielnetoDotCom** [comment]
I think I am using a different version of your plugin because I do not have the category button anymore.

Can you please download the newest version on the plugins site?

![image](https://user-images.githubusercontent.com/18009293/61633363-4de46980-ac65-11e9-9496-bb8e945adeb8.png)

**Comment by xemtube** [comment]
Tks !
