### ISSUE TITLE
IMDB not fetching

### ISSUE THREAD

**Issue by jaynelim** [YouPHPTube/YouPHPTube#1892]
hello i am having problem with imdb not fetching the meta data. it says "processing" but nothing happens after long time. what can i do?

**Comment by DanielnetoDotCom** [comment]
Hi, check your log file for some clue.

usually, this is due to directory permission.

**Comment by jaynelim** [comment]
hello thanks for your reply. where can i find the log file?
and which directory needs permission change for imdb plugin?

**Comment by DanielnetoDotCom** [comment]
Check here https://github.com/YouPHPTube/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by jaynelim** [comment]
thanks. i was able to find the error log file and saw that i needed to make the IMDbScrape folder and contents writeable.
