### ISSUE TITLE
Are these features paid plugins only?

### ISSUE THREAD

**Issue by honeyfairy** [YouPHPTube/YouPHPTube#1895]
I want to make my site the same like your youphptube Netflix demo, with the portrait poster images. 
1. Is the preview of the movie  only available with paid plugin (shown in pic in red with number 1)
2. Is portrait poster images only available with paid plugin? (shown in pic in blue with number 2)

![youphptube plugins](https://user-images.githubusercontent.com/17691989/61832295-f7e41180-ae70-11e9-8b68-f735ef51fd4d.PNG)

**Comment by akhilleusuggo** [comment]
@honeyfairy Did you at the least tested plugin? Cause your question are telling that you didn't . 
In case you do , did you tried the plugin IMDbScrape (IMDbScrape) ?

**Comment by honeyfairy** [comment]
Yes, I tried for a long time. Mine looks like this:

![min](https://user-images.githubusercontent.com/17691989/61834329-d4709500-ae77-11e9-9e86-a512c81b096d.PNG)

**Comment by DanielnetoDotCom** [comment]
@honeyfairy 

first update your site, to make sure you have the latest configurations.

I am pasting the plugin's configurations here. it may help you.

the portrait images show only if it is available

![image](https://user-images.githubusercontent.com/18009293/61879574-af0c7700-aec9-11e9-9a3e-bbab48250b8b.png)

**Comment by honeyfairy** [comment]
Thank you!! Yes now I see that I had Landscape options on.
Beautiful! Now I will buy 2 plugins from you!

**Comment by honeyfairy** [comment]
But I still cannot get the moving preview (marked number 1 in my screenshot) 
What is this option called?

**Comment by DanielnetoDotCom** [comment]
If you mean the gif option...

![image](https://user-images.githubusercontent.com/18009293/61949044-f0f7f480-af7f-11e9-917e-c733f8a91482.png)

**Comment by honeyfairy** [comment]
Yes, I disabled animated gif (I checked the option)
Then the animated gif did not work.

Then I unchecked it again. But now it does not work too...

How do I get the animated gif to work again?

**Comment by honeyfairy** [comment]
If I change to Gallery mode or youtube mode the animated gifs work. Only it does not work anymore on the netflix style

**Comment by DanielnetoDotCom** [comment]
are you using the latest YouPHPTube version?

are you using portrait or landscape images?

**Comment by honeyfairy** [comment]
Yes, I just did a git pull last night.
I'm using portrait images.

Thank you

**Comment by DanielnetoDotCom** [comment]
Make sure you add animated gifs for your portrait images 

![image](https://user-images.githubusercontent.com/18009293/61996238-85d61d00-b068-11e9-8d97-793b7216fc91.png)

**Comment by honeyfairy** [comment]
i mean the big video play. here is a screen recording of what i mean. 
As you can see, the video (Moana) is playing 
[new.zip](https://github.com/YouPHPTube/YouPHPTube/files/3438311/new.zip)

But on mine, the video does not play in the preview, its only a static image

**Comment by DanielnetoDotCom** [comment]
I see, maybe you miss the trailer

![image](https://user-images.githubusercontent.com/18009293/61996516-6db3cd00-b06b-11e9-930f-978a8b307cc8.png)

**Comment by honeyfairy** [comment]
Yes!! Thats it. Now its working. Thank you!!
