### ISSUE TITLE
add more ressolution to encode

### ISSUE THREAD

**Issue by psujit775** [YouPHPTube/YouPHPTube#1897]
how can i add mode resolution to encode videos. 
and also i have multiple video chunks and i want to join them before start encoding in multiple resolutions basically i want to join multiple small video files and make it one big file then i want it to encode in multiple resolution.
and also i want to put logo on videos.

I know I'm asking for too much but please help me.
Thank You.

**Comment by akhilleusuggo** [comment]
Hello @psujit775 
1)About adding mode resolution to encode videos , I don't understand what do you mean . If you mean to add more resolution then the one there's already , I've already asked for it and get ignored 
2)About to join multiple files that's easy to do with minimum knowledge on FFMPEG . 
-Take all the files location 
-Create a list.txt
-Name them equally and give them value name number , like video1 , video2
-Run the command to ''join them''
You can find more detailed info here from the community : https://stackoverflow.com/questions/7333232/how-to-concatenate-two-mp4-files-using-ffmpeg

-The logo can be done on the YouPHPTube personalized logo plugin : VideoLogoOverlay (VideoLogoOverlay) OR
-You can add the logo on the encoder , so when the video is being encoded the logo will appear where you ask the encoder to put it . The mail difference is that , when you put the logo thru the plugin , will only appear when it's playing from web browser ( like from your site ) . If you put the command on the encoding process , even if they download the video from your site and play it anywhere else , the logo will be part of the video.

All your question can be googled , and really has nothing to do with the script of YouPHPTube it self 
You're welcome

**Comment by psujit775** [comment]
Thanks for your reply.
I asked to join videos through YouPHPTube-Encoder but anyway thanks.

YouPHPTube is a great tool.

**Comment by DanielnetoDotCom** [comment]
@psujit775 sorry, there is no option to join videos on YouPHPTube
