### ISSUE TITLE
Videos link to same one

### ISSUE THREAD

**Issue by hanx-phy** [YouPHPTube/YouPHPTube#1899]
I upload some video by 'Encode Video and Audio' and they are fine.
But now all of videos link to a new video embed from YouTube. I'm not sure what operating make this mistake. There are two actions i had done before I got this problem:
1. I add a new video by 'Embed a Video Link' from YouTube
2. I change all videos' category from default to any other
After that I upload another video by 'Embed a Video Link' and it's fine.

BTY, I find a video cannot play on android 9 and post the problem in [#1712 ](https://github.com/YouPHPTube/YouPHPTube/issues/1712#issuecomment-515279757). This video keep its link and didn't change to youtube one.

**Comment by akhilleusuggo** [comment]
I don't really understand you . But how did you encoded an ''Embed a Video Link'' ?
Embed a Video Link it just shows the Original source on your site , that mean the video it's actually not hosted by your site ; but Youtube .
You need to copy/past the link from Youtube to the encoder if you want to be the one hosting it .

**Comment by hanx-phy** [comment]
@akhilleusuggo thanks for reply.

I have already encoded my own video and it's okay. And I can also encode video from YouTube or just embed it. Every thing is okay.

I mean after I did some actions above(1&2), I click every video link and it jump to same video which I embed from YouTube.

**Comment by DanielnetoDotCom** [comment]
Hi, do you mean all your videos are messed up?

I have no idea what happens, can you please check the videos table on database?

**Comment by hanx-phy** [comment]
> Hi, do you mean all your videos are messed up?
Yes. All links jump to playing same video with different title and Gif which are match to the link.
> 
> I have no idea what happens, can you please check the videos table on database?
Sorry, but I think I can not do that now. 
I have deleted wrong videos and re-uploaded it. 
But before that, I checked the files in /var/www/html/YouPHPTube/videos, the videos are fine.

**Comment by hanx-phy** [comment]
Alright, I cannot reproduce this bug right now. So I will close issue. 
If it happen again in future I'll open a new issue. 
Thanks you all
