### ISSUE TITLE
UpRequestUploadRights & UpRequestLivestreamRights

### ISSUE THREAD

**Issue by akhilleusuggo** [YouPHPTube/YouPHPTube#1905]
signUpRequestUploadRights
signUpRequestLivestreamRights

This 2 option does just nothing . I do not get any notification for UpRequestUploadRights & RequestLivestreamRights .

**Comment by DanielnetoDotCom** [comment]
OMG, you are right, it was just lost on the code.

I just sent an update to remove it.

Thanks for finding it.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom You're welcome . But the idea is really good to request stream or video upload . Hope to see it on the future

**Comment by akhilleusuggo** [comment]
userMustBeLoggedIn this one I don't understand at all . User must be logged in for what ? It's under CustomizeUser (CustomizeUser)

**Comment by DanielnetoDotCom** [comment]
Yes, I guess it was an idea that was not implemented.

userMustBeLoggedIn will show a login form in all site, even to see the gallery video.

only after login, you will see the gallery.
