### ISSUE TITLE
Long videos take to long to load

### ISSUE THREAD

**Issue by akhilleusuggo** [YouPHPTube/YouPHPTube#1908]
Videos of 10-20mn does load really fast ( I'm talking about the start of the video )
Videos of 3-4h ( usually streams ) take really long to load the first time , once they're loaded ( started ) , I can go to any point on the video and does load fast . 

What does exactly cause this issue ? ( not an internet problem , I have 1gb/s ) and my server got 3gb/s

**Comment by DanielnetoDotCom** [comment]
Do you have the VideoThumbnails plugin?

it is executed at the first time you run a video.

it will send it to the encoder in the background. maybe it is overloading your server.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom No I do not have the plugin. Yes, I have watched one of the videos on your site that explains it , but it's not my case

**Comment by akhilleusuggo** [comment]
Is not only the fist time you visit the video , it's every time you open the same video . If I F5 the page , it takes to long to load the video . It's like the video player were designed to load a % of the video at the first shot

**Comment by TLCReuver** [comment]
Did you try different browsers ? I notice that Google Chrome always start directly, Firefox sometimes with 1 sec delay & Edge sometimes 3 sec delay !

**Comment by akhilleusuggo** [comment]
@TLCReuver I'm currently using google chrome , and I have tried it on opera and firefox , the same issue  
![image](https://user-images.githubusercontent.com/52116577/62010273-e34d9500-b160-11e9-8bfb-5c0983fe01e3.png)

as you can see , loading ..... takes really long , as I have said , I think it' loads a percentage of the video before it starts like 3-5% than start

**Comment by TLCReuver** [comment]
If uou upload the .mp4 with "Direct Upload" and not by the encoder (SD_HD_Low) you can use qt-faststart to change the appropriate meta-data in the mp4, also known as the moov atom or movie atom.
 
https://walterebert.com/blog/start-playing-mp4-videos-before-download-has-finished/

See attached file
[qt-faststart.zip](https://github.com/YouPHPTube/YouPHPTube/files/3439489/qt-faststart.zip)

**Comment by akhilleusuggo** [comment]
All the videos are imported from youtube , and I'm using custom encoding option , the one youtube and twitch uses to get the best quality possible . Take a look here : 
https://tube.akhilleusuggo.com/video/awaken-ft-valerie-broussard-league-of-legends-cinematic-season-2019

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo Did you customize the encoder FFMPEG commands?

I guess we have by default the `-movflags faststart` , it should speed up the video play

![image](https://user-images.githubusercontent.com/18009293/62052046-1b011f00-b1eb-11e9-933d-541b79fd684f.png)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom But what has to do the encoder with the video start playing . I think it's something that has to do with the video player not the encoder .

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo , sorry, this is not the player. Without the movflags faststart the payer may need to download a large portion of the file before being able to start play it.


Official FFMPEG documentation:
https://ffmpeg.org/ffmpeg-formats.html
-movflags faststart
    Run a second pass moving the index (moov atom) to the beginning of the file. This operation can take a while, and will not work in various situations such as fragmented output, thus it is not enabled by default.

**Comment by akhilleusuggo** [comment]
I'll give a try right now and report you with the resolt , it may take a me 30-1h since I'll encode a 7h video

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom No difference , I've tried it with the -movflags faststart and the same delay

**Comment by akhilleusuggo** [comment]
this is the one I'm using right now : ffmpeg -i {$pathFileName} -c:v libx264 -x264opts keyint=120:no-scenecut -s 1920x1080 -movflags faststart -r 60 -preset medium -b:v 4290k -profile:v main -c:a aac -sws_flags lanczos {$destinationFile}

**Comment by DanielnetoDotCom** [comment]
I am not sure. 

Try to direct access the video file (mp4 file) just to make sure it is not a player issue.

I have never watched a 7 hours (1080p)  video on the web.

maybe a solution for that is an HLS video. The HLS split the video into hundreds of small 10 seconds pieces, so the video needs only to download 10 seconds of the video file to play.

**Comment by JoshWho** [comment]
You need to add **+faststart**   You cannot forget the **+**   
This function will put the videos meta info at the front of the file so it will be streamable. 

Here is a example of one I use in my encoder:
 `ffmpeg -threads 4 -i {$pathFileName} -vf scale=-2:720 -movflags +faststart -preset veryfast -vcodec h264 -acodec aac -strict -2 -max_muxing_queue_size 1024 -y {$destinationFile}`

The **veryfast** setting will make the file size smaller without losing the quality and it is not bad on speed either.

**Comment by akhilleusuggo** [comment]
@JoshWho Hello , thank you for the reply ( it's late but it's really good info ). I know it's needed the ''+'' . I forgot to update the solution for that . This solution should be reported to @DanielnetoDotCom because by default he's not using it , that's why I had problems . After reading the documentation i found the +

**Comment by DanielnetoDotCom** [comment]
Thanks, I didnt know I was missing the +
