### ISSUE TITLE
No videos show up after encoded. 

### ISSUE THREAD

**Issue by johnp125** [YouPHPTube/YouPHPTube#1909]
I seem to have the site up and running but I cannot seem to get any videos to upload. The encoder has been downloaded and it looks like it is working but after it processes the video it shows nothing on the main site. 

This is the apache error log. 

[Sun Jul 28 01:40:57.923167 2019] [php7:warn] [pid 22221] [client 192.168.182.1:53066] PHP Warning:  require_once(/var/www/html/YouPHPTube-Encoder/view/../videos/configuration.php): failed to open stream: No such file or directory in /var/www/html/YouPHPTube-Encoder/view/index.php on line 18
[Sun Jul 28 01:40:57.923237 2019] [php7:error] [pid 22221] [client 192.168.182.1:53066] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/YouPHPTube-Encoder/view/../videos/configuration.php' (include_path='.:/usr/share/php') in /var/www/html/YouPHPTube-Encoder/view/index.php on line 18
[Sun Jul 28 01:40:57.940926 2019] [php7:warn] [pid 22221] [client 192.168.182.1:53066] PHP Warning:  mkdir(): Permission denied in /var/www/html/YouPHPTube-Encoder/objects/functions.php on line 211
[Sun Jul 28 01:45:28.797723 2019] [mpm_prefork:notice] [pid 22179] AH00169: caught SIGTERM, shutting down
[Sun Jul 28 01:45:33.290880 2019] [mpm_prefork:notice] [pid 23222] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Sun Jul 28 01:45:33.291013 2019] [core:notice] [pid 23222] AH00094: Command line: '/usr/sbin/apache2'
[Sun Jul 28 03:09:49.236118 2019] [php7:warn] [pid 23269] [client 192.168.182.1:61133] PHP Warning:  require_once(/var/www/html/YouPHPTube-Encoder/video/objects/include_config.php): failed to open stream: No such file or directory in /var/www/html/YouPHPTube-Encoder/videos/configuration.php on line 19, referer: http://192.168.182.129/YouPHPTube-Encoder/?justLogin=1
[Sun Jul 28 03:09:49.237146 2019] [php7:error] [pid 23269] [client 192.168.182.1:61133] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/YouPHPTube-Encoder/video/objects/include_config.php' (include_path='.:/usr/share/php') in /var/www/html/YouPHPTube-Encoder/videos/configuration.php on line 19, referer: http://192.168.182.129/YouPHPTube-Encoder/?justLogin=1
[Sun Jul 28 03:09:56.260921 2019] [php7:warn] [pid 25301] [client 192.168.182.1:61172] PHP Warning:  require_once(/var/www/html/YouPHPTube-Encoder/video/objects/include_config.php): failed to open stream: No such file or directory in /var/www/html/YouPHPTube-Encoder/videos/configuration.php on line 19, referer: http://192.168.182.129/YouPHPTube-master/mvideos
[Sun Jul 28 03:09:56.261053 2019] [php7:error] [pid 25301] [client 192.168.182.1:61172] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/YouPHPTube-Encoder/video/objects/include_config.php' (include_path='.:/usr/share/php') in /var/www/html/YouPHPTube-Encoder/videos/configuration.php on line 19, referer: http://192.168.182.129/YouPHPTube-master/mvideos
[Sun Jul 28 03:10:30.348489 2019] [php7:warn] [pid 27198] [client 192.168.182.1:61238] PHP Warning:  require_once(/var/www/html/YouPHPTube-Encoder/videos/objects/include_config.php): failed to open stream: No such file or directory in /var/www/html/YouPHPTube-Encoder/videos/configuration.php on line 19, referer: http://192.168.182.129/YouPHPTube-master/mvideos
[Sun Jul 28 03:10:30.348585 2019] [php7:error] [pid 27198] [client 192.168.182.1:61238] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/YouPHPTube-Encoder/videos/objects/include_config.php' (include_path='.:/usr/share/php') in /var/www/html/YouPHPTube-Encoder/videos/configuration.php on line 19, referer: http://192.168.182.129/YouPHPTube-master/mvideos
[Sun Jul 28 03:10:39.416369 2019] [php7:warn] [pid 23860] [client 192.168.182.1:61239] PHP Warning:  require_once(/var/www/html/YouPHPTube-Encoder/videos/objects/include_config.php): failed to open stream: No such file or directory in /var/www/html/YouPHPTube-Encoder/videos/configuration.php on line 19, referer: http://192.168.182.129/YouPHPTube-master/mvideos
[Sun Jul 28 03:10:39.416445 2019] [php7:error] [pid 23860] [client 192.168.182.1:61239] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/YouPHPTube-Encoder/videos/objects/include_config.php' (include_path='.:/usr/share/php') in /var/www/html/YouPHPTube-Encoder/videos/configuration.php on line 19, referer: http://192.168.182.129/YouPHPTube-master/mvideos
[Sun Jul 28 03:20:53.121793 2019] [mpm_prefork:notice] [pid 23222] AH00169: caught SIGTERM, shutting down
[Sun Jul 28 03:20:57.703052 2019] [mpm_prefork:notice] [pid 34467] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Sun Jul 28 03:20:57.703230 2019] [core:notice] [pid 34467] AH00094: Command line: '/usr/sbin/apache2'
[Sun Jul 28 03:31:52.982831 2019] [mpm_prefork:notice] [pid 34467] AH00169: caught SIGTERM, shutting down
[Sun Jul 28 03:31:57.542045 2019] [mpm_prefork:notice] [pid 37295] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Sun Jul 28 03:31:57.542152 2019] [core:notice] [pid 37295] AH00094: Command line: '/usr/sbin/apache2'

**Comment by DanielnetoDotCom** [comment]
Are you sure your encoder is OK?

I can see this error: `PHP Fatal error: require_once(): Failed opening required '/var/www/html/YouPHPTube-Encoder/videos/objects/include_config.php' `

**Comment by johnp125** [comment]
What do I need to check?

**Comment by DanielnetoDotCom** [comment]
I am not sure, looks like you did not follow the installation instructions.

at least the encoder is not propper installed

**Comment by akhilleusuggo** [comment]
I think you have misconfigured the encoder 
Also looks like not enough permission `Failed opening required..... `

**Comment by johnp125** [comment]
I would agree. The encoder may not have been installed correctly. I followed the install page requirements after the encoder was downloaded. The website directed how to install and how to setup the sql server. what is the preferred install directions for Ubuntu 18.04?

**Comment by johnp125** [comment]
Ok on the "YouPHPTube-master/admin/?page=general_settings" nothing seems to save. I changed permissions to 777 to check seems to make no difference.

**Comment by johnp125** [comment]
NGINX or Apache? The instructions talk about both. https://www.how2shout.com/how-to/install-youphptube-ubuntu-server-youtube-clone-script.html

**Comment by DanielnetoDotCom** [comment]
Hi, you can find some installation tutorials here https://tutorials.youphptube.com/

**Comment by johnp125** [comment]
Followed this to the letter for ubuntu 18.x. Took about 15min. Working fine now. https://github.com/YouPHPTube/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-YouPHPTube-version-4.x-or-newer

**Comment by DanielnetoDotCom** [comment]
I am glad to hear you made it work
