### ISSUE TITLE
How can I debug the Live Streaming ?

### ISSUE THREAD

**Issue by akhilleusuggo** [YouPHPTube/YouPHPTube#1913]
I have been trying to setup the livestreaming , but no success . I'm using apache2 for my server ( ISPConfig ) . I know you do not support any of those panels . But the configuration should be the same . Apache uses port 80 and 443 , in my case ISPConfig panel uses port 8080 , witch I can't give it to Nginx . The config that I'm using are this one : 

  ```
  worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://xxx/plugin/Live/on_publish.php;
                            on_play http://xxx/plugin/Live/on_play.php;
                            on_record_done http://xxx/plugin/Live/on_record_done.php;
                    }
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8081;
                    listen 444 ssl;
                    server_name localhost;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"      
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }
            }
    }

```

PS: The http://xxx/ is just a replacement for my url site .

**Comment by akhilleusuggo** [comment]
I have changed to the port 8088 and looks like it does work , but no video got displayed after starting to stream . The server receive data but no video plays 
![image](https://user-images.githubusercontent.com/52116577/62011045-f06f8180-b16a-11e9-9779-503eaefaeba4.png)

Stats from http://xxx:8088/stats shows that the data is being received

**Comment by lunar54** [comment]
in the live plugin are server, playerServer, stats all pointing to your nginx stream server ? and doesn't ISPConfig use nginx for the back end of the panel ? I use i-MSCP but i also use 2 separate servers

**Comment by akhilleusuggo** [comment]
@lunar54 ISPConfig does support ISPConfig Apache2 ( the one I use ) , and ISPConfig Nginx ( that I have never used ) 

Parameters of my plugin :
`{"button_title":"LIVE","server":"rtmp://xxx/live","playerServer":"https://tube.akhilleusuggo.com:444/live","stats":"https://xxx:444/stat","disableDVR":false,"disableGifThumbs":false,"useAadaptiveMode":false,"experimentalWebcam":false}`

No matter what port I use on `https://xxx:444/stat` , even if I use `https://xxx:8088stat` still working , but need F5 everytime to get real time stats 
I'm confused

**Comment by lunar54** [comment]
Yes i understand ISPConfig uses apache to host sites but i believe it uses nginx to host the control panel ? been along time since i used ISPConfig don't remember. check your server to see what ports are being used. when using a 2nd server for stream server you need to add a DNS resource record A record to point to 2nd server

**Comment by akhilleusuggo** [comment]
I managed to make it work , but not correctly . I have changed the plugin settings to port 8088 , but that's http and not https . I reloaded the page and still not working , getting an Warning from the browser , that there are scrips ( bla bla ) , after allowing that , the page turned into http and now the video plays , but not really what I want , not without the HHTPS

**Comment by akhilleusuggo** [comment]
Works finally , holy sh*t , got the idea now , need to import the SSL certificate into the NGINX config file to be able to run the site on SSL
