### ISSUE TITLE
LiveChat

### ISSUE THREAD

**Issue by tiplovo** [YouPHPTube/YouPHPTube#1915]
Здравствуйте!Установил все по мануалу,не работает чат обмен сообщениями ,что где изменить?

**Comment by RisKatOr** [comment]
Здравствуйте, 

[https://github.com/YouPHPTube/YouPHPTube/wiki/Set-up-my-own-Stream-Server](url) еще раз пройдитесь по пунктам 4,5,6 и 9.

![Adsız](https://user-images.githubusercontent.com/4102352/62032790-34a66480-b1f3-11e9-8016-9a38d9bdd73e.png)

**Comment by tiplovo** [comment]
Это все я проделал,чат открывается,сообщения я могу писать,но если другой пользователь пишет я не вижу его сообщения

**Comment by RisKatOr** [comment]
Install tables вы кликали ? давайте я попробую тоже написать в чат, напишите адрес сайта.

**Comment by tiplovo** [comment]
да базу я установил ,вот адрес http://212.60.5.232

**Comment by RisKatOr** [comment]
а какие у вас настройки в плагине на Edit parameters , можете скрин селать.

**Comment by tiplovo** [comment]
минуту

**Comment by tiplovo** [comment]
![image](https://user-images.githubusercontent.com/53423163/62036987-57914280-b20c-11e9-89e1-49413bf3a191.png)

**Comment by RisKatOr** [comment]
настройки у вас для SSL но сайт без SSL , вам нужно устанавить и активировать SSL, можно с Let's Encrypt бесплатно это сделать.

а так же девятый пункт посмотреть/проверить все.

9. in case you use a HTTPS connnection you may need to Enable secure WebSocket
sudo nano /etc/apache2/mods-available/proxy.conf

Make the file looks like this

<IfModule mod_proxy.c>
        ProxyPass /wss/ ws://127.0.0.1:8888/
</IfModule>
restart Apache

sudo a2enmod proxy_wstunnel

/etc/init.d/apache2 restart

Change the plugin variables to {"websocket":"wss://[yourServer]/wss/"}

**Comment by tiplovo** [comment]
Спасибо,понял,А без сертификата не будет работать?

**Comment by RisKatOr** [comment]
вроде и без сертификата должен работать но настройки видимо нужно обратно взять, а может и проблема вовсе не из за SSL, может быть и связано с Database (MySQL)

**Comment by DanielnetoDotCom** [comment]
OMG, I am lost on this Russian script.

I am glad I have you guys to support this.

I appreciate that

**Comment by akhilleusuggo** [comment]
@tiplovo Как нет , у меня не было сертификат первый раз когда настроил страницу и всё норм сработало , просто надо скирнуть последний пункт ( 9 )

**Comment by tiplovo** [comment]
Всем привет!Вот вчера с нуля на http все перенастроил,чат заработал в базу сообщения стали записываться,а сегодня с утра кое что правил ,перезапустил apach и все ,соединения нет,сижу битый час не пойму в чем проблема

**Comment by tiplovo** [comment]
Вобщем может кому пригодится  кто на http ,остановил apach , сделал 
sudo nano /etc/apache2/mods-available/proxy.conf
<IfModule mod_proxy.c>
        ProxyPass /ws/ ws://127.0.0.1:8888/
</IfModule>
sudo a2enmod proxy_wstunnel
sudo nohup php /var/www/html/plugin/LiveChat/chat-server.php &
sudo /etc/init.d/apache2 restart все заработало в настройках плагина ws://youserver:8888/ws/

**Comment by akhilleusuggo** [comment]
как и сказал , если ты без SSL тогда тебе надо скипнуть пукт 9
