### ISSUE TITLE
Make a video not listed

### ISSUE THREAD

**Issue by akhilleusuggo** [YouPHPTube/YouPHPTube#1916]
I'm trying to upload a video and hide it from the first page, where you can see the latest uploads , but it still appears there . When you click on it , it gives an error for lacking the permission ( normal ) , but it still shows ... Anyway to hide it ?

I have created groups and added it there , but still showing .

**Comment by DanielnetoDotCom** [comment]
Are you looking for this

![image](https://user-images.githubusercontent.com/18009293/62066572-0c753080-b208-11e9-8131-42043f4e9b9a.png)

**Comment by akhilleusuggo** [comment]
I'm not using the gallery plugin , but yes I've checked and found it . Thank you
