### ISSUE TITLE
.Gif on the video "trailer"

### ISSUE THREAD

**Issue by akhilleusuggo** [YouPHPTube/YouPHPTube#1922]
Is there anyway to customize the .gif that get automatically created when the video is uploaded ? With customize I mean change the .gif duration , the ffmpeg code line etc 
On the encoder I don't see any specification for the .gif , this mean it should be somewhere on the script page or on the DB .

What I want to customize are what part of the video I want to show as a trailer and the duration of the .gif , or create multiple .gif and join them to get from a 20mn video like 5 .gif that represent 
gif1 ( the first 20% of the video )
gif2 ( the 20-40 of the video ) and so on

**Comment by DanielnetoDotCom** [comment]
Hi,for now the gif ffmpeg command is hardcoded , we may add this option in the future to customize it.
