### ISSUE TITLE
Allow Share My Videos

### ISSUE THREAD

**Issue by akhilleusuggo** [YouPHPTube/YouPHPTube#1927]
This option is not working ''Allow Share My Videos''
I have to allow share the video 1 by 1 and manually . I'm talking about this feature on the picture bellow :
![image](https://user-images.githubusercontent.com/52116577/62285534-ae398f00-b44d-11e9-835b-722f30011b00.png)

**Comment by DanielnetoDotCom** [comment]
It depends how did you select here 
![image](https://user-images.githubusercontent.com/18009293/62294538-880df200-b441-11e9-8e93-c76d507381c8.png)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I have selected both of them

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/62328045-f8e8f480-b4a9-11e9-987d-8f99cf6d408c.png)

**Comment by DanielnetoDotCom** [comment]
disable the "PerVideo"  option, then all your videos will have (or not) the download option.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom nothing changed .I'm not talking about the download option , but about share this video :

![image](https://user-images.githubusercontent.com/52116577/62379947-f638de80-b53f-11e9-8eee-fbd94014b7dd.png)

As you can see , is not automatically made ... I have to activate this for each video I have on the site , and it's gonna take me 2-3years only ( xD )

Any idea @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
I am talking about disabling this

![image](https://user-images.githubusercontent.com/18009293/62467359-f288a000-b769-11e9-8d5a-8e22821d1402.png)

**Comment by akhilleusuggo** [comment]
I did already and no changes

**Comment by DanielnetoDotCom** [comment]
To be honest, I am not sure what is going on, but I just sent some updates to make sure it works propery

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Now it's working . And the allow video share option disappears from the videos ( that makes more sense that it work correctly )

![image](https://user-images.githubusercontent.com/52116577/62645491-3c2ce280-b944-11e9-86d8-fe6895dad229.png)
