### ISSUE TITLE
How long ago video was uploaded

### ISSUE THREAD

**Issue by k7n2g** [YouPHPTube/YouPHPTube#1931]
Hi can anyone tell me how and where to get rid of the video timestamp, when a video was uploaded please see the screencast  

https://www.screencast.com/t/uBD000Xalkb

**Comment by DanielnetoDotCom** [comment]
sorry, we do not have this option.

but maybe you can do it with CSS adding a custom CSS
https://github.com/YouPHPTube/YouPHPTube/wiki/Site-Design-and-Templates#add-a-custom-css

**Comment by k7n2g** [comment]
Thanks guys will give it a go
