### ISSUE TITLE
http and https / public ip / chrome security warning

### ISSUE THREAD

**Issue by piratesignal** [YouPHPTube/YouPHPTube#1932]
Hi,
I am trying to run new install from ec2 instance on aws.
I have installed youphptube successfully and can get to the page but I have to proceed around a security page on chrome / address showing a crossed out https before the ip address

like when I type the public ip from the ec2 instance, the chrome security page pops up that I have to proceed around to get to site, site works fine

I thought I set permissions right in ec2... using the auto ec2 youphptube subscription configuration when creating the instance

Im guessing that apache is not reading the .htaccess file maybe

I can ssh in but I am really lost at the point when I  sudo nano /etc/apache2/apache2.conf

could you please lay it down for an idiot like me on what to do next or if I am even in the right area... 

please and thank you

**Comment by akhilleusuggo** [comment]
@piratesignal Your question has nothing to do with YouPHPTube script it self . You need a valid certificate ( SSL ) or use your site without SSL ( http )
At the least provide a screen of the ''security issue'' that you're getting

**Comment by piratesignal** [comment]
ok. let me back my question up a bit, and thank you for the fast response

I have a domain hosted at godaddy but I have not pointed it at the ec2 public domain
as I am just working from the ec2 instance public ip.  54.166.254.164  
will it make a difference if I go ahead and point my domain at the that ip

**Comment by piratesignal** [comment]
im totally new to aws and all this so confusing to me, Im sorry that I have to be  the total newb asking dumb questions

**Comment by piratesignal** [comment]
oh, Im using chrome browser if that makes a dif

**Comment by piratesignal** [comment]
I understand the striked out https://    but upon first pasting in the public ip 54.166.254.164 chrome throws up that site security page that you have to click on advanced and then proceed, i feel stupid, lol, am I stupid?

**Comment by akhilleusuggo** [comment]
@piratesignal This has really nothing to do with the provider . I have never used aws but using gcp . And to be honest I don't understand your question . In anyway , what you have to do . Go to Godaddy dashboard > Manage DNS > Write the subdomain ( example www ) > Pointing to ' Public IP 54.166.254.164 as example > TTL 600 > wait for it 5mn 

Are you using any panels ? Or do you manage Apache2 by yourself ?

**Comment by akhilleusuggo** [comment]
@piratesignal Ok , I have just checked your site . It's exactly what I have said : You don't have a valid certificate . Your site doesn't mean he's not ''secure'' , the browser just check the certificate and doesn't find it signed by any authority . But to do that you need a domain name ( the one your got from godaddy )

**Comment by piratesignal** [comment]
gotcha, yes, I can manage at godaddy as Im am very familiar with their stuff. 

So godaddy servers pretty much suck for video stuff - On the other hand, Amazon is where I have set it the youphptube up.  At amazon AWS, the guys from youphptube have a standard  server setup  thing (kinda like godaddy and lets say wordpress)

**Comment by piratesignal** [comment]
and thanks for your help on a sunday at noon I really do appreciate it akhilleusuggo

**Comment by piratesignal** [comment]
im going to godaddy now and pointing the domain at the aws ip, will let you know _ probably should have done that first before asking

**Comment by akhilleusuggo** [comment]
@piratesignal It's gonna work , you can buy domain from GoDaddy , and use it on VM ows and use the storage of google . I mean , if you point everything right , should be no problem

**Comment by piratesignal** [comment]
didnt work plus Im having other problems still unresolved
thanks for your help though, I appreciate it akhill
