### ISSUE TITLE
thumbnail for vids just shows 404 

### ISSUE THREAD

**Issue by piratesignal** [YouPHPTube/YouPHPTube#1933]
![youphpthumbnailproblem](https://user-images.githubusercontent.com/53704787/62429404-48af0200-b6dc-11e9-82f1-91ce8a311375.png)

**Comment by piratesignal** [comment]
when I try to set manually it doesnt seem to take

**Comment by akhilleusuggo** [comment]
404 means the thumbnail has not been generated 
Maybe the log files can tell where the error is coming from

**Comment by DanielnetoDotCom** [comment]
If you are direct uploading the video you need a plugin (MP4ThumbsAndGif) to autogenerate thumbs.

or you can edit the thumbs on the videos manager

you can get the plugin here https://www.youphptube.com/plugins/
