### ISSUE TITLE
LiveChat

### ISSUE THREAD

**Issue by tiplovo** [YouPHPTube/YouPHPTube#1937]
Hello dears!
1-do you Expect a chat update with additional features and what?
2-And when to wait?
3 - somebody screwed third-party chat?
Всем привет!
1-Предвидится ли обновление чата с дополнительными функциями и какими?
2-когда ждать?
3- кто нибудь прикручивал сторонний чат?

**Comment by akhilleusuggo** [comment]
Пока без новости

**Comment by tiplovo** [comment]
Печально!Придется самому дописывать.хотя бы смайлы сделать и лимит на сообщения )))

**Comment by tiplovo** [comment]
![image](https://user-images.githubusercontent.com/53423163/62647386-dce1c900-b969-11e9-83c3-f587fb058b27.png)

**Comment by akhilleusuggo** [comment]
не плохо , красиво
