### ISSUE TITLE
Search functionality not working

### ISSUE THREAD

**Issue by sambhuva** [YouPHPTube/YouPHPTube#1942]
Prepare failed: (1146) Table '1Rivetsight.tags_has_videos' doesn't exist<br>

**Comment by tiplovo** [comment]
ну так написанно же не существует таблица

**Comment by sambhuva** [comment]
those things I know, but I check that db script and table creation step wasn't there.

**Comment by DanielnetoDotCom** [comment]
@sambhuva looks like you miss to install the plugins table 

![image](https://user-images.githubusercontent.com/18009293/62779944-e747b400-ba8a-11e9-8a06-146cd82f62f6.png)

**Comment by sambhuva** [comment]
it's working. Thank you.
