### ISSUE TITLE
Paypal Error

### ISSUE THREAD

**Issue by soapstreams** [YouPHPTube/YouPHPTube#1951]
I have my paypal account set up to accept payments, got the client key and secret and copied into the requisite fields in the plugin, but I when I submit payment I get the following error:

The requested URL /plugin/YPTWallet/plugins/YPTWalletStripe/redirect_url.php was not found on this server.

Please help me resolve.

jdr

**Comment by DanielnetoDotCom** [comment]
I saw this before, I am not sure how to fix, but I guess you will need to reset everything.

also make sure your plugins are up to date.

Try to follow this ...

Reset your plugins configurations (PayPal , Stripe and Wallet)

Go to the plugin, select the tab code and delete all content and save it.

![image](https://user-images.githubusercontent.com/18009293/62942509-d1016700-bdae-11e9-9f22-21173c235361.png)

make it for all 3 plugins above.

after that delete the PayPal application and create a new one. and grab the credentials again.

**Comment by soapstreams** [comment]
Nope. Can't get it to work at all. I have no idea why. Same error. Some bizarre error: "The requested URL /plugin/YPTWallet/plugins/YPTWalletStripe/redirect_url.php was not found on this server."

Almost 2 weeks and I can't get this to work now. I have no idea how to fix it or what the problem is. But I can't go live with the site or even use this script if it behaves in unpredictable and unfixable ways. I am spending money to do this and have no money coming in because I can't go live when the site doesn't work. 

Please help me resolve this and the problem with the encoders. If you can't, say so so I don't waste any more of my time or money. My summer is over, I am back at work and have less time to spend on this. I need to move this forward quickly and go live as soon as possible. Please.

**Comment by soapstreams** [comment]
By the way. I can't delete the code. It won't go away. I have even disabled the cache and manually cleared the cache. It will not delete the code from the paypal plugin. I change it. I deleted the paypal app and created another one and added the new id and secret. But same problem.

**Comment by DanielnetoDotCom** [comment]
Please email me the server credentials and a summary of what is going on I will try to fir it for you on monday

**Comment by soapstreams** [comment]
I am so frustrated.

 

#1: I have already given you my server credentials. Which server do you need access to? The VPS? You also have an admin account to log into my site with.

#2: I have already summarized what is going on. I summarized 11 days ago and again yesterday. But here it is again:

 

Whever I try to submit a payment from PayPal, I get "The requested URL /plugin/YPTWallet/plugins/YPTWalletStripe/redirect_url.php was not found on this server."

 

The Stripe plugin is NOT active. And I cannot delete the code. Every tiime I delete and save, it just reappears. On both Paypal and Stripe plugins.

 

 

 


Sent: Saturday, August 24, 2019 at 5:41 AM

**Comment by DanielnetoDotCom** [comment]
I just try your VPS credentials and the password I had does not work anymore.

I asked you to summarize everything, including the problem with encoders.

also, send me the credentials for encoder and network.

**Comment by soapstreams** [comment]
Have you been able to resolve the issue with PayPal plugin and encoders?

jdr
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 8/24/19, 5:51 PM YouPHPTube <notifications@github.com> wrote:
I just try your VPS credentials and the password I had does not work anymore.
I asked you to summarize everything, including the problem with encoders.
also, send me the credentials for encoder and network.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/YouPHPTube/YouPHPTube/issues/1951?email_source=notifications\u0026email_token=AKI2MDRP5AWY65LLOC2XOZLQGG3OFA5CNFSM4ILF7X5KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5CI2LA#issuecomment-524586284",
"url": "https://github.com/YouPHPTube/YouPHPTube/issues/1951?email_source=notifications\u0026email_token=AKI2MDRP5AWY65LLOC2XOZLQGG3OFA5CNFSM4ILF7X5KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5CI2LA#issuecomment-524586284",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by soapstreams** [comment]
And I sent you the new credentials. I will forward that email to you.

jdr
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 8/27/19, 8:58 AM YouPHPTube <notifications@github.com> wrote:
I could not take a look since the credential I have for you VPS does not work anymore.
I told you that on the other issue ticket.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/YouPHPTube/YouPHPTube/issues/1951?email_source=notifications\u0026email_token=AKI2MDTLPPGSIBO3PL6CIZ3QGUXIJA5CNFSM4ILF7X5KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5H2OWI#issuecomment-525313881",
"url": "https://github.com/YouPHPTube/YouPHPTube/issues/1951?email_source=notifications\u0026email_token=AKI2MDTLPPGSIBO3PL6CIZ3QGUXIJA5CNFSM4ILF7X5KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5H2OWI#issuecomment-525313881",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by soapstreams** [comment]
I am working today, but will create a screencast showing what happens.

jdr
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 8/27/19, 2:17 PM YouPHPTube <notifications@github.com> wrote:
Where did you click to get it?
I just click on the add funds and looks fine for me

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/YouPHPTube/YouPHPTube/issues/1951?email_source=notifications\u0026email_token=AKI2MDQAIKV5I3AHAN2GL4LQGV4WJA5CNFSM4ILF7X5KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5I2OWI#issuecomment-525444953",
"url": "https://github.com/YouPHPTube/YouPHPTube/issues/1951?email_source=notifications\u0026email_token=AKI2MDQAIKV5I3AHAN2GL4LQGV4WJA5CNFSM4ILF7X5KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5I2OWI#issuecomment-525444953",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by soapstreams** [comment]
I sent you a link to a video/screencast of this error that keeps coming up. Were you able to figure out what is causing this? Please help me fix this.

jdr
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 8/27/19, 2:17 PM YouPHPTube <notifications@github.com> wrote:
Where did you click to get it?
I just click on the add funds and looks fine for me

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/YouPHPTube/YouPHPTube/issues/1951?email_source=notifications\u0026email_token=AKI2MDQAIKV5I3AHAN2GL4LQGV4WJA5CNFSM4ILF7X5KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5I2OWI#issuecomment-525444953",
"url": "https://github.com/YouPHPTube/YouPHPTube/issues/1951?email_source=notifications\u0026email_token=AKI2MDQAIKV5I3AHAN2GL4LQGV4WJA5CNFSM4ILF7X5KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5I2OWI#issuecomment-525444953",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by DanielnetoDotCom** [comment]
Please delete the monthly plan and create a new one.

this may fix the redirect error.

**Comment by soapstreams** [comment]
I will give it a shot. Thanks.

jdr
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 8/30/19, 9:05 AM YouPHPTube <notifications@github.com> wrote:
Please delete the monthly plan and create a new one.
this may fix the redirect error.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/YouPHPTube/YouPHPTube/issues/1951?email_source=notifications\u0026email_token=AKI2MDXO7REVEUSXFLCMUYLQHESJBA5CNFSM4ILF7X5KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5RX6XQ#issuecomment-526614366",
"url": "https://github.com/YouPHPTube/YouPHPTube/issues/1951?email_source=notifications\u0026email_token=AKI2MDXO7REVEUSXFLCMUYLQHESJBA5CNFSM4ILF7X5KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5RX6XQ#issuecomment-526614366",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by soapstreams** [comment]
Thank you very much. That seems to have resolved the issue. Thank you very much.

 

jdr

 

Sent: Friday, August 30, 2019 at 9:05 AM
