### ISSUE TITLE
Admin login issue

### ISSUE THREAD

**Issue by illias1** [YouPHPTube/YouPHPTube#1952]
Hey!

I cannot log-in to the admin account anymore since in my last session I changed user login to be required to use email. So, "admin" user cannot log in anymore and the email I believe was the admin email doesn't work either (normal user can log in, no problem here). I am sure about my password. 

I also changed my password through
https://github.com/YouPHPTube/YouPHPTube/wiki/Reset-a-Password
but an email user input is still required...

Could you explain how to go around this issue, please?

Kind regards,

**Comment by akhilleusuggo** [comment]
You don't need an email for the SSH changing password . You just need to specify the user name ( on your case ''admin'' )
You can also try changing it from the DB ( not recommended )
The SSH user is the best option

**Comment by DanielnetoDotCom** [comment]
@illias1 I guess I understand what you mean, you are forced to use the email, but your admin username is only admin.

you need to reset your configuration to the default one, try this in your MySQL

`DELETE FROM plugins WHERE name='CustomizeUser';`

with this you should reset your users configuration and will be able to login again

**Comment by illias1** [comment]
I couldn't wait and reinstalled the website once again. However, the issue persisted and I could go around by replacing the "admin" user by the email. 
So, maybe I'm the only one, but it seems like the form requires an email, however, the app continues reading the "user" value and not the "email" associated to it

**Comment by DanielnetoDotCom** [comment]
try to clear the configuration as I mention above, or manually replace the user field, on the database, with the email

**Comment by illias1** [comment]
The second is what i did and it works. Thanks:)
