### ISSUE TITLE
Unclear license, and statement making YouPHPTube non-free software

### ISSUE THREAD

**Issue by 717g301github** [YouPHPTube/YouPHPTube#1956]
> This Software must be used for Good, never Evil. It is expressly forbidden to use YouPHPTube to build porn sites, violence, racism or anything else that affects human integrity or denigrates the image of anyone.

The license tells it is free software. Without limitations.

You are stating on your front page the above quote which makes it unfree software by definition. You have stated expression "used for good, never evil", which is vague, and nobody can know what you mean "good" or "evil". You are forbidding it to use it for porn sites, which makes it non-free software. I am not interested to build a porn site, but I am interested that there are many decentralized video websites that will help in fediverse. However, forbidding it for porn sites, first does not define well what is porn and makes it non-free software. It would be anyway impossible to forbid it really.

You are forbidding to build website with violence, yet there is so much violence in the world, this would forbid the majority of news about violence. It makes it non-free software.

"Anything else that affects human integrity" is vague definition.

In general, can you make this software really free software without those statements?

You can say that "You would not like it to be used for those issues, and that is your personal opinion".

You could state that "You would not provide support for such usages", which is also legitimate.

But to expressly forbid it on front page, extends the LICENSE into something vague and legally binding, I would ask you to change those wordings so that your software really becomes free software by definition: https://www.gnu.org/philosophy/free-sw.html

**Comment by DanielnetoDotCom** [comment]
I am sorry, but I will NOT remove it.

**Comment by 717g301github** [comment]
So can you provide clear license that I understand if it is free software or proprietary software?
