### ISSUE TITLE
Adsense option disappeared 

### ISSUE THREAD

**Issue by akhilleusuggo** [YouPHPTube/YouPHPTube#1957]
![image](https://user-images.githubusercontent.com/52116577/63133529-96b9e480-bfbd-11e9-9934-4af472a896dd.png)

For some reason the adsense option disappeared . On plugins it's activated but not working

**Comment by DanielnetoDotCom** [comment]
Hi

there is nothing on the code to hide it.

I guess something else hide it from you. maybe an AD block

**Comment by xemtube** [comment]
Maybe an ad blocking program has hidden adsense away. Find what software is blocking to disable it or try using another browser.

**Comment by akhilleusuggo** [comment]
It was a caching problem with the AsyncJobs on the plugins . After disabling the option and clearing the cache , it went back. Weird , vut solved the problem .
