### ISSUE TITLE
Problem new Editor (added Screenshots)

### ISSUE THREAD

**Issue by TLCReuver** [YouPHPTube/YouPHPTube#1960]
First at all, the new editor is a very nice enhancement for YPT, many thanks.

I have to modify about 1000 videos with the new structure but it's wort it.

First problem is that the links saved as 'new window" opened in the current window (also not modified in MySQL).

The second is that "next video" is cleared when i modify video (like editing text, tags etc.) and i have lot of next videos assigned.

**Comment by DanielnetoDotCom** [comment]
hey, can you please screenshot so I can understand what is happening?

**Comment by TLCReuver** [comment]
Hi Daniel, I added some screenshots:

1.  "Next video" is cleared when i modify video (like editing text, tags etc.)
![Record](https://user-images.githubusercontent.com/39981177/63220685-4c875d80-c18d-11e9-82dc-238273c44b91.jpg)

2. Links saved as 'new window" opened in the current window
![New_Window](https://user-images.githubusercontent.com/39981177/63220701-8a848180-c18d-11e9-903a-0522ec3f53f8.jpg)
Missing here "_blank" like
![New_Window 2](https://user-images.githubusercontent.com/39981177/63220726-08e12380-c18e-11e9-8014-67eccffcab3a.jpg)

3. With the new structure I have to modify every record to insert some "Enters" to correct it but i have no problems to do that.
![Structure](https://user-images.githubusercontent.com/39981177/63220771-9fade000-c18e-11e9-8b8f-8a2f7b07102e.jpg)

**Comment by DanielnetoDotCom** [comment]
1. "Next video" 

I could not reproduce it on my side. can you please try to reproduce it on demo site?

2. Links saved as 'new window" 

Fixed  

3. With the new structure I have to modify every record 

Yes, that was my bad I should, not release this editor yet, and make it auto update them all 
I released by mistake and I can not roll back now.

**Comment by TLCReuver** [comment]
Hi Daniel,

I tested NextVideo on DemoSite and i've got the same problem and edited this video:

![NextVideo_0](https://user-images.githubusercontent.com/39981177/63324418-50031c00-c328-11e9-8b1f-75077b1722f0.jpg)

Created Next Video and save it:

![NextVideo_1](https://user-images.githubusercontent.com/39981177/63324473-70cb7180-c328-11e9-82d2-9847175458e1.jpg)

It is saved properly:

![NextVideo_2b](https://user-images.githubusercontent.com/39981177/63324767-036c1080-c329-11e9-80c4-d2f147ee0b89.jpg)

When i edit the Video on the same way:

![NextVideo_3](https://user-images.githubusercontent.com/39981177/63324828-2dbdce00-c329-11e9-856e-3915ad77fffc.jpg)

... the Next Video is not showing anymore:

![NextVideo_4](https://user-images.githubusercontent.com/39981177/63324932-6493e400-c329-11e9-9c6f-b10bfd594c80.jpg)

When i save the Video (also without editing the text), the Next Video is cleared:

![NextVideo_5b](https://user-images.githubusercontent.com/39981177/63325209-fd2a6400-c329-11e9-9932-a9d6fb5bb1c8.jpg)

**Comment by DanielnetoDotCom** [comment]
Thanks, issue was confirmed and fixed

**Comment by TLCReuver** [comment]
Perfect, thanks.
