### ISSUE TITLE
Recording Live Stream 

### ISSUE THREAD

**Issue by akhilleusuggo** [YouPHPTube/YouPHPTube#1966]
Anyway to get automatically get the name of the recorded file stream ( /tmp ) to match the actual name stream ?

**Comment by DanielnetoDotCom** [comment]
I guess if you are using the plugin SendRecordedToEncoder this is the default behaviour, correct?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I forgot that you implemented the plugin. No i'm not using it for the moment . I'm trying something to get something better work ( live transcoder ) . Works for me for non YouPHPTube script , but need to go deeper and get some more knowledge to get it work .
