### ISSUE TITLE
Errors in new version 7.5 - In upload new video or modify

### ISSUE THREAD

**Issue by alegiovannelli** [YouPHPTube/YouPHPTube#1967]
In the new version updated i have those errors in uploading or modify videos:

` PHP Fatal error:  Uncaught Error: Call to undefined function ctype_space() in /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier/Token/Text.php:43
Stack trace:
#0 /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier/Lexer/DirectLex.php(161): HTMLPurifier_Token_Text->__construct('\n\n')
#1 /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier.php(215): HTMLPurifier_Lexer_DirectLex->tokenizeHTML('\n\n', Object(HTMLPurifier_Config), Object(HTMLPurifier_Context))
#2 /var/www/localhost/htdocs/objects/video.php(1367): HTMLPurifier->purify('<!DOCTYPE html>...')
#3 /var/www/localhost/htdocs/objects/videoAddNew.json.php(82): Video->setDescription('<!DOCTYPE html>...')
#4 {main}
  thrown in /var/www/localhost/htdocs/objects/htmlpurifier/HTMLPurifier/Token/Text.php on line 43
`

![Senza titolo](https://user-images.githubusercontent.com/29068703/63218932-0b7c5280-c167-11e9-8207-60fae7ae7cbf.png)

The files referenced in tinymce directory are not present.

Perhaps these are TinyMCE premium paid plugins not included in the repository. Is it possible to disable them to avoid errors?

Thank you in advance for your help

**Comment by clienttask** [comment]
I think it is permission issue. Try to set this /objects directory folders to 777.

**Comment by TLCReuver** [comment]
Same problem here because jpg en gif are stored as .jpg and .gif (without filename).

You can delete these files in Videos-folder.
I temporary fix this to "Direct Upload" a *.mp4, save it and edit the video and upload .jpg and/or .gif afterwards till the problem is solved.

**Comment by DanielnetoDotCom** [comment]
As I can see the problem is this ...

`PHP Fatal error: Uncaught Error: Call to undefined function ctype_space()`

you should google how to fix it.

**Comment by alegiovannelli** [comment]
Thank you very much, that was the problem. I installed the php ctype module and it immediately worked. In previous releases perhaps this module was not used. Thanks for the valuable help. I close this issue.
