### ISSUE TITLE
Add the link in the live page to the Channel's Channel page.

### ISSUE THREAD

**Issue by xemtube** [YouPHPTube/YouPHPTube#1969]
In the live page, you need to add the link in the channel logo to the channel page of the channel. Details you see illustrations

![1](https://user-images.githubusercontent.com/50126312/63223508-bbda6d00-c1e0-11e9-92a1-8d0d28c20129.png)

**Comment by akhilleusuggo** [comment]
Yeh , you're right , never seen it too

**Comment by DanielnetoDotCom** [comment]
Agree

**Comment by xemtube** [comment]
Currently the Link to the Channel is not the correct address of the Channel. I tried it on demo.youphptube.com, the same error happened.

**Comment by DanielnetoDotCom** [comment]
You are right , I am sorry
