### ISSUE TITLE
Public Encoder

### ISSUE THREAD

**Issue by BreadAbuse** [YouPHPTube/YouPHPTube#1971]
When I go onto the public encoder through my website everything works as normal except it says "Sorry! We could not find your streamer site!" Can I have help? (Im making a non-profit site and don't want to spend much money on it I do know i can use https://youphptube.com/services )

**Comment by DanielnetoDotCom** [comment]
Hi

please check your encoder and streamer log file, you may find some clue.

post them here, we may  be able to help you.

**Comment by BreadAbuse** [comment]
No no I use the public encoder

**Comment by DanielnetoDotCom** [comment]
probably because your streamer is not in a public network.

what is the domain and IP of your streamer?

**Comment by BreadAbuse** [comment]
sharevid.danwin1210.me 116.202.17.147 its on a proxy server for my hosting service

**Comment by DanielnetoDotCom** [comment]
but what is your streamer URL?

sharevid.danwin1210.me does not look like a YouPHPTube site.

**Comment by BreadAbuse** [comment]
sharevid.danwin1210.me/vid/

**Comment by BreadAbuse** [comment]
Its running the software

**Comment by BreadAbuse** [comment]
OOOOHHHHH for some reason its redirecting let me fix that

**Comment by DanielnetoDotCom** [comment]
probably when you fix the redirect you will get some progress

**Comment by BreadAbuse** [comment]
I fixed the redirect I just want to set it up.

**Comment by akhilleusuggo** [comment]
@BreadAbuse Just to make things clear. What do you mean with public encoder? Are you talking about the encoder from YouPHPTube ? I mean encoder.youphptube.com ? Or you want to set a public encoder ?? Make sure to git pull and check that your encoder on the setting matchs the link I have provided up . Also make sure to provide the same link of your website on the encoder site .
In case of failure try this 2 links
https://sharevid.danwin1210.me/vid
&
https://sharevid.danwin1210.me/vid/
Provide your user name and password , you should not find any issue

**Comment by BreadAbuse** [comment]
@akhilleusuggo I tried to use that but it doesn't work. I don't know why its a fresh install with the requirements. THe only thing I think is stopping it is I haven't got URL rewrite setup on NginX (I converted it and everything works fine on it)

**Comment by akhilleusuggo** [comment]
@BreadAbuse So you're not using apache ?

**Comment by BreadAbuse** [comment]
No, I am not using Apache2 but everything is working as fine until my hosting service sets up the url rewrite. I tested uploads and more they worked excellent I just can't view the videos because Url rewrite isn't set up yet.

**Comment by BreadAbuse** [comment]
I might just install my own encoder because nothing it working :(
