### ISSUE TITLE
Error Link to wrong channel of channel

### ISSUE THREAD

**Issue by xemtube** [YouPHPTube/YouPHPTube#1972]
https://github.com/YouPHPTube/YouPHPTube/issues/1969

Currently the Link to the Channel is not the correct address of the Channel. I tried it on demo.youphptube.com, the same error happened.

https://user-images.githubusercontent.com/50126312/63223508-bbda6d00-c1e0-11e9-92a1-8d0d28c20129.png

**Comment by DanielnetoDotCom** [comment]
Thanks for notice I just sent a fix.
