### ISSUE TITLE
autoplay for livestream

### ISSUE THREAD

**Issue by mikweb2017** [YouPHPTube/YouPHPTube#1973]
I still have not found how to start the stream automatically a visit must always click play?
i dont work anymore

**Comment by DanielnetoDotCom** [comment]
Did you tried this?

![image](https://user-images.githubusercontent.com/18009293/63270283-487f3c80-c26e-11e9-8c3d-e103ed9c06e4.png)

**Comment by DanielnetoDotCom** [comment]
Anyway, I just notice the browsers are blocking autoplay on unmuted videos.

**Comment by mikweb2017** [comment]
yes but dont wokr

**Comment by mikweb2017** [comment]
you have fixed now work agein
