### ISSUE TITLE
Error of failing to embed embed for Playlist url with long titles

### ISSUE THREAD

**Issue by xemtube** [YouPHPTube/YouPHPTube#1975]
Error of failing to Bulk embed for Playlist url with long titles.

Example Url Playlist :
 https://www.youtube.com/watch?v=5TCp7Pp8s0w&list=PLIcpO_qbgWPAEzzjnc00IZ2kghZWuFZoE

![image](https://user-images.githubusercontent.com/50126312/63327685-e2231880-c358-11e9-8ead-765e3313b30c.png)

- I tried testing on demo.Youphptube.com, the same error occurred. You can check and fix this error

**Comment by DanielnetoDotCom** [comment]
Hi, it should work now
