### ISSUE TITLE
Videoplayer is not showing

### ISSUE THREAD

**Issue by TLCReuver** [YouPHPTube/YouPHPTube#1976]
Since the last update the videoplayer is gone (it seem to be with non_embedded Videos)
This is also on demo-site.

![Video](https://user-images.githubusercontent.com/39981177/63352342-3e8a3600-c361-11e9-8439-ddb72b81f2e3.jpg)

**Comment by DanielnetoDotCom** [comment]
You were right, please try now

**Comment by TLCReuver** [comment]
Problem fixed. Thanks.
