### ISSUE TITLE
The video player is not displayed

### ISSUE THREAD

**Issue by itdoka** [YouPHPTube/YouPHPTube#1977]
Hi! Today I installed a new version of the site and encountered such a problem.
![bandicam 2019-08-20 21-43-13-739](https://user-images.githubusercontent.com/52359603/63354384-ecfc9e00-c396-11e9-9869-69f9cd269f8c.jpg)
It seems that there are simply not enough images.
![bandicam 2019-08-20 21-42-12-474](https://user-images.githubusercontent.com/52359603/63354714-8fb51c80-c397-11e9-870a-3ff39e8c1550.jpg)
![bandicam 2019-08-20 21-43-40-426](https://user-images.githubusercontent.com/52359603/63354769-a65b7380-c397-11e9-8107-63927dfa6433.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, I sent a fix for this an hour ago, please update your files

**Comment by itdoka** [comment]
Thanks

вт, 20 авг. 2019 г. в 22:28, YouPHPTube <notifications@github.com>:

**Comment by TLCReuver** [comment]
Problem fixed, thanks.
