### ISSUE TITLE
A bug in YouPHPTube

### ISSUE THREAD

**Issue by lm0963** [YouPHPTube/YouPHPTube#1979]
There is a bug in User::login and sqlDAL::readSql. Anyone can login as admin without knowing the password.
![image](https://user-images.githubusercontent.com/28585832/63490014-40c9cd00-c4e6-11e9-95af-b26ac2d4feaf.png)

That is all about crc32 collision, so just delete the find_Old or change to another hash function.

**Comment by DanielnetoDotCom** [comment]
Hi, 

I really appreciate your help, security is very important for us.

I still do not get it how it may happen. How can we login without password?

find_Old method is used only for old logins HASH compatibility (MD5). it can be secure removed without affect the YouPHPTube features.

Anyway, I just sent an update to disable the old hash by default, but it can be enabled back on the CustomizeAdvanced plugin (enableOldPassHashCheck)

**Comment by lm0963** [comment]
Hi,

I am not sure if it's a good idea to discuss that bug in public.

When it try to get users' information, it will call readSql. In that function, it will cache the sql results.That caches use the crc32 as index. That means two different sql sentence may hit on one cache. That is the bug. I found the key out just taken for 5 minutes.

In find_Old just append the raw pass(really raw,not encoded) to the end of the string to calculate crc32.

**Comment by DanielnetoDotCom** [comment]
Got it, thanks

so the problem is the cache. I just realize the login should never use the cache.

I am sending a new update that makes the login do not use the cache.

**Comment by lm0963** [comment]
In fact, I think it will be much simpler to just delete the find_Old or just change crc32 to md5(or just other hash function). crc32 should not be used as a hash function.

**Comment by DanielnetoDotCom** [comment]
Ok thanks, I am listen you.

changed to MD5

**Comment by akhilleusuggo** [comment]
I guess you saved the community

**Comment by DanielnetoDotCom** [comment]
I had to revert it back due this

https://github.com/YouPHPTube/YouPHPTube/issues/1980

It was overloading the server in a loop that never ends.

the login is secured since it does not use the cache anymore.

change crc32 to md5 I will need to take a better look to see what is that huge impact.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Thank you Sir

**Comment by lm0963** [comment]
Hi,

I google for a while, and I think maybe that is because the dechex funcion. But I can't make sure. And just a suggest, if possible, relpacing the crc32 with other hash function. Or can't make sure what sql sentence is really excute.

**Comment by akhilleusuggo** [comment]
There's 2 option that I don't know for what they're used . If possible @DanielnetoDotCom can explain:
enableCachePerUser
enableCacheForLoggedUsers

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo those options cache the full HTML page, they does not cache queries

SQL queries are idependent of plugins

and @lm0963 is correct the dechex was causing it. remove dechex and replace with md5 looks like works
