### ISSUE TITLE
Youphptube 502 error failed to access Youphptube after I updated Youphptube

### ISSUE THREAD

**Issue by xemtube** [YouPHPTube/YouPHPTube#1980]
After I updated Youphptube cd / var / www / html / YouPHPTube / && sudo git pull. I cannot access Youphptube again, report 502 error. Check tail -n 200 -f /var/www/YouPHPTube/videos/youphptube.log does not appear at all. You check the update for any errors.

**Comment by akhilleusuggo** [comment]
Yeh , the site is broken , and uses the 100% of the RAM and CPU . My site died

**Comment by DanielnetoDotCom** [comment]
I guess it is fixed now
