### ISSUE TITLE
Error not showing Channel name after update

### ISSUE THREAD

**Issue by xemtube** [YouPHPTube/YouPHPTube#1981]
Add 1 More error is not showing the Channel name after updating

![image](https://user-images.githubusercontent.com/50126312/63528925-03892d80-c52e-11e9-84a0-b3ef413a2c7a.png)

**Comment by DanielnetoDotCom** [comment]
How are those option on your side?
![image](https://user-images.githubusercontent.com/18009293/63529520-276f5380-c4db-11e9-8529-7f5a59c765a8.png)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom This happens sometimes , maybe it's something from server . Happens very often on the stream chat when the internet is slow . It shows the ID channel instead of the Name Channel .
