### ISSUE TITLE
Thumbnail slow loads

### ISSUE THREAD

**Issue by akhilleusuggo** [YouPHPTube/YouPHPTube#1982]
The thumbnail are actually loading really slow . When i mean slow , I don't really mean that has something to do with the internet , they are just on blur , and after 10-15s they all show at once . Witch makes me thing they all got downloaded , but for some reason they don't show up quickly , but when they show up , they show up all at once

**Comment by akhilleusuggo** [comment]
Edit : What may need to happen is to show the thumbs as the loads goes , not when all the page are downloaded from the server . I don't know if I'm explaining

**Comment by DanielnetoDotCom** [comment]
those are the lines that load the images.

https://github.com/YouPHPTube/YouPHPTube/blob/cdd30fd419add42745f49f1f44262e87d8bdcf56/view/js/script.js#L40

we load first small resolutions of the images, and after your server load the full HTML we load the real images.

maybe some other script is slowing down you to load your full page

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom How can I know what actually slowing down the site ? The small resolutions loads instantly ( if you mean the blurry images ) , but the ''clear'' images takes 10-20s :(

**Comment by DanielnetoDotCom** [comment]
Usually what I do, I go to the Developer Tools tab, select network and check what content is taking longer to load

![image](https://user-images.githubusercontent.com/18009293/63686530-7fa69e00-c7d8-11e9-8229-c5c17aed9ef7.png)

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/63705863-f8801700-c825-11e9-99a9-e812094b98cb.png)

I'm not sure what does playlist means , but there's a lot of them

**Comment by akhilleusuggo** [comment]
That actually was from ''ALL'' requests , do you need something in particular  ? cause that what I see :
![image](https://user-images.githubusercontent.com/52116577/63707703-79411200-c82a-11e9-9b3a-be441bd2dbd6.png)

It's a big list , I can not show on a screenshot

**Comment by akhilleusuggo** [comment]
This one from my second site with less loading stuff 
![image](https://user-images.githubusercontent.com/52116577/63707870-e2c12080-c82a-11e9-9d53-620e081fda5a.png)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I would say ' Very notable difference '' . Time load now improved from 15s to 4s . Thank you :) . Works 👍
