### ISSUE TITLE
1 physical server for multiple sites live streaming 

### ISSUE THREAD

**Issue by akhilleusuggo** [YouPHPTube/YouPHPTube#1988]
So my question is there's anyway to create for example 2 sites with YouPHPTube and use the same server to stream on both sites ? Since on the nginx config we need to add the link of the site , I don't see how to add the link of the second site to be able to stream on it . 
So basically what I'm asking if is there anyway to create some kind of proxy or Vhost Nginx stream .

**Comment by DanielnetoDotCom** [comment]
Sorry, I can not help you with that.

I am only able to install 1 Livestream per server.

**Comment by akhilleusuggo** [comment]
thanks for the answer :)
