### ISSUE TITLE
Upload video via encoder stuck at sharing queue

### ISSUE THREAD

**Issue by one1page** [YouPHPTube/YouPHPTube#1991]
Help!!!
I installed the streamer and used public encoder without a problem. But lately i found out that some videos uploaded on my site was not actually mine and look like it has something to do or from the public encoder. So, i installed a local encoder on my server. Installation went well but my uploading stick on sharing queue (on encoder) and also showing progress(on queue) on my streamer.

Refer to attached images and log files below:

[(encoder)youphptube.log](https://github.com/YouPHPTube/YouPHPTube/files/3539793/encoder.youphptube.log)
[(streamer)youphptube.log](https://github.com/YouPHPTube/YouPHPTube/files/3539797/streamer.youphptube.log)
![encoderqueue](https://user-images.githubusercontent.com/17507134/63669739-61a76080-c80d-11e9-859e-8318d5f4c1b5.JPG)
![streamerqueue](https://user-images.githubusercontent.com/17507134/63669740-61a76080-c80d-11e9-97a3-dbb4f146ce8b.JPG)

Thanks and Regards,
G. H. Pacete

**Comment by DanielnetoDotCom** [comment]
Hi, looks like you could download but you could not encode

First I would recommend you to make sure you have the latest FFMPEG

try this: 

`sudo add-apt-repository ppa:jonathonf/ffmpeg-4 && sudo apt-get update -y && apt-get install ffmpeg`

If the error persists check the log file for some clue.

**Comment by one1page** [comment]
Hi Daniel, thanks for the response. I tried your recommendations and also tried to reinstall FFMPEG and encoder but no to avail error still persist. I'm quite new to configurations on linux and working with VODs so i find it hard to find the cause of problem even on log files.

[youphptube(encoder).log](https://github.com/YouPHPTube/YouPHPTube/files/3548588/youphptube.encoder.log)
this is the fresh log file generated by my encoder and below is from my streamer:
[youphptube(streamer).log](https://github.com/YouPHPTube/YouPHPTube/files/3548601/youphptube.streamer.log)

If you can spare some time please i just need some clue on where to resolve the problem. 

Thanks and regards,
G. H. Pacete

**Comment by akhilleusuggo** [comment]
You need make sure you're giving the correct php upload limit etc on the php.conf

**Comment by one1page** [comment]
Hi @akhilleusuggo, thanks for response. 
My PHP upload limits are so far enough and should not be the cause. I set my limits to 6GB both on streamer, encoder and system wide configuration. I tested my streamer and can upload without a problem on public encoder. My issue only exist on my local encoder installed on the same server with my streamer.

Thanks and regards,
G. H. Pacete

**Comment by akhilleusuggo** [comment]
@one1page Ok , are you sure you're giving the right ''chmod'' to the encoder and streamer site ?
1)Could you try to give chmod 777 to the /var/www/html/YouPHPTube/videos and /var/www/html/YouPHPTube-Encoder/videos

2) Git pull
3)I see that you're using a panel . Is not recommended for this script , cause you will always be having some issues . I'm saying this from log file /var/www/clients/client1/web1/web/bccwebstream/
Are you using ISPConfig ?

**Comment by one1page** [comment]
@akhilleusuggo yes sir, "videos" folder permissions on both streamer and encoder are already writable. My server is a LAMP server with ubuntu 14.04 with PHP7 and apache2 managed through ispconfig.
I installed both encoder and streamer using terminal.

**Comment by akhilleusuggo** [comment]
@one1page I knew that because I had many problems with ISPConfig with this script . This is not a blog website .
Is not about writable , just with the permissions . Anyway I don't know what may cause it , as far I know none uses ubtuntu 14.04 for this script

**Comment by one1page** [comment]
@akhilleusuggo, my streamer has no problem running on ubuntu 14.04 with ISPConfig and most of my php and apache configurations i do it directly on config files(via terminal) not with ISP Config UI. I read on some blogs and issues here that they just do not use ubuntu 14.04 because its no longer available on most location and default package of 14.04 are running PHP5 version. I managed to run PHP7, apache2 with ngin-x and rtmp on this platform so most of the problems that others encountered on streamer site(specially live streaming) are not present on my setup.
"CHMOD 777" permits write access on specified folders and i can confirm that i have no problem on permissions as i can read and write on the location. Actually, i tried to trace the encoding proccess and found that video files were successfully written on videos folder.
I think the issue is at "encoding" (as what @DanielnetoDotCom said) and thats where i am not sure where to start looking to try to fix the problem.
I can confirm that FFMPEG were installed and also tried to put up other streaming platform on other locations to test the encoder and resulted to same problem, thus, issue was found to be on my local encoder site.

**Comment by one1page** [comment]
@DanielnetoDotCom thanks  Daniel. Unfortunately, i hung right here. I managed to install PHP7.0 on ubuntu 14.04 but look like some of its packages are incompatible with 14.04 libraries thats why curl is not working the way it is. For now, I'll try to up a new server with ubuntu 16.04 for my local encoder. I cant upgrade my current ubuntu 14.04 because of my customized applications that are only able to run on this platform and lower version of ubuntu and debian which are very troublesome to upgrade.
Thanks for the responses. I will mark this issue  close upon the completion of my ubuntu 16.04 setup.

Regards,
G. H. Pacete

**Comment by one1page** [comment]
Hi @DanielnetoDotCom, I manage to setup ubuntu 16.04 encoder site and all of curl errors are gone. But i still get an error and status error just tell me that error is "[]", Please help me what could be wrong.
Here is my logfile:
[youphptube.log](https://github.com/YouPHPTube/YouPHPTube/files/3561377/youphptube.log)

Thanks and regards,
G. H. Pacete

**Comment by one1page** [comment]
Sorry @DanielnetoDotCom for tagging again. I managed to fix the problem. I just update ffmpeg to ffmpeg-4 that you gave above. Thanks and cheers for more years with youphptube.

Regards,
G. H. Pacete
