### ISSUE TITLE
LiveChat spam in the chat on the stream

### ISSUE THREAD

**Issue by tiplovo** [YouPHPTube/YouPHPTube#1995]
how to fix the endless chat messages,someone came into the chat and wrote all things and empty messages,to such an extent that much of the site hovered,in the code not found where to turn off

**Comment by akhilleusuggo** [comment]
Make only registered/logged in users to be able to use chat .

**Comment by akhilleusuggo** [comment]
@JoshWho agree . But did you put only registered user can type on chat ? Because if you do , you actually ''ban'' them . On users panel with the admin account . If you leave the chat open for non registered users , well you're asking for spam then

**Comment by akhilleusuggo** [comment]
@JoshWho So , they register an account by email verification ? That's what you're saying ? Never seen bots confirming accounts and going thou captcha for a small site ( the most likely you have )

**Comment by akhilleusuggo** [comment]
@JoshWho Can't help you with that , even if they there's some IP blocker they can use VPN ... I mean your problem is personal more then other thing

**Comment by tiplovo** [comment]
Чат сделан видимо для наглядности,многие наверно не встречали тролей.....

**Comment by palich91** [comment]
I support, the chat needs to be finalized! Be sure to make it possible to ban in the chat

**Comment by akhilleusuggo** [comment]
looks like someone is talking to me . @DanielnetoDotCom is the script owner , i'm just like you , a script user 👍

**Comment by tiplovo** [comment]
> похоже, со мной кто-то разговаривает . @DanielnetoDotCom является владельцем сценария, я так же , как и вы, пользователь сценария

If he is a developer, then he is aware of what protection should be .Take any forum the easiest ,there is protection from sending blank messages and some sort of filtration,and then in the chat it turns out nothing is,and you can chat to shove anything that may harm the website
