### ISSUE TITLE
 Error not displaying video management list after update

### ISSUE THREAD

**Issue by xemtube** [YouPHPTube/YouPHPTube#1998]
After I finished updating YouphpTube. The video management section of the administrator account is corrupt and cannot display the video list. Details according to the attached image. Please check and fix it

![image](https://user-images.githubusercontent.com/50126312/63855157-ef7b7b00-c9c8-11e9-9117-7662f4ced44b.png)

**Comment by xemtube** [comment]
I have cleared the cache but the error still happens.

**Comment by xemtube** [comment]
I have updated this command cd / var / www / html / YouPHPTube / && sudo git pull.

Now I have to update it correctly

**Comment by xemtube** [comment]
I have tried downloading the original Youphptube from https://github.com/YouPHPTube/YouPHPTube but I still find many files missing such as error in the image, is there any way to fully update it. Can you check it again?

![image](https://user-images.githubusercontent.com/50126312/63862453-cf52b880-c9d6-11e9-9cbc-1084720cc84c.png)

**Comment by xemtube** [comment]
This error comes from Plugin Blackblaze_B2. When I turned off the Blackblaze_B2 Plugin, everything worked normally. The error only occurred when I turned on the Blackblaze_B2 Plugin. Can you check this problem again?

**Comment by DanielnetoDotCom** [comment]
I see, can you please check your log files?

**Comment by xemtube** [comment]
I check the Youphptube diary there is nothing there. Details as attached photo

![image](https://user-images.githubusercontent.com/50126312/64026253-91859980-cb68-11e9-89d1-52672e585ee2.png)

**Comment by DanielnetoDotCom** [comment]
you are using the wrong directory

try **/var/www/html/YouPHPTube/videos/youphptube.log**

so the command may be `tail /var/www/html/YouPHPTube/videos/youphptube.log`

**Comment by xemtube** [comment]
![image](https://user-images.githubusercontent.com/50126312/64026597-46b85180-cb69-11e9-9d3c-65a6b170f8b5.png)

**Comment by xemtube** [comment]
I resend the error log image when enabling B2 plugin.

![image](https://user-images.githubusercontent.com/50126312/64026923-e5dd4900-cb69-11e9-95f5-248306ed0015.png)

**Comment by DanielnetoDotCom** [comment]
Looks like your backblaze credentials are wrong.
