### ISSUE TITLE
Do not show ads at some location

### ISSUE THREAD

**Issue by xemtube** [YouPHPTube/YouPHPTube#2001]
How to display ads in these positions. I placed ad code on the ADs Plugin like on demo.youphptube. But the following positions do not see the same display on the demo.youphptube web. Thank you !

![image](https://user-images.githubusercontent.com/50126312/64058623-f5937680-cbd7-11e9-83d6-e41e37d7d5da.png)

![image](https://user-images.githubusercontent.com/50126312/64058658-6f2b6480-cbd8-11e9-877f-df90e616ebc4.png)

**Comment by DanielnetoDotCom** [comment]
This is an automatic position for adsense

Google autoplace this ad over there

![image](https://user-images.githubusercontent.com/18009293/64172373-3c2cdf00-ce2b-11e9-88a9-578d16785b70.png)
