### ISSUE TITLE
Direct links do not give Opengraph/Schema.org/Twitter card data

### ISSUE THREAD

**Issue by 717g301github** [YouPHPTube/YouPHPTube#2002]
If I copy link from here:
https://demo.youphptube.com/trending
such as:
https://demo.youphptube.com/video/conan-the-barbarian-2011-red-band-trailer-hd-18-

then link does not show or have Opengraph/Schema.org/Twitter card data, result:
https://pleroma.gnusocial.club/notice/9mRp0P9ORhFmfWAcM4

however, if I copy this link:
https://demo.youphptube.com/video/conan-the-barbarian-2011-red-band-trailer-hd-18-?rrating=1

then it works fine:
https://pleroma.gnusocial.club/notice/9mRp2WFH2QnNFgvfCy

**Comment by JoshWho** [comment]
I would also like to have a place to upload a Open Graph image for my home page. and to add it to the Header of the home page so when people shares the site they will get a preview of it just like the video thumbs.

**Comment by DanielnetoDotCom** [comment]
@717g301github please try now

@JoshWho do you mean for global usage? for example when sharing a page without any video?
it supposes to show your site logo correct?

**Comment by 717g301github** [comment]
It is not working:
https://demo.youphptube.com/video/conan-the-barbarian-2011-red-band-trailer-hd-18-

is not giving any nice Schema.org/Twitter Card/Facebook Opengraph

And I think you should implement Schema.org in addition to Facebook Opengraph, as not really everybody has Facebook, and it is tied to Facebook page admin ID, which makes no sense to tie people to proprietary network.

**Comment by DanielnetoDotCom** [comment]
I guess it is cached in your side.

if you test it here it is working

https://opengraphcheck.com/result.php?url=https%3A%2F%2Fdemo.youphptube.com%2Fvideo%2Fconan-the-barbarian-2011-red-band-trailer-hd-18-#.XW5lqShKiHs

**Comment by 717g301github** [comment]
Maybe yes, then it is working better now.

**Comment by 717g301github** [comment]
> I would also like to have a place to upload a Open Graph image for my home page. and to add it to the Header of the home page so when people shares the site they will get a preview of it just like the video thumbs.

Maybe you can just change the main page template, if such exists.

**Comment by JoshWho** [comment]
> @717g301github please try now
> 
> @JoshWho do you mean for global usage? for example when sharing a page without any video?
> it supposes to show your site logo correct?

Yeah for a default OG / Twittercard for pages with no vids or home page.
