### ISSUE TITLE
Password for users created by an OAuth Integration plugin is not strong

### ISSUE THREAD

**Issue by pastakhov** [YouPHPTube/YouPHPTube#2003]
https://github.com/YouPHPTube/YouPHPTube/blob/453189fd21d2df74f4217053509cf8e5c7550be3/objects/user.php#L1122

it looks like it is possible to brute force users password if account was created by any OAuth Integration plugin.

Am I right?

**Comment by DanielnetoDotCom** [comment]
I do not think so

**Comment by pastakhov** [comment]
please set minimum value at least, in other case it can return `123` or even `1`

**Comment by DanielnetoDotCom** [comment]
even better now.
