### ISSUE TITLE
BulkEmbed plugin

### ISSUE THREAD

**Issue by soapstreams** [YouPHPTube/YouPHPTube#2006]
What does the BulkEmbed plugin do? Will it allow users to embed youtube playlists, for example? Thanks.

**Comment by akhilleusuggo** [comment]
type the link from youtube and select what you want to embed.

**Comment by JoshWho** [comment]
Bulk Uploader is kinda like how a Wordpress Video Poster plugin works.You search for a term on YouTube and then it finds hundreds of pages of videos. You select some or all and click Embed and it will do it all for you.
