### ISSUE TITLE
HLS and VideoThumbnails plugin compatibility

### ISSUE THREAD

**Issue by soapstreams** [YouPHPTube/YouPHPTube#2007]
Is there a known problem getting the video thumbnails plugin to work with HLS videos? When the cursor hovers on the video play line for most of the videos, I see a time stamp and a still image from the video related that time. But with the new HLS videos, the time stamp is there, but there is no still image, just a brown background.

I sure hope this isn't an issue that can't be resolved because the HLS videos play much quicker than the other videos. They seem to take longer to encode, but respond much faster once live on the site. Thanks.

**Comment by DanielnetoDotCom** [comment]
HLS works fine with VideoThumbnails 

try to delete the generated thumbs and try again.

![image](https://user-images.githubusercontent.com/18009293/64172593-b1001900-ce2b-11e9-8ba5-8b20e19fda2c.png)


in case it fails again, please share your log files.

**Comment by soapstreams** [comment]
I have deleted the thumbnails and went through the videos again. Same problem, though. All I get is a brown background, that's it. Any other ideas?

**Comment by akhilleusuggo** [comment]
@soapstreams How much videos do you have hosted ? The encoder need a bit of time to make all the thumbnails working .

**Comment by soapstreams** [comment]
I just uploaded 20, so I guess that makes it about 40 or 50 total so far.

**Comment by DanielnetoDotCom** [comment]
@soapstreams I just found this bug, it is due to the security, there is nothing to do with the HLS

I am investigating to fix and I will release an update soon

**Comment by DanielnetoDotCom** [comment]
I guess it is fixed now, please try again.

Also your site is updated

**Comment by soapstreams** [comment]
Did you do anything to the encoders for that fix? Because I can't upload anything now. And the thumbnails only work on some videos. I will be happy to delete everything and reupload it all, but I can't get it to upload anymore.

**Comment by soapstreams** [comment]
Did you do anything to the encoders for that fix? Because I can't upload anything now. And the thumbnails only work on some videos. I will be happy to delete everything and reupload it all, but I can't get it to upload anymore.

**Comment by soapstreams** [comment]
For the encoder I sent the last video to, I show the max file size for both the streamer and the encoder to be 6 GB:

![image](https://user-images.githubusercontent.com/43099662/64902952-6c1f8200-d676-11e9-9d97-df9073b7c96e.png)

The video file I attempted to upload (after multiple others failed as well) to encoder.soappirat.es is still at https://soappirat.es/video/santa-barbara-ep-1-m073084. The file was uploaded on 9/12. Here is the log readout from encoder.soappirat.es:

![image](https://user-images.githubusercontent.com/43099662/64902988-e7813380-d676-11e9-99f7-acf75a617d7e.png)

I can't make heads or tails of this.

**Comment by DanielnetoDotCom** [comment]
I am not sure.

can you check it the 88_tmpFile_converted.zip exists? what size is it?

![image](https://user-images.githubusercontent.com/18009293/64955164-e3633a80-d85d-11e9-9319-c5a273bf7074.png)

also do you know what encoder does it sending the file? so I can take a deeper look into the encoder?

**Comment by soapstreams** [comment]
It is sending it to encoder.soappirat.es as opposed to encoder1 or 2 or 3. It is on the storage server (5.79.81.131).

**Comment by soapstreams** [comment]
But all 4 encoders are doing the same thing.

**Comment by soapstreams** [comment]
The file is in that directory:

![image](https://user-images.githubusercontent.com/43099662/64958975-d2163000-d855-11e9-9ce4-f04adff0595f.png)

**Comment by DanielnetoDotCom** [comment]
cam you please confirm me if it happens with any file size or only with large files?

**Comment by soapstreams** [comment]
You have already uploaded a smaller file through that encoder and said it works fine. All of these encoders were working prior to the fix regarding HLS/thumbnail compatibility. Bow none of the encoders will work with the same files that encoded fine before

**Comment by DanielnetoDotCom** [comment]
but there is no clue what is happening, I need to collect some clue

If you want you can share with me the file that is rising the error I can test it from my side.

**Comment by soapstreams** [comment]
Try this link to the video from my shared google drive:

https://drive.google.com/file/d/1mVoakFHBEXy2G7X18UwTB8yjlMMZWZSm/view?usp=drivesdk

**Comment by DanielnetoDotCom** [comment]
Hi, I only install zip on the encoder server and seems to be working now, can you please test it again? 

please use the encoder.soappirat.es

**Comment by soapstreams** [comment]
Ok. I have that one working now, but when I try to edit the video info, I get the following error:

"Sorry! Directory /var/www/html/YouPHPTube/objects/htmlpurifier/HTMLPurifier/DefinitionCache/Serializer not writable, please chmod to 777"

I tried to chmod that directory, but it says there is no such file or directory.

**Comment by DanielnetoDotCom** [comment]
are you sure it does not exists?

I am pretty sure you missed something

**Comment by soapstreams** [comment]
That directory doesn't exist:

![image](https://user-images.githubusercontent.com/43099662/65047747-99935680-d928-11e9-9074-b70e4a0b56de.png)

**Comment by DanielnetoDotCom** [comment]
So you did not copy/update your code correctly

this directory exists in the main branch
https://github.com/YouPHPTube/YouPHPTube/tree/master/objects/htmlpurifier/HTMLPurifier

**Comment by soapstreams** [comment]
What do you mean? I didn't copy or update any code at all, correct or otherwise. To what are you referring? I copied the error message, is that what you mean?

**Comment by DanielnetoDotCom** [comment]
I mean, or you did not clone the files correctly or you are looking into the wrong server.

I guess you are managing too many servers, and you are looking into the wrong one.

this directory is inside the streamer server

**Comment by soapstreams** [comment]
Got ya. I CHMOD'ed the directory on the streamer server instead of the encoder server and there it was. Poof! Like magic!

I am closing this out, oh merciful Heaven.
