### ISSUE TITLE
TinyMCE trying to load premium plugins

### ISSUE THREAD

**Issue by patriclougheed** [YouPHPTube/YouPHPTube#2009]
The video manager editor tries to load all the premium plugins that are not included: 
tinymce.min.js:9 GET /view/js/tinymce/plugins/powerpaste/plugin.min.js net::ERR_ABORTED 404
tinymce.min.js:9 GET /view/js/tinymce/plugins/advcode/plugin.min.js net::ERR_ABORTED 404
tinymce.min.js:9 GET /view/js/tinymce/plugins/mediaembed/plugin.min.js net::ERR_ABORTED 404
tinymce.min.js:9 GET /view/js/tinymce/plugins/tinymcespellchecker/plugin.min.js net::ERR_ABORTED 404
tinymce.min.js:9 GET /view/js/tinymce/plugins/a11ychecker/plugin.min.js net::ERR_ABORTED 404
tinymce.min.js:9 GET /view/js/tinymce/plugins/formatpainter/plugin.min.js net::ERR_ABORTED 404
tinymce.min.js:9 GET /view/js/tinymce/plugins/permanentpen/plugin.min.js net::ERR_ABORTED 404
tinymce.min.js:9 GET /view/js/tinymce/plugins/pageembed/plugin.min.js net::ERR_ABORTED 404
tinymce.min.js:9 GET /view/js/tinymce/plugins/tinycomments/plugin.min.js net::ERR_ABORTED 404
tinymce.min.js:9 GET /view/js/tinymce/plugins/mentions/plugin.min.js net::ERR_ABORTED 404
tinymce.min.js:9 GET /view/js/tinymce/plugins/linkchecker/plugin.min.js net::ERR_ABORTED 404

Changing it to:
`tinymce.init({
                                            selector: '#inputDescription', // change this value according to your HTML
                                            plugins: 'code print preview fullpage searchreplace autolink directionality visualblocks visualchars fullscreen image link media codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists wordcount imagetools textpattern help',
                                            //toolbar: 'fullscreen | formatselect | bold italic strikethrough forecolor backcolor | link image media pageembed | alignleft aligncenter alignright alignjustify | numlist bullist outdent indent | removeformat | addcomment',
                                            toolbar: 'fullscreen | formatselect | bold italic strikethrough | link image media pageembed | numlist bullist | removeformat | addcomment',`

Fixed the 404 errors

**Comment by DanielnetoDotCom** [comment]
thanks, try now
