### ISSUE TITLE
CDN for Videos Only

### ISSUE THREAD

**Issue by frq6692** [YouPHPTube/YouPHPTube#2010]
Hello
I found this help  [Cloudflare](https://github.com/YouPHPTube/YouPHPTube/wiki/Using-CDN-for-Videos-Only) CDN for video only. But this is not working now with YouPHPTube version 7.5.

I setup the same way as written in wiki

Even after this setup video upload to same site (not to CDN site).
But Player show error because video not found in CDN site directory (Here CDN setup work well). 
Please help how to fix it, that uploaded video go to CDN site directory

**Comment by DanielnetoDotCom** [comment]
I just checked and it is working on demo site.

may be something else.

check the .video URL is our CDN

![image](https://user-images.githubusercontent.com/18009293/64175444-ad6f9080-ce31-11e9-89a7-f996171ce89c.png)

**Comment by frq6692** [comment]
Thanks

I check demo sites working properly and also setup same way. But things not worked for me. Also 
Network tab showing wrong domain, I  think inserted CDN domain in plugin not updating there values in DB or files.

Please look here  (login credentials same as in demo)
http://streamer.imkd.in/   Front end site
http://streamer2.imkd.in/  Video CDN site

**Comment by DanielnetoDotCom** [comment]
Looks like you have 2 different sites. (different installations)

the domains should point to the same site/ installation

but one with a CDN active and the other one without CDN

**Comment by frq6692** [comment]
Thanks DanielnetoDotCom this worked for me
