### ISSUE TITLE
How to set up ad position as shown in the picture. I couldn't find any function to set it up like it did on demo.Youphptube.com

### ISSUE THREAD

**Issue by xemtube** [YouPHPTube/YouPHPTube#2011]
How to set up ad position as shown in the picture. I couldn't find any function to set it up like it did on demo.Youphptube.com

![image](https://user-images.githubusercontent.com/50126312/64157651-47026680-ce61-11e9-957d-87a8ff8fe899.png)

**Comment by DanielnetoDotCom** [comment]
Same as here https://github.com/YouPHPTube/YouPHPTube/issues/2001
