### ISSUE TITLE
 The LiveChat Plugin should be replaced with another more efficient plugin.

### ISSUE THREAD

**Issue by xemtube** [YouPHPTube/YouPHPTube#2015]
Currently the livechat plugin is not effective on Youphptube. You should replace another plugin more effectively (It has the function of blocking porn chat, inciting ...). Eg Rocket.Chat

**Comment by tiplovo** [comment]
Проще дописать пару строк кода ,на лимит сообщения и запрет на ввод символов ....хотя дело каждого

**Comment by DanielnetoDotCom** [comment]
Agree, I am building a chat now, but this will be a commercial plugin
