### ISSUE TITLE
Strong Server but My Stream freezes why

### ISSUE THREAD

**Issue by lamadya** [YouPHPTube/YouPHPTube#2016]
Hi 
My Stream freezes why
I have 2 high server but my stream Freezing after seconds
Server one on contabo 
CPU : 1-2 x Intel Xeon E5 2630v4 1-2 x (10 x 2.20 GHz)
RAM : 256 GB REG ECC
Port / bandwidth :  1 Gbit/s port UNLIMITED Traffic
Operating system : Ubuntu 16.04 
Using Your Tutorial For install YouPHPtube And NGINX RTMP 
Sent stream Via FFMPEG With Loop
Code Loop {
#!/bin/bash
while :; do
ffmpeg -re -i http://adtv.ercdn.net/adsport2/adsport2_720p.m3u8 -s hd720 -r 60 -g 60 -b:v 3M -c:v libx264 -x264-params keyint=60 -bufsize 500k -c:a aac -strict -2 -ar 44100 -b:a 128k -f flv rtmp://myipserver/live?p=4adc701664135e50b2354496086d53dd/5d70337586747 </dev/null > /dev/null 2>&1
done &
}

Server Two From a local distributor
RAM 16 GB
Processeur CPU 8 Cores / 8 Threads [Intel Atom™ 2,5 GHz]
Débit Internet 1 Gb/s (Garanti 700 Mb/s)
Operating system : Ubuntu 16.04 
Using Your Tutorial For install YouPHPtube And NGINX RTMP 
Sent stream Via FFMPEG With Loop
Code Loop {
#!/bin/bash
while :; do
ffmpeg -re -i http://adtv.ercdn.net/adsport2/adsport2_720p.m3u8 -s hd720 -r 60 -g 60 -b:v 3M -c:v libx264 -x264-params keyint=60 -bufsize 500k -c:a aac -strict -2 -ar 44100 -b:a 128k -f flv rtmp://myipserver/live?p=4adc701664135e50b2354496086d53dd/5d70337586747 </dev/null > /dev/null 2>&1
done &
}
This My Nginx Config http://lamadya.com/nginx.conf
But My Stream freezes why Please Help Me

**Comment by akhilleusuggo** [comment]
Maybe the actual problem is from the source you're linking ?

**Comment by lamadya** [comment]
the source stable without freezing, Even when using a video file video.mp4 get freezing

**Comment by akhilleusuggo** [comment]
@lamadya Ok , try this line : 
`ffmpeg -re -i VideoDir -vcodec libx264 -x264opts keyint=120:no-scenecut -s 1280x720 -movflags faststart -r 60 -preset ultrafast -b:v 6000k -profile:v main -sws_flags lanczos  -c:a aac -b:a 128k -ac 2 -ar 44100 -f flv rtmp://YOURSITE/live?p=Key/KEYStream -nostdin -nostats </dev/null >/dev/null 2>&1 &`

Leave a feedback , thanks

**Comment by lamadya** [comment]
Thanks for your reply but still freezes

**Comment by akhilleusuggo** [comment]
@lamadya Could you explain what do you mean with '' freezes '' ?
Packet loss ? It does stop every 5s or what exactly ? 
Do you think it's a hardware lack or a connection problem ? Not talking about your specs server , but something wrong on the script if you believe so

**Comment by lamadya** [comment]
You can check here and Thank you sir

**Comment by lamadya** [comment]
https://yallabeinhd.com/live/

**Comment by akhilleusuggo** [comment]
@lamadya For some reason I don't see anything freezing ... I'm sure with the ffmpeg line that I gave you , it should not freezes
