### ISSUE TITLE
Cannot successfully change db password

### ISSUE THREAD

**Issue by OhioVR** [YouPHPTube/YouPHPTube#2019]
Admin password can be changed via the provided php script. Thank you for that. And I can change the admin password for the encoder easily with an sql query. But I cannot change the mysql password for youphptube streamer. I have the right command to change the root password on mariadb, that works ok. But when I enter the password into configuration.php I get the site maintence error stating that my root password is wrong. If I change it back to the original that doesn't work either. I tried grepping for the original password string but couldn't find it anywhere but configuration.php

**Comment by akhilleusuggo** [comment]
1) clear the cache of the browser 
2)```
 sudo mysql
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'NEWPASSWORD';
```

**Comment by OhioVR** [comment]
Thank you and really fast reply too! The key issue was the mysql_native_password flag. I ended up using the following docker command in case someone is looking for a similar solution:

    sudo docker exec -i -u root "youphptube_mariadb_1" mysql -u root -p"${MYSQL_ROOT_PASSWORD}" -e "update mysql.user set plugin = 'mysql_native_password' where User='root'; UPDATE mysql.user SET plugin = 'mysql_native_password', Password = PASSWORD('${MYSQL_ROOT_PASSWORD}') WHERE User = 'root'; FLUSH PRIVILEGES;"
