### ISSUE TITLE
Add more than 1 new domain name for Youphptube.

### ISSUE THREAD

**Issue by xemtube** [YouPHPTube/YouPHPTube#2022]
Currently I have added a new domain name XemTube.TV for Youphptube to work in parallel with the current domain name. But when I access the new domain name XemTube.TV, it automatically switches back to the main domain name XemTube.Online.

Set youphptube.conf
`<VirtualHost *:80>
    DocumentRoot "/var/www/html/YouPHPTube"
    ServerName xemtube.online
    ServerAlias www.xemtube.online
    ServerAlias xemclip.online
    ServerAlias www.xemclip.online
    ServerAlias xemtube.tv
    ServerAlias www.xemtube.tv
    ServerAdmin webmaster@localhost
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
RewriteEngine on
RewriteCond %{SERVER_NAME} =www.xemtube.tv [OR]
RewriteCond %{SERVER_NAME} =xemtube.tv [OR]
RewriteCond %{SERVER_NAME} =www.xemclip.online [OR]
RewriteCond %{SERVER_NAME} =xemclip.online [OR]
RewriteCond %{SERVER_NAME} =xemtube.online [OR]
RewriteCond %{SERVER_NAME} =www.xemtube.online
RewriteRule ^ https://xemtube.online%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
`
How to set up the same domain name works in parallel on a website.

Thank you !

**Comment by DanielnetoDotCom** [comment]
You may need to create another vhost 

be careful on change this file because you may mess up with the ssl configuration.

**Comment by xemtube** [comment]
I have just sent you an email to support this issue. Please check your mail and support me. Thanks a lot !
