### ISSUE TITLE
twitter widget plugin request please

### ISSUE THREAD

**Issue by joey2354** [YouPHPTube/YouPHPTube#2024]
Hi

Could someone please make a twitter widget plugin feed for members profile page please ?

So when they post to twitter it will send an rss feed to a widget to their profile page live.

thank you
i have money .............

**Comment by DanielnetoDotCom** [comment]
Hi,

 @joey2354 can you please give an example what are you expecting?

this is not clear for me

**Comment by joey2354** [comment]
https://publish.twitter.com/#


like this, so they add their @username and a widget appears on their profile page or next to their videos

**Comment by JoshWho** [comment]
I think he is asking for something that auto sendicates to Twitter as soon as they go live. This would have to work with Rss Feeds. You can create a app at IFTTT and setup a trigger to auto tweet as soon as you go live.  What you included as a trigger is what gets selected.

**Comment by joey2354** [comment]
It doesn't matter about this sorry now, I've changed my mind, might slow my site down too much.


thank you anyways
