### ISSUE TITLE
How to fix "No compatible source found for this media" ?

### ISSUE THREAD

**Issue by TTcam** [YouPHPTube/YouPHPTube#2027]
After adding the YouTube link “Insert Video Link” the first playback is normal. If you reload the “No compatible source found for this media” page. Heals only Ctrl + F5. How to fix?

**Comment by TTcam** [comment]
In Chrome, Opera and others. Plugin "Cache" disabled

**Comment by xemtube** [comment]
Please check off the Chromecast Plugin and try again

![image](https://user-images.githubusercontent.com/50126312/64488393-a0a7ce00-d271-11e9-8e76-248cdc40f360.png)

**Comment by TTcam** [comment]
Thank. It helped
