### ISSUE TITLE
 No Chat2 Plugin found anywhere.

### ISSUE THREAD

**Issue by XemTube-TV** [YouPHPTube/YouPHPTube#2031]
Chat 2 plugin is free or paid. Because I did not find it here https://www.youphptube.com/plugins/

**Comment by XemTube-TV** [comment]
It has been updated information here https://github.com/YouPHPTube/YouPHPTube/wiki/Chat2-Plugin. Demo.YouPhptube also has this Plugin. I think I have to wait that long

**Comment by DanielnetoDotCom** [comment]
Hi, I am working to finish the Chat, it is on Beta version now, that is why it is on demo site.

Soon it will be on the store.


I appreciate your feedback if I am missing something

**Comment by tiplovo** [comment]
Super
