### ISSUE TITLE
Video Upload Not Working ( Encoder )

### ISSUE THREAD

**Issue by akhilleusuggo** [YouPHPTube/YouPHPTube#2032]
I've been trying to upload videos to the encoder already 3 days , and I've tried everything to make it works , but it doesn't . I'm getting this error : 

`PHP Warning:  rename(/var/www/html/YouPHPTube-Encoder/videos/chunk/3/test 2018.04.11 - 20.57.18.04.mp4,/var/www/html/YouPHPTube-Encoder/videos/original_test2018041120571804_YPTuniqid_5d7c460291fca1.72485886): No such file or directory in /var/www/html/YouPHPTube-Encoder/view/upload.php on line 34
`
And finally I have found out what was causing the problem . The name of the file was not accepted . Basically if having numbers or SPACES , looks like need the \ to indicate that there's a space otherwise FFmpeg will not recognize it  . That happens to me when I try to encode a video that's having spaces on the name .

Any fix for this without renaming the file to very short names and without spaces  ?
Thanks

**Comment by JoshWho** [comment]
Should be a way to Sanitize the title from all symbols quotes and slashes. I mentioned this a while ago. So far I just tell everyone to make sure the title doesn't have quotes and symbols and slashes.

**Comment by JoshWho** [comment]
> I've been trying to upload videos to the encoder already 3 days , and I've tried everything to make it works , but it doesn't . I'm getting this error :
> 
> `PHP Warning: rename(/var/www/html/YouPHPTube-Encoder/videos/chunk/3/test 2018.04.11 - 20.57.18.04.mp4,/var/www/html/YouPHPTube-Encoder/videos/original_test2018041120571804_YPTuniqid_5d7c460291fca1.72485886): No such file or directory in /var/www/html/YouPHPTube-Encoder/view/upload.php on line 34 `
> And finally I have found out what was causing the problem . The name of the file was not accepted . Basically if having numbers or SPACES , looks like need the \ to indicate that there's a space otherwise FFmpeg will not recognize it . That happens to me when I try to encode a video that's having spaces on the name .
> 
> Any fix for this without renaming the file to very short names and without spaces ?
> Thanks

What version of PHP are you using?
Also is your .htaccess functioning correctly and Urls all working good?

**Comment by akhilleusuggo** [comment]
yeh , the site works perfectly . PHP 7.2 ( ubtuntu 18.04 )

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo I am pretty sure I sent a fix for this couple of weeks ago.

can you please update your encoder and check it?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Fixed , thanks
