### ISSUE TITLE
Encoder fail to download some videos

### ISSUE THREAD

**Issue by Elfanar** [YouPHPTube/YouPHPTube#2035]
Hi,

I've setup the encoder as subfolder for my youphptube installation.
While some videos are working just fine, some are not working with me, I get this :
Sorry!
We could not get the title of your video (https://www.youtube.com/watch?v=zhJDqLPFR78) go to Update your Youtube-DL to fix it.

Using the public encoder, things are working just fine, and I am pretty sure my youtube-dl is the latest, I tried sudo pip install --upgrade youtube-dl and all, I don't have any error messages at enc/videos/youphptube.log . It seems like a bug to me.
![Screenshot from 2019-09-15 11-35-42](https://user-images.githubusercontent.com/37922869/64919105-b3f5f480-d7af-11e9-957e-b3b8dc6fb5fc.png)

**Comment by akhilleusuggo** [comment]
You're banned for some hours from YouPHPTube . You can visit the youtube-dl community and ask them about this . If you're still wondering if this is a bug , try to download a video from youtube with the youtube-dl and you'll get at error . That error it's a temporary ban from youtube ( for doing too much requests )

**Comment by Elfanar** [comment]
> You're banned for some hours from YouPHPTube . You can visit the youtube-dl community and ask them about this . If you're still wondering if this is a bug , try to download a video from youtube with the youtube-dl and you'll get at error . That error it's a temporary ban from youtube ( for doing too much requests )

You mean I was banned from youtube.com for excessive downloading ? this is not true, I can download the same video from server's command line (bash youtube-dl), and also I can download other videos using same encoder setup, just NOT this video, I think it is encoder bug but nothing at logs shows any information.

**Comment by akhilleusuggo** [comment]
This makes nonsense to me . ( a bug for one video lol )

**Comment by Elfanar** [comment]
not one video at all, some videos working and some are not, I just gave you an example.
