### ISSUE TITLE
Dynamic Copyright Year Code

### ISSUE THREAD

**Issue by soapstreams** [YouPHPTube/YouPHPTube#2037]
I asked about this a while back and was told there was no "smarty" code or something similar to use to automatically update the year in the footer, but I did find javascript code that I got to work, in case anyone is interested:

Activate the CustomizeAdvanced plugin, click on "Edit Parameters" and scroll down to "footerHTMLCode." Paste the following into the textbox:

```
<footer>

<p>&copy Copyright 
  <script type="text/javascript">
   "var today = new Date()
   "var year = today.getFullYear()
   "document.write(year)
  </script>
<a href="https://yoursite.com">Your Site</a>
</p>

</footer>
```

**Comment by soapstreams** [comment]
It insert a space after the year and I want a comma after. Anyone know how to add a comma to the document.write command?

**Comment by DanielnetoDotCom** [comment]
That is a good solution. :)
