### ISSUE TITLE
FEATURE REQUEST - Live Stream to show on Users Channel Page.

### ISSUE THREAD

**Issue by JoshWho** [YouPHPTube/YouPHPTube#2045]
Would be really kewl if when a user goes live it shows on their channel page.

A lot of my users look for it there and get confused.

**Comment by tiplovo** [comment]
Плеер встройте в страницу с потока

**Comment by JoshWho** [comment]
> Плеер встройте в страницу с потока

Я бы предпочел, чтобы его можно было воспроизвести на странице канала, где появляется большое видео. Было бы очень здорово увидеть это там.

**Comment by tiplovo** [comment]
За место этого плеера встройте плеер с потока и динамически ключь подставьте ,чтоб поток соответсвовал каналу пользователя

**Comment by JoshWho** [comment]
> За место этого плеера встройте плеер с потока и динамически ключь подставьте ,чтоб поток соответсвовал каналу пользователя

TRANSLATED: For the place of this player, mount the player from the stream and dynamically substitute the key so that the stream matches the user channel

**Comment by tiplovo** [comment]
Да правильно
