### ISSUE TITLE
Donation link

### ISSUE THREAD

**Issue by mikweb2017** [YouPHPTube/YouPHPTube#2048]
how to  work  for Donation Link.
Do you need some extra plugins or how to configure them?
![Bildschirmfoto 2019-09-19 um 22 08 28](https://user-images.githubusercontent.com/30271757/65277439-307b3100-db2a-11e9-8d0e-39be6cd1b504.png)

**Comment by DanielnetoDotCom** [comment]
Hi, just update to the latest YouPHPTube version 7.6

Enable it here 
![image](https://user-images.githubusercontent.com/18009293/65280434-b5545380-db06-11e9-89f1-d1e0976af026.png)

then in my account, you will see ...

![image](https://user-images.githubusercontent.com/18009293/65280474-d452e580-db06-11e9-8788-fd692fb702a8.png)

**Comment by mikweb2017** [comment]
ok thanks
