### ISSUE TITLE
how to move youphptube for root folder

### ISSUE THREAD

**Issue by sandrecardoso** [YouPHPTube/YouPHPTube#2051]
how to move youphptube to root folder I installed it and it looked like this:
https://tiosamcomunity.tk/YouPHPTube stayed as a subdomain

**Comment by maxlinux2000** [comment]
it is not necessary to change the installation site. Simply modify the file /etc/apache2/sites-avalaibles/tiosamcomunity.tk like this:

<VirtualHost *:80>
    DocumentRoot "/var/www/html/YouPHPTube"
    ServerName tiosamcomunity.tk
    # Other directives here
</VirtualHost>
<VirtualHost *:443>
    DocumentRoot "/var/www/html/YouPHPTube"
    ServerName tiosamcomunity.tk
    # Other directives here
</VirtualHost>

probably you need to modify only the DocumentRoot directive

**Comment by sandrecardoso** [comment]
thank you so much i did it and then i restarted apache and it worked
