### ISSUE TITLE
Returning errors are rapidly  filling my log file 

### ISSUE THREAD

**Issue by ustoopia** [YouPHPTube/YouPHPTube#2052]
Hi all,
I'm seeing the same errors over and over again in the log file. This error is logged so many times that it will create a 25MB log files in no-time. Below are the three error messages and below this I will paste the part of the Live.php file that the error is pointing to.

```
PHP Warning:  simplexml_load_string(): Entity: line 6: parser error : Opening and ending tag mismatch: hr line 5 and body in /var/www/web8/web/plugin/Live/Live.php on line 95
PHP Warning:  simplexml_load_string(): &lt;/body&gt; in /var/www/web8/web/plugin/Live/Live.php on line 95
PHP Warning:  simplexml_load_string():        ^ in /var/www/web8/web/plugin/Live/Live.php on line 95
PHP Warning:  simplexml_load_string(): Entity: line 7: parser error : Opening and ending tag mismatch: body line 3 and html in /var/www/web8/web/plugin/Live/Live.php on line 95
PHP Warning:  simplexml_load_string(): &lt;/html&gt; in /var/www/web8/web/plugin/Live/Live.php on line 95
PHP Warning:  simplexml_load_string():        ^ in /var/www/web8/web/plugin/Live/Live.php on line 95
PHP Warning:  simplexml_load_string(): Entity: line 8: parser error : Premature end of data in tag html line 1 in /var/www/web8/web/plugin/Live/Live.php on line 95
PHP Warning:  simplexml_load_string():  in /var/www/web8/web/plugin/Live/Live.php on line 95
PHP Warning:  simplexml_load_string(): ^ in /var/www/web8/web/plugin/Live/Live.php on line 95
```

All these errors are related to line 95 in Live.php as shown below.

```
93    function getStatsObject() {
94        ini_set('allow_url_fopen ', 'ON');
95        $xml = simplexml_load_string($this->get_data($this->getStatsURL()));
96        return $xml;
97    }
```

The site works without any noticeable issues. But it's pretty annoying that my log file grows so fast. This makes it difficult to open to view it. So if anybody has any clue what's causing the error, I would be very grateful.

**Comment by DanielnetoDotCom** [comment]
@ustoopia I am pretty sure you are using an old version.

first, try to update your code

**Comment by ustoopia** [comment]
You're absolutely right. I was actually several versions behind. I performed all the updates 1 by 1 and I will keep an eye on the log file to see if this indeed resolved the issue. Thank you very much for the help.
