### ISSUE TITLE
can't git pull

### ISSUE THREAD

**Issue by akhilleusuggo** [YouPHPTube/YouPHPTube#2064]
/var/www/html/YouPHPTube# git pull
Updating b58b912e..17688490
error: Your local changes to the following files would be overwritten by merge:
        locale/function.php
        objects/functions.php
        objects/logoff.php
        objects/video.php
        plugin/Articles/Articles.php
        plugin/CustomizeUser/CustomizeUser.php
        plugin/CustomizeUser/actionButton.php
        plugin/YPTWallet/plugins/YPTWalletStripe/confirmButton.php
        plugin/YPTWallet/plugins/YPTWalletStripe/confirmRecurrentButton.php
        plugin/YouPHPFlix2/view/css/style.css
        view/modeYoutube.php
Please commit your changes or stash them before you merge.
Aborting

**Comment by DanielnetoDotCom** [comment]
You can overwrite your changes sudo git fetch --all && sudo git reset --hard origin/master

**Comment by akhilleusuggo** [comment]
ok , now the site is not working xD

**Comment by DanielnetoDotCom** [comment]
is it working or not?

**Comment by akhilleusuggo** [comment]
Working fine , yes Sr
