### ISSUE TITLE
Error: managerCategories_body

### ISSUE THREAD

**Issue by abelhongo1983** [YouPHPTube/YouPHPTube#2067]
Hello again, on the view / managerCategories_body.php page on the line:

<th data-column-id="commands" data-formatter="commands" data-sortable="false"></th>

The "commands" text is required

so:

<th data-column-id="commands" data-formatter="commands" data-sortable="false"><?php echo __("Commands"); ?></th>

$t['Commands'] = "Comandos";

**Comment by abelhongo1983** [comment]
Hi, I'm sorry my English is not very good.

On the page: view/managerCategories_body.php

The text $t['Commands'] is required 
************************************************
<th data-column-id = "commands" data-formatter = "commands" data-sortable = "false"> <? php echo __ ("Commands"); ?> </th>
************************************************
so that the column filter does not go blank is not an error is an observation


And in Spanish Commands = Comandos

**Comment by DanielnetoDotCom** [comment]
Hi, in case the $t['Commands']  does not exist it will write Command

so it is not required, but this is the way to create translations.
