### ISSUE TITLE
AWS s3 Plugin not working 

### ISSUE THREAD

**Issue by forsmartworld** [YouPHPTube/YouPHPTube#2071]
Hello i can't make AWS s3 plugin work i'm runnig script on AWS EC2 instance with ubuntu 18.04 .

![AWS s3 error](https://user-images.githubusercontent.com/42339163/65513166-6d0cab00-dee3-11e9-859d-535bdaabe850.jpg)
I did follow up all instructions on git, still not manage to make it work

**Comment by DanielnetoDotCom** [comment]
Hi, 

how is your bucket screen?

I would like to compare your credentials and names

**Comment by DanielnetoDotCom** [comment]
also if you can check your log file, it may give you some clue.

**Comment by forsmartworld** [comment]
![image](https://user-images.githubusercontent.com/42339163/65513517-0d62cf80-dee4-11e9-9efb-ea2b57d1fb8b.png)

**Comment by forsmartworld** [comment]
![log youphptube](https://user-images.githubusercontent.com/42339163/65514057-2e77f000-dee5-11e9-926b-f18540a05567.jpg)
 

![image](https://user-images.githubusercontent.com/42339163/65514149-6c751400-dee5-11e9-814d-b36828b7a4fe.png)

**Comment by forsmartworld** [comment]
i will kill instance and reinstall plugin

**Comment by forsmartworld** [comment]
i have to delete only mp.4 and not gifs? from sistem videos folder?

**Comment by DanielnetoDotCom** [comment]
DO NOT remove the videos directory from the system

check your videos directory has only videos with a size of 10 bytes, they are dumb files but it is necessary to keep it working.

**Comment by forsmartworld** [comment]
ok thank you great support. i will close this issue
