### ISSUE TITLE
ffmpeg too many threads !!

### ISSUE THREAD

**Issue by maxlinux2000** [YouPHPTube/YouPHPTube#2072]
Hello
I am encoding a video and watching the processes with htop.
It turns out that of ffmpeg there are about 20 or more and my cpu only has 4 cores.

Is there a way to limit the number of threads to something more manageable?

![Captura de pantalla de 2019-09-24 16-53-02](https://user-images.githubusercontent.com/5683921/65523406-8403cb00-deec-11e9-990d-46c331059449.png)
![Captura de pantalla de 2019-09-24 16-53-45](https://user-images.githubusercontent.com/5683921/65523407-8403cb00-deec-11e9-87a5-e49791ec465f.png)

**Comment by DanielnetoDotCom** [comment]
google for the ffmpeg -thread, this way you can limit the cores

you will need to be able to access the configuration tab

![image](https://user-images.githubusercontent.com/18009293/65534893-ac80ca80-ded6-11e9-940c-a378c128a14d.png)

In case you can not see this tab, check this...

https://github.com/YouPHPTube/YouPHPTube-Encoder/issues/145

**Comment by maxlinux2000** [comment]
Tnx,
I think this link is good :)
https://superuser.com/questions/792525/how-to-change-ffmpeg-threads-settings

**Comment by maxlinux2000** [comment]
ok now is much better!

with a little allwinner ARM64 H5 (4 core) the best option is:

ffmpeg -threads 4 -i /var/www/html/You.....

regards
MaX
