### ISSUE TITLE
livestream configured but it is not working

### ISSUE THREAD

**Issue by Ibrahimera** [YouPHPTube/YouPHPTube#2073]
I followed step by step to set up stream
 https://github.com/YouPHPTube/YouPHPTube/wiki/Set-up-my-own-Stream-Server

here is my live page

![livepage](https://user-images.githubusercontent.com/51007186/65544868-73257a80-df29-11e9-965f-33c99a9af86f.jpg)

here is the error on my OBS 

![obserror](https://user-images.githubusercontent.com/51007186/65542417-62263a80-df24-11e9-9419-d992ba1a1e75.jpg)

button parameters

{"button_title":"LIVE","server":"rtmp://34.70.144.189/live","playerServer":"http://34.70.144.189:8080/live","stats":"http://34.70.144.189:8080/stat","disableDVR":false,"disableGifThumbs":false,"useAadaptiveMode":false,"experimentalWebcam":false}

here is my nginx.conf file

    worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://34.70.144.189/plugin/Live/on_publish.php;
                            on_play http://34.70.144.189/plugin/Live/on_play.php;
                            on_record_done http://34.70.144.189/plugin/Live/on_record_done.php;
                    }
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    server_name localhost;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';
                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';
                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-                     
                     ip/stats"
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }
            }
    }

Here is my state

![state](https://user-images.githubusercontent.com/51007186/65543338-3b690380-df26-11e9-84ec-83b97954765b.jpg)

i don't know what is wrong with it

**Comment by akhilleusuggo** [comment]
You config is weired , you have duplicated parts . Like this one `on_publish http://mydomain/plugin/Live/on_publish.php;` and `on_publish http://mydomain/plugin/Live/on_publish.php;`

Everything is duplicated I would say

**Comment by Ibrahimera** [comment]
when i coppied from the nginx.conf i didn't notice that i coppied some part twice and paste here it is not duplicate in nginx.conf file

**Comment by Ibrahimera** [comment]
I got this in my nginx/logs/error.log every time i try to stream,

2019/09/24 22:29:26 [error] 30524#0: *277 open() "/HLS/live/5d8940af1db7a/index.m3u8" failed (2: No such file or directory), client: client_ip, server: localhost, request:$
2019/09/24 22:29:37 [info] 30524#0: *280 client closed connection while waiting for request, client: client_ip, server: 0.0.0.0:8080

**Comment by akhilleusuggo** [comment]
just delete all and copypast again witht he right information

**Comment by Ibrahimera** [comment]
I did, i updated, everything is the right information now

**Comment by akhilleusuggo** [comment]
Does it work ?

**Comment by Ibrahimera** [comment]
i think you misunderstood, i said i pasted some part twice here in the issue on github from nginx.conf file, in my nginx.conf file nothing is duplicate,   i just changed these lines nothing else

 on_publish http://34.70.144.189/plugin/Live/on_publish.php;
                        on_play http://34.70.144.189/plugin/Live/on_play.php;
                        on_record_done http://34.70.144.189/plugin/Live/on_record_done.php;

I reinstalled several times, every time i have this problem that i asked here.

**Comment by DanielnetoDotCom** [comment]
Does this directory exists?
`
/HLS/live/`

does it have permission to write?

**Comment by Ibrahimera** [comment]
Yes the Directory /HLS/live/ exist and the permission for the /HLS/live/  is drwxrwxrwx

**Comment by DanielnetoDotCom** [comment]
Place here your NGINX.conf and your live plugin parameters screenshot

**Comment by Ibrahimera** [comment]
worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://34.70.144.189/plugin/Live/on_publish.php;
                            on_play http://34.70.144.189/plugin/Live/on_play.php;
                            on_record_done http://34.70.144.189/plugin/Live/on_record_done.php;
                    }
            }
    }

    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    server_name localhost;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';
                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';
                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }
            }
    }


![liveparameters](https://user-images.githubusercontent.com/51007186/65805756-15e52f80-e19c-11e9-9b01-3093bbd1eb2d.jpg)

**Comment by DanielnetoDotCom** [comment]
make sure the /HLS/live directory exists and have write permissions (You show only the /HLS in your screenshot)

**Comment by Ibrahimera** [comment]
thank you guys for your help  i found the problem, it is because the firewalls block the port 1935. I opened it, and now it is working
as the OBS alert said ( make sure no firewall blocking the connection)

**Comment by maxlinux2000** [comment]
Hello,

I am trying to setup the live steam, following this document:
https://github.com/YouPHPTube/YouPHPTube/wiki/Set-up-my-own-Stream-Server

But it doesn't work for me, so I have some doubts:

1) Since in the tutorial they talk about compiling the nginx rtmp module, I suppose that you also have to install nginx. How? with "sudo apt install nginx"?
... but this module is installed in /usr/local/nginx/
How do I make nginx use this module?
Or do I have to compile nginx also in /usr/local/nginx ?

2) In the tutorial there is no talk of installing nginx, but there is a comment about changing port 80 to 8080, so I have isntalled it with apt-get.
It refers to changing the configuration file in /etc/nginx/sites-available/default in:

server {
        listen 80 default_server;
        listen [::]: 80 default_server;

to

server {
        listen 8080 default_server;
        listen [::]: 8080 default_server;

???

3) I have the ufw disabled and I have launched nginx and it is active on port 8080.
But port 1935 is off .... I guess nginx is not using the nginx rtmp module, or it could be something else.


all help is grateful, 
thanks
