### ISSUE TITLE
video upload error 

### ISSUE THREAD

**Issue by gujarraju** [YouPHPTube/YouPHPTube#2081]
Dear Mr. Daniel

Today i update after that getting error.

Sorry!

Your video has NOT been saved!

**Comment by DanielnetoDotCom** [comment]
Check your log file

**Comment by gujarraju** [comment]
[0] => Array
        (
            [file] => /var/www/html/YouPHPTube/objects/mysql_dal.php
            [line] => 85
            [function] => log_error
            [args] => Array
                (
                    [0] => [sqlDAL::writeSql] Prepare failed: (1054) Unknown column 'serie_playlists_id' in 'field list'<br>
INSERT INTO videos (title,clean_title, filename, users_id, categories_id, status, description, duration,type,videoDownloadedLink, next_videos_id, created, modified, videoLink, can_download, can_share, only_for_paid, rrating, externalOptions, sites_id, serie_playlists_id) values ('Srinivasa Kalyanam New Released Full HD Hindi Dubbed Movie 2019| Nithiin,Rashi khanna,Nandita swetha','srinivasa-kalyanam-new-released-full-hd-hindi-dubbed-movie-2019-nithiin-rashi-khanna-nandita-swetha', '_YPTuniqid_5d8da7dc703730.07618579', 1,2, 'a', '\n\n', '02:00:47', 'embed', '', NULL,now(), now(), 'https://www.youtube.com/watch?v=VeoiEqdkKAk', '0', '0','0', '', '{"videoStartSeconds":"00:00:00"}', NULL, NULL)
                )

        )

    [1] => Array
        (
            [file] => /var/www/html/YouPHPTube/objects/video.php
            [line] => 262
            [function] => writeSql
            [class] => sqlDAL
            [type] => ::
            [args] => Array
                (
                    [0] => INSERT INTO videos (title,clean_title, filename, users_id, categories_id, status, description, duration,type,videoDownloadedLink, next_videos_id, created, modified, videoLink, can_download, can_share, only_for_paid, rrating, externalOptions, sites_id, serie_playlists_id) values ('Srinivasa Kalyanam New Released Full HD Hindi Dubbed Movie 2019| Nithiin,Rashi khanna,Nandita swetha','srinivasa-kalyanam-new-released-full-hd-hindi-dubbed-movie-2019-nithiin-rashi-khanna-nandita-swetha', '_YPTuniqid_5d8da7dc703730.07618579', 1,2, 'a', '\n\n', '02:00:47', 'embed', '', NULL,now(), now(), 'https://www.youtube.com/watch?v=VeoiEqdkKAk', '0', '0','0', '', '{"videoStartSeconds":"00:00:00"}', NULL, NULL)
                )

        )

    [2] => Array
        (
            [file] => /var/www/html/YouPHPTube/objects/videoAddNew.json.php
            [line] => 104
            [function] => save
            [class] => Video
            [object] => Video Object
                (
                    [id:Video:private] => 
                    [title:Video:private] => Srinivasa Kalyanam New Released Full HD Hindi Dubbed Movie 2019| Nithiin,Rashi khanna,Nandita swetha
                    [clean_title:Video:private] => srinivasa-kalyanam-new-released-full-hd-hindi-dubbed-movie-2019-nithiin-rashi-khanna-nandita-swetha
                    [filename:Video:private] => _YPTuniqid_5d8da7dc703730.07618579
                    [description:Video:private] => \n\n
                    [views_count:Video:private] => 
                    [status:Video:private] => a
                    [duration:Video:private] => 02:00:47
                    [users_id:Video:private] => 1
                    [categories_id:Video:private] => 2
                    [old_categories_id:Video:private] => 
                    [type:Video:private] => embed
                    [rotation:Video:private] => 0
                    [zoom:Video:private] => 1
                    [videoDownloadedLink:Video:private] => 
                    [videoLink:Video:private] => https://www.youtube.com/watch?v=VeoiEqdkKAk
                    [next_videos_id:Video:private] => NULL
                    [isSuggested:Video:private] => 0
                    [videoGroups:Video:private] => Array
                        (
                        )

                    [trailer1:Video:private] => 
                    [trailer2:Video:private] => 
                    [trailer3:Video:private] => 
                    [rate:Video:private] => 0
                    [can_download:Video:private] => 0
                    [can_share:Video:private] => 0
                    [only_for_paid:Video:private] => 0
                    [rrating:Video:private] => 
                    [externalOptions:Video:private] => {"videoStartSeconds":"00:00:00"}
                    [sites_id:Video:private] => NULL
                    [serie_playlists_id:Video:private] => NULL
                    [youtubeId:Video:private] => 
                )

            [type] => ->
            [args] => Array
                (
                    [0] => 1
                )

**Comment by DanielnetoDotCom** [comment]
OMG, it not suppose to be there yet, I will send a fix

**Comment by DanielnetoDotCom** [comment]
Please update and try now

**Comment by gujarraju** [comment]
Yes know ok
 Thanks
