### ISSUE TITLE
Why 3 encoding togheter?

### ISSUE THREAD

**Issue by maxlinux2000** [YouPHPTube/YouPHPTube#2083]
Today looking the encoder I found this:

![Captura de pantalla de 2019-09-27 18-32-42](https://user-images.githubusercontent.com/5683921/65785926-ced44b80-e155-11e9-9c01-2d5c7cff294d.png)

it's normal? 3 videos encoding together?

![Captura de pantalla de 2019-09-27 18-37-40](https://user-images.githubusercontent.com/5683921/65785978-f1fefb00-e155-11e9-9559-4af4c2dfc34f.png)

**Comment by DanielnetoDotCom** [comment]
To be honest I don't know, they are not supposed to do this

**Comment by maxlinux2000** [comment]
I will post here the logs?

**Comment by maxlinux2000** [comment]
[youphptube.zip](https://github.com/YouPHPTube/YouPHPTube/files/3663777/youphptube.zip)

Here yo have just in case.

**Comment by akhilleusuggo** [comment]
I use this trick to fast my encoding queue , by canceling the encods and re-starting them . I wish this would be possible like a plugin to tell ffmpeg how much queue at once were possible :(

**Comment by maxlinux2000** [comment]
....In fact the encoder has stopped it several times, and to restart
it, I have erased the whole queue and put it back again. I would like
to keep the delivery order because I was importing an entire YouTube
channel.
What I would like is to have a button to force the restart of a video
that for some reason has stopped or that I want to restart because I
have modified for example the ffmpeg impositions
