### ISSUE TITLE
Article Article error correction

### ISSUE THREAD

**Issue by XemTube-TV** [YouPHPTube/YouPHPTube#2088]
The Article plugin has 2 issues to fix:

1. Frame error when presenting in this form. 
![image](https://user-images.githubusercontent.com/50126312/65849226-a3c74300-e373-11e9-941f-258d6f5138a7.png)

Projection is the same as for Live Streaming

![image](https://user-images.githubusercontent.com/50126312/65849265-d5400e80-e373-11e9-9a5f-8cee2fed90ba.png)

2.  Allows adding Poster images on Article Article Plugin

**Comment by DanielnetoDotCom** [comment]
can you please share a link of the Article problem ?

are you using the theater mode? is that why?

**Comment by XemTube-TV** [comment]
https://xemtube.tv/video/-c-nhan-tam-ph-n-ii-ch-ng-7-tr-thanh-ng-i-giao-ti-p-kheo-leo?channelName=DacNhanTam.

You should disable theater mode for Article Article plugin

**Comment by DanielnetoDotCom** [comment]
Please update and try now
