### ISSUE TITLE
General

### ISSUE THREAD

**Issue by AntonG76** [YouPHPTube/YouPHPTube#2093]
Hi, I need guidance on how to upload my logo. Please help.

**Comment by tiplovo** [comment]
https://yousite.com/siteConfigurations

**Comment by AntonG76** [comment]
The site is not working. Please explain to me how to upload a logo. Thank you.

**Comment by XemTube-TV** [comment]
https://xemtube.tv/admin/?page=site_settings

Please login to the admin account and replace your domain name by following the link above to upload your logo.

**Comment by AntonG76** [comment]
Found it. Thank you. How do I change the navbar color?

**Comment by XemTube-TV** [comment]
Go to the following link and simply change your domain name and choose the theme you want

https://xemtube.tv/admin/?page=design_themes

**Comment by AntonG76** [comment]
Now I am getting No compatible source was found for this media. How do I fix that?

**Comment by DanielnetoDotCom** [comment]
@AntonG76 it should be multiple reasons, please provide more details of your video.

how did you upload it, what plugins you have enabled, video link, etc

**Comment by XemTube-TV** [comment]
@AntonG76  I think the error comes from having the Chromecast Plugin turned on. Please turn it off and try again. 

![image](https://user-images.githubusercontent.com/50126312/65963875-e11bf580-e485-11e9-8fc1-058eeb0ea19d.png)

**Comment by AntonG76** [comment]
I have it figured out and got things working. I have two others questions.

1. Which plugins do I have to purchase in order for live broadcasting to work?

2. When broadcasting live, is it possible to invite others to join on cam as a panel? like live video conferencing.

**Comment by DanielnetoDotCom** [comment]
@AntonG76 I guess for you the best option is to use a tool like skype or google hangout, and then you can stream your screen using OBS

you just need to properly configure your nignx to make the live works

**Comment by AntonG76** [comment]
Ok. Thank you.

1. How to I make the video player smaller?
2. How do I make video thumbnails become animated?

**Comment by DanielnetoDotCom** [comment]
1. use TheaterButton plugin or use CSS (of course you must know CSS to be able to do it)
2.  read this https://github.com/YouPHPTube/YouPHPTube/wiki/About-Video-Upload#information

**Comment by AntonG76** [comment]
I activated the TheaterButton. Video player still will not minimize.

![image](https://user-images.githubusercontent.com/46876438/66060661-081d0a80-e50c-11e9-8014-f3ee60e4a924.png)

**Comment by DanielnetoDotCom** [comment]
the VR360 must be enabled first
![image](https://user-images.githubusercontent.com/18009293/66061957-de1d1580-e516-11e9-892a-9fc93956a098.png)


after enable refresh your page.

I can not see the theater switch in your player, is it an embed video or self hosted video?

**Comment by AntonG76** [comment]
Embed videos

**Comment by DanielnetoDotCom** [comment]
TheaterButton and VR360 does not work with embed videos

**Comment by AntonG76** [comment]
Noted. Is it possible to embed Google Hangouts widget to the script? If so, where? I want to use it so channels can have a panel when they go live.

**Comment by DanielnetoDotCom** [comment]
I dont understand what do you mean.

**Comment by AntonG76** [comment]
Good morning. When channels broadcast live, I want them to be able to invite others to join them on cam.  Where in YouPHPTube script can I add the Google Hangouts widget codes?

**Comment by DanielnetoDotCom** [comment]
You already asked this 

![image](https://user-images.githubusercontent.com/18009293/66127942-37428300-e5c3-11e9-9e7e-cc1cd4dd0767.png)

**Comment by AntonG76** [comment]
Right. So now I am asking in which file do I paste the widget codes? :)

**Comment by DanielnetoDotCom** [comment]
I dont know what are you talking about.

I dont know what is this Google hangout code

**Comment by AntonG76** [comment]
https://stackoverflow.com/questions/25640441/embed-google-hangout-on-my-website-fully-functional-from-y-webpage

**Comment by DanielnetoDotCom** [comment]
try some of those

![image](https://user-images.githubusercontent.com/18009293/66128675-b7b5b380-e5c4-11e9-85ed-9cf3bbe5089c.png)

**Comment by AntonG76** [comment]
Awesome. Thank you. 

Next question: How do I add CA (Canada) to the country switch or whatever it is called in the following image?
![image](https://user-images.githubusercontent.com/46876438/66128930-dd3ebf00-e5bc-11e9-8814-304649d32b03.png)

**Comment by DanielnetoDotCom** [comment]
copy the us.php and name it ca.php. it may work

https://github.com/YouPHPTube/YouPHPTube/tree/master/locale

**Comment by AntonG76** [comment]
I am new to GitHub. I don't know how to perform that.

**Comment by DanielnetoDotCom** [comment]
You must do it on your server NOT on github, the link is just the file location.
you will not replace you will copy and create a new one.

**Comment by AntonG76** [comment]
I suggest you make it possible on your script to add countries. I am not proficient in performing such a task on my server. I am ignorant in that department. Lol. :)

**Comment by AntonG76** [comment]
Nobody answering questions today? LOL

**Comment by DanielnetoDotCom** [comment]
the only way to add countries now is to manually create the file

**Comment by AntonG76** [comment]
1. Where and how do I do that?

Next Question: Where do I get the Donation Link? I can't find anything on ,y PayPal

**Comment by DanielnetoDotCom** [comment]
1. I told you 4 days ago, you must look for this path into your server

![image](https://user-images.githubusercontent.com/18009293/66309423-f9559f80-e8df-11e9-828a-4452b4e2e51f.png)

2. try to google about paypal and donation

3. use the customize plugin, you can purchase it here https://www.youphptube.com/plugins/

**Comment by AntonG76** [comment]
I checked Google. It does not say what the Donation Link is.  I tried one link from PayPal and after pasting it,m the donate button took me to my YouPlay profile page. I', gonna need assistance,

**Comment by DanielnetoDotCom** [comment]
You can hire us for support or configure it for you.

we can not support you on paypal
