### ISSUE TITLE
Your videos directory must be writable

### ISSUE THREAD

**Issue by akhilleusuggo** [YouPHPTube/YouPHPTube#2095]
![image](https://user-images.githubusercontent.com/52116577/65941849-b48bbd80-e434-11e9-8fc6-5ee554cf640a.png)

I have changed dedicated server , and when installing the new server , I'm not able to make the directory writable . 
`sudo chmod -R 777 /var/www/html/YouPHPTube/view/configurations.phpvideos`
is not doing any effect

**Comment by DanielnetoDotCom** [comment]
If you are sure it is writable, just ignore this message

**Comment by DanielnetoDotCom** [comment]
actually, something is strange
this directory` /var/www/html/YouPHPTube/view/configurations.phpvideos`
it should be `sudo chmod -R 777 /var/www/html/YouPHPTube/videos`

**Comment by akhilleusuggo** [comment]
I managed to fix it `sudo chmod -R 777 /var/www/html/YouPHPTube/videos`

**Comment by magdesign** [comment]
Just keep in mind that `chmod -R 777` a folder would give permission to anyone to write and execute code on your server.
This means an attacker could execute code on your server, which does not fell very safe!
