### ISSUE TITLE
Stream Online but error: The media could not be loaded, either because the server or network failed or because the format is not supported.

### ISSUE THREAD

**Issue by elsenandy** [YouPHPTube/YouPHPTube#2098]
Hi,
I am setting up youphptube for me at home. Until now everything seems to be fine. Also streaming via OBS seems to work. At least it says that everything is online. But the stream doesn't show any video, and tells me "The media could not be loaded, either because the server or network failed or because the format is not supported."
Is there any Log where I can figure out the problem?
Best regards.

**Comment by elsenandy** [comment]
Also stats are showing correct.

**Comment by akhilleusuggo** [comment]
could you screen the parameters that you're using on your Live plugin ?

**Comment by elsenandy** [comment]
![Untitled](https://user-images.githubusercontent.com/56048211/66023273-fbd78400-e4f0-11e9-833a-e1dad9bf7f52.png)
Here you are.

Andy these are my plugin Settings:
{"button_title":"LIVE","server":"rtmp://youphptube.hostzone.lu/live","playerServer":"http://youphptube.hostzone.lu/live","stats":"http://youphptube.hostzone.lu:8080/stats","disableDVR":false,"disableGifThumbs":false,"useAadaptiveMode":false,"experimentalWebcam":false}

Best regards

**Comment by DanielnetoDotCom** [comment]
Hi, please check all the tips here https://github.com/YouPHPTube/YouPHPTube/issues/2073

**Comment by elsenandy** [comment]
Hi,

It was not really the same problem but i figured out. I had to set the port from player server also to 8080.

Now it seems that everything is working. I will go on to set up encoding for streams to be saved into library.

Best regards.
