### ISSUE TITLE
There are 2 errors on YouPHPtube that need fixing

### ISSUE THREAD

**Issue by XemTube-TV** [YouPHPTube/YouPHPTube#2099]
1. Embedded videos cannot use the theater presentation function.

![image](https://user-images.githubusercontent.com/50126312/66021343-985f4d80-e514-11e9-82db-e903f5c331c4.png)

![image](https://user-images.githubusercontent.com/50126312/66021836-27209a00-e516-11e9-9f1e-d9c7cfa0d61f.png)

2. When the Chromecast Plugin is enabled, Embed Videos will not work
 when it was played for the 2nd time onwards and received the error message "No compatible sources were found for this media"

![image](https://user-images.githubusercontent.com/50126312/66022051-e6755080-e516-11e9-944f-f6608d05da3f.png)

**Comment by DanielnetoDotCom** [comment]
We can not add theaterbutton on embed videos, we can only add it on our video player

if you update your files it should work. Chromecast should not be present on embed videos anymore.
