### ISSUE TITLE
Recording streamed Videos

### ISSUE THREAD

**Issue by elsenandy** [YouPHPTube/YouPHPTube#2101]
Hi there.

I am right to say, that only with a paid feature it is possible to record the streamed video?
If yes, is there a possibility to get a trial for some days? I am not sure yet if I want to use it, or it works as I supposed.

Best regards.

**Comment by DanielnetoDotCom** [comment]
Yes, you are correct, and sorry we do not have a trial.

but for sure it works, it will save your live stream and user your encoder to transcode the video file into a web playable

**Comment by elsenandy** [comment]
Thank you for your quick reply.

What about Mobile App? Do i need something special? I get an error when trying to connect. Or does it need to have https?

Best regards

**Comment by DanielnetoDotCom** [comment]
HTTPS is not required, but make sure you have your API plugin and the mobileManager plugin enabled

**Comment by elsenandy** [comment]
![Screenshot_20191002-193221_PHPTube](https://user-images.githubusercontent.com/56048211/66067270-88169500-e54b-11e9-8a8e-b432cd14b094.jpg)
I have now enabled these two settings, but I am getting the same error.
10.10.30.30 is my internal IP. Also with the real hostname i get the same error. No DNS Problems, Wifi enabled, no Firewall enabled. On my PC it's all working.

Best regards.

**Comment by DanielnetoDotCom** [comment]
Is your phone at the same network as your internal IP? 10.10.30.30

your phone must be on the same network

**Comment by elsenandy** [comment]
My Phone is on 10.10.20.0 but has access to 10.10.30.0
What about connecting from external. the phone will not be on the same network.

**Comment by DanielnetoDotCom** [comment]
that is your network limitation, all devices must be on the same network

**Comment by elsenandy** [comment]
Changed now the server to the same network as my smartphone.

Sorry same error.

**Comment by DanielnetoDotCom** [comment]
I am not sure what you have, but I am pretty sure the error still in your network.

try to use a public IP for your server

**Comment by elsenandy** [comment]
Oh lol, from public, it's working..

Only thing I need. 

Best regards, and many thanks for your super support.

I will give the information to our company, in order to setup youphptube for internal documentation and user helpsystem. I love the product.

Best regards.
