### ISSUE TITLE
Https site is not showing correctly

### ISSUE THREAD

**Issue by elsenandy** [YouPHPTube/YouPHPTube#2103]
Hi,

One last error. ;)
I set up everything, and enabled https in Apache. I have no cert for internal use.
Internal I can connect via https without any problems. But if I want to connect from external via Reverse Proxy by using https with good certificate, the site is not showing correcty.
-> Screenshot

![Untitled](https://user-images.githubusercontent.com/56048211/66067582-2efb3100-e54c-11e9-8421-aaca95863753.png)

Are there some more ports to open? I opened already 8080 for Nginx. Stats are showing correct.

**Comment by DanielnetoDotCom** [comment]
can you please paste here your configuration.php file?

make sure you hide your database password

**Comment by elsenandy** [comment]
the one out of the video folder? /var/www/html/YouPHPTube/videos?
That will be this one:

<?php
$global['configurationVersion'] = 2;
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) { 
    // get the subdirectory, if exists
    $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
    $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
    $global['webSiteRootURL'] = 'http://youphptube.hostzone.lu/YouPHPTube/';
}
$global['systemRootPath'] = '/var/www/html/YouPHPTube/';
$global['salt'] = '5d93972f36258';
$global['enableDDOSprotection'] = 1;
$global['ddosMaxConnections'] = 40;
$global['ddosSecondTimeout'] = 5;
$global['strictDDOSprotection'] = 0;

$mysqlHost = 'localhost';
$mysqlPort = '3306';
$mysqlUser = 'root';
$mysqlPass = '******';
$mysqlDatabase = 'youPHPTube';

/**
 * Do NOT change from here
 */

require_once $global['systemRootPath'].'objects/include_config.php';

**Comment by elsenandy** [comment]
<?php
$global['configurationVersion'] = 2;
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) { 
    // get the subdirectory, if exists
    $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
    $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
    $global['webSiteRootURL'] = 'http://youphptube.hostzone.lu/YouPHPTube/';
}
$global['systemRootPath'] = '/var/www/html/YouPHPTube/';
$global['salt'] = '5d93972f36258';
$global['enableDDOSprotection'] = 1;
$global['ddosMaxConnections'] = 40;
$global['ddosSecondTimeout'] = 5;
$global['strictDDOSprotection'] = 0;

$mysqlHost = 'localhost';
$mysqlPort = '3306';
$mysqlUser = 'root';
$mysqlPass = '****';
$mysqlDatabase = 'youPHPTube';

/**
 * Do NOT change from here
 */

require_once $global['systemRootPath'].'objects/include_config.php';

**Comment by DanielnetoDotCom** [comment]
replace this 

```
if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) {
// get the subdirectory, if exists
$subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), FILE);
$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
$global['webSiteRootURL'] = 'http://youphptube.hostzone.lu/YouPHPTube/';
}
```

for this

`$global['webSiteRootURL'] = 'http://youphptube.hostzone.lu/YouPHPTube/';`

only one line

**Comment by elsenandy** [comment]
I am sorry,

that did not helped.

Here my actual file now:

`<?php
$global['configurationVersion'] = 2;
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
$global['webSiteRootURL'] = 'http://youphptube.hostzone.lu/YouPHPTube/';

$global['systemRootPath'] = '/var/www/html/YouPHPTube/';
$global['salt'] = '5d93972f36258';
$global['enableDDOSprotection'] = 1;
$global['ddosMaxConnections'] = 40;
$global['ddosSecondTimeout'] = 5;
$global['strictDDOSprotection'] = 0;

$mysqlHost = 'localhost';
$mysqlPort = '3306';
$mysqlUser = 'root';
$mysqlPass = '****';
$mysqlDatabase = 'youPHPTube';

/**
 * Do NOT change from here
 */

require_once $global['systemRootPath'].'objects/include_config.php';
`

**Comment by DanielnetoDotCom** [comment]
ok, now please delete your videos/cache directory

**Comment by elsenandy** [comment]
I changed in that file now http to https on URL.

Now it's ok.
