### ISSUE TITLE
Video views

### ISSUE THREAD

**Issue by Donnerstein** [YouPHPTube/YouPHPTube#2106]
Hello,
if the cookies are blocked or frozen by the browser extension "Umatrix", then the views of a video increase every second and thereby falsify the actual views.

umatrix extension:
https://addons.mozilla.org/de/firefox/addon/umatrix/

**Comment by Donnerstein** [comment]
I have another question, is there already a possibility to add the option to set the replay speed?

greeting
Donnerstein

**Comment by DanielnetoDotCom** [comment]
I didn't know about the cookies, I have to think about a solution. I do not have any yet.

the playback speed we recently add  it in the PlayerSkins plugin
![image](https://user-images.githubusercontent.com/18009293/66123420-5ab40080-e5b8-11e9-9184-5c7b38722b42.png)

**Comment by DanielnetoDotCom** [comment]
I sent an update to try to block the cookie error
