### ISSUE TITLE
Domain

### ISSUE THREAD

**Issue by streamer84** [YouPHPTube/YouPHPTube#2108]
How do i change the ip url to my domain?

**Comment by DanielnetoDotCom** [comment]
I think you should google for that, it is not related to YouPHPTube

**Comment by streamer84** [comment]
change http://myIP/YouPHPTube/ to a domain that I bought, so this change is done outside my website?

**Comment by DanielnetoDotCom** [comment]
Just a tip ...
for myself I use apache virtual hosts
