### ISSUE TITLE
clonesite plugin

### ISSUE THREAD

**Issue by fst24sx** [YouPHPTube/YouPHPTube#2109]
When using the clone site plugin usually after a few hundred videos it will hang with no error. just sits there for hours on same video title.

i have checked logs and it shows nothing.

we have several thousand videos and are having a hard time getting the site to clone properly.

**Comment by DanielnetoDotCom** [comment]
You may find the progress of a clone in the directory `videos/cache/clones/`

if it crashes, check the log from both streamers for some clue

**Comment by fst24sx** [comment]
it doesnt crash. it just hangs it will just sit on video XXX out of 30,000.

ive checked logs and it shows no errors. every few hundred videos it does this. i have to close the window and restart the clone process and it picks up where it left off after copying the database all over again.

 none of the logs form either server shows an error.

**Comment by DanielnetoDotCom** [comment]
if you close the window, you do not need to restart the progress, it may overload your server

just follow the progress in your log file with the tail command

`tail -f videos/cache/clones/yourlogfile.log`

**Comment by fst24sx** [comment]
right, I think you are missing my issue.

I have done this 4 days ago. after a few hundred videos it will hang. no error just sits there on the same video for 6+ hours

i am already watching from command line

it just hangs no error.

**Comment by fst24sx** [comment]
it took approx 24hrs to transfer only 15gb worth of movies. both servers are dedicated with 1gbps ports. this is abnormally slow.

not sure whats going on. its going but extremely slow. im closing the issue for now. I will re open once I figure it out.

 thanks for the insight :)

**Comment by DanielnetoDotCom** [comment]
the good thing is that the clone script is incremental, next time will only transfer the new videos.

**Comment by fst24sx** [comment]
ok quick question, Since I have restarted the clone process a couple times before it finished. does that mean its doing 2X the work now?

should/could I terminate the current process and start it as a single process properly?  or should I just leave it?

**Comment by DanielnetoDotCom** [comment]
I am pretty sure it will run twice, you will need to stop apache or restart your server to make it free.

**Comment by fst24sx** [comment]
can I just do regular restart apache command?

**Comment by DanielnetoDotCom** [comment]
sorry what?

**Comment by fst24sx** [comment]
nevermind I figured it out.

OK so for anyone else interested. if you start the clone process multiple times it will run on multiple threads over writing itself and taking forever.  The GUI in the admin panel has a tendency to get stuck and have major delay in displaying the process.

none of this is a n issue when you only have a few hundred or thousand videos. but i have around 50,000 videos. so after running the clone process every few thousand it will hang. so use CLI to watch the log files to help minimize clone issues
1. start clone process from admin panel
2. Run command: "cd  /var/www/html/YouPHPTube/videos/cache/clones"
3. run command: "tail -f client.log" 
4. if video hangs for abnormal amount of time run command: "sudo service apache2 restart"
5. click "clone now" button in admin panel
6. repeat steps 2&3 and watch progress
7. of it hangs again repeat steps 4-6 in that order

(each time you do this it will pick up the cloning process where it left off instead of creating new threads slowing it down.)

I hope this helps someone else.
