### ISSUE TITLE
Search engine does not work

### ISSUE THREAD

**Issue by maxlinux2000** [YouPHPTube/YouPHPTube#2112]
As written above, the search engine for videos does not work.
Steps to reproduce:
Go to the home of your youphptube and in the search engine above insert a word of a title that knows that it exists (you can copy and paste)

Outcome:
A page opens where it tells you:
Warning! We haven't found videos or audios to show.

What should I do
It would have to work and look so much in the titles that in the descriptions of the videos

I have see in the console of browser... there are 3 fonts missing, but I don't thinks so important for this bug

![Captura de pantalla de 2019-10-04 11-57-12](https://user-images.githubusercontent.com/5683921/66199179-5d892100-e69e-11e9-891c-b84013f44d1e.png)

Here the Log

> root@iesus:/var/www/html/YouPHPTube/videos# tail -f youphptube.log 
>                     [0] => /var/www/html/YouPHPTube/plugin/YouTube/view/modeYouTube.php
>                 )
> 
>             [function] => require
>         )
> 
> )
> 
> [04-Oct-2019 11:50:29 Europe/Berlin] [sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) Table 'youPHPTube.tags_has_videos' doesn't exist<br>
> SELECT u.*, v.*,  nv.title as next_title, nv.clean_title as next_clean_title, nv.filename as next_filename, nv.id as next_id, c.id as category_id,c.iconClass,c.name as category,c.iconClass,  c.clean_name as clean_category,c.description as category_description,c.nextVideoOrder as category_order, v.created as videoCreation,  (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = 1 ) as likes,  (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = -1 ) as dislikes , (SELECT `like` FROM likes as l where l.videos_id = v.id AND users_id = '1' ) as myVote  FROM videos as v LEFT JOIN categories c ON categories_id = c.id LEFT JOIN users u ON v.users_id = u.id LEFT JOIN videos nv ON v.next_videos_id = nv.id  WHERE 1=1  AND u.status = 'a'  AND v.status IN ('a','xmp4','xwebm','xmp3','xogg') AND (v.id IN (select videos_id FROM tags_has_videos LEFT JOIN tags as t ON tags_id = t.id AND t.name LIKE '%presentación%' WHERE t.id is NOT NULL) OR ( v.title LIKE '%presentación%'  OR  CONVERT(CAST(v.title as BINARY) USING utf8) LIKE '%presentación%'  OR  v.description LIKE '%presentación%'  OR  CONVERT(CAST(v.description as BINARY) USING utf8) LIKE '%presentación%'  OR  c.name LIKE '%presentación%'  OR  CONVERT(CAST(c.name as BINARY) USING utf8) LIKE '%presentación%'  OR  c.description LIKE '%presentación%'  OR  CONVERT(CAST(c.description as BINARY) USING utf8) LIKE '%presentación%' )) AND v.id != 1  ORDER BY RAND()  LIMIT 1
> [04-Oct-2019 12:00:58 Europe/Berlin] getVideosURL generated in 0.0062 seconds. fileName: _YPTuniqid_5d8ba2243a7595.00294050 
> [04-Oct-2019 12:00:59 Europe/Berlin] getVideosURL Cache in 0.0002 seconds. fileName: _YPTuniqid_5d8e28a60d8e44.42715310 
> [04-Oct-2019 12:00:59 Europe/Berlin] getVideosURL age: 145111 minimumExpirationTime: 31536000
> [04-Oct-2019 12:00:59 Europe/Berlin] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/YouPHPTube/plugin/VideoTags/VideoTags.php on line 176
> [04-Oct-2019 12:01:14 Europe/Berlin] Array
> (
>     [0] => Array
>         (
>             [file] => /var/www/html/YouPHPTube/objects/mysql_dal.php
>             [line] => 130
>             [function] => log_error
>             [args] => Array
>                 (
>                     [0] => [sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) Table 'youPHPTube.tags_has_videos' doesn't exist<br>
> SELECT u.*, v.*,  nv.title as next_title, nv.clean_title as next_clean_title, nv.filename as next_filename, nv.id as next_id, c.id as category_id,c.iconClass,c.name as category,c.iconClass,  c.clean_name as clean_category,c.description as category_description,c.nextVideoOrder as category_order, v.created as videoCreation,  (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = 1 ) as likes,  (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = -1 ) as dislikes , (SELECT `like` FROM likes as l where l.videos_id = v.id AND users_id = '1' ) as myVote  FROM videos as v LEFT JOIN categories c ON categories_id = c.id LEFT JOIN users u ON v.users_id = u.id LEFT JOIN videos nv ON v.next_videos_id = nv.id  WHERE 1=1  AND u.status = 'a'  AND v.status IN ('a','xmp4','xwebm','xmp3','xogg') AND (v.id IN (select videos_id FROM tags_has_videos LEFT JOIN tags as t ON tags_id = t.id AND t.name LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%' WHERE t.id is NOT NULL) OR ( v.title LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  CONVERT(CAST(v.title as BINARY) USING utf8) LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  v.description LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  CONVERT(CAST(v.description as BINARY) USING utf8) LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  c.name LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  CONVERT(CAST(c.name as BINARY) USING utf8) LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  c.description LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  CONVERT(CAST(c.description as BINARY) USING utf8) LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%' )) ORDER BY v.Created DESC  LIMIT 1
>                 )
> 
>         )
> 
>     [1] => Array
>         (
>             [file] => /var/www/html/YouPHPTube/objects/video.php
>             [line] => 693
>             [function] => readSql
>             [class] => sqlDAL
>             [type] => ::
>             [args] => Array
>                 (
>                     [0] => SELECT u.*, v.*,  nv.title as next_title, nv.clean_title as next_clean_title, nv.filename as next_filename, nv.id as next_id, c.id as category_id,c.iconClass,c.name as category,c.iconClass,  c.clean_name as clean_category,c.description as category_description,c.nextVideoOrder as category_order, v.created as videoCreation,  (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = 1 ) as likes,  (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = -1 ) as dislikes , (SELECT `like` FROM likes as l where l.videos_id = v.id AND users_id = '1' ) as myVote  FROM videos as v LEFT JOIN categories c ON categories_id = c.id LEFT JOIN users u ON v.users_id = u.id LEFT JOIN videos nv ON v.next_videos_id = nv.id  WHERE 1=1  AND u.status = 'a'  AND v.status IN ('a','xmp4','xwebm','xmp3','xogg') AND (v.id IN (select videos_id FROM tags_has_videos LEFT JOIN tags as t ON tags_id = t.id AND t.name LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%' WHERE t.id is NOT NULL) OR ( v.title LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  CONVERT(CAST(v.title as BINARY) USING utf8) LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  v.description LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  CONVERT(CAST(v.description as BINARY) USING utf8) LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  c.name LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  CONVERT(CAST(c.name as BINARY) USING utf8) LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  c.description LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  CONVERT(CAST(c.description as BINARY) USING utf8) LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%' )) ORDER BY v.Created DESC  LIMIT 1
>                 )
> 
>         )
> 
>     [2] => Array
>         (
>             [file] => /var/www/html/YouPHPTube/plugin/YouTube/view/modeYouTube.php
>             [line] => 49
>             [function] => getVideo
>             [class] => Video
>             [type] => ::
>             [args] => Array
>                 (
>                     [0] => 0
>                     [1] => viewable
>                     [2] => 
>                     [3] => 
>                     [4] => 1
>                 )
> 
>         )
> 
>     [3] => Array
>         (
>             [file] => /var/www/html/YouPHPTube/view/index.php
>             [line] => 27
>             [args] => Array
>                 (
>                     [0] => /var/www/html/YouPHPTube/plugin/YouTube/view/modeYouTube.php
>                 )
> 
>             [function] => require
>         )
> 
> )
> 
> [04-Oct-2019 12:01:14 Europe/Berlin] [sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) Table 'youPHPTube.tags_has_videos' doesn't exist<br>
> SELECT u.*, v.*,  nv.title as next_title, nv.clean_title as next_clean_title, nv.filename as next_filename, nv.id as next_id, c.id as category_id,c.iconClass,c.name as category,c.iconClass,  c.clean_name as clean_category,c.description as category_description,c.nextVideoOrder as category_order, v.created as videoCreation,  (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = 1 ) as likes,  (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = -1 ) as dislikes , (SELECT `like` FROM likes as l where l.videos_id = v.id AND users_id = '1' ) as myVote  FROM videos as v LEFT JOIN categories c ON categories_id = c.id LEFT JOIN users u ON v.users_id = u.id LEFT JOIN videos nv ON v.next_videos_id = nv.id  WHERE 1=1  AND u.status = 'a'  AND v.status IN ('a','xmp4','xwebm','xmp3','xogg') AND (v.id IN (select videos_id FROM tags_has_videos LEFT JOIN tags as t ON tags_id = t.id AND t.name LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%' WHERE t.id is NOT NULL) OR ( v.title LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  CONVERT(CAST(v.title as BINARY) USING utf8) LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  v.description LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  CONVERT(CAST(v.description as BINARY) USING utf8) LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  c.name LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  CONVERT(CAST(c.name as BINARY) USING utf8) LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  c.description LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  CONVERT(CAST(c.description as BINARY) USING utf8) LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%' )) ORDER BY v.Created DESC  LIMIT 1
> [04-Oct-2019 12:01:14 Europe/Berlin] Array
> (
>     [0] => Array
>         (
>             [file] => /var/www/html/YouPHPTube/objects/mysql_dal.php
>             [line] => 130
>             [function] => log_error
>             [args] => Array
>                 (
>                     [0] => [sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) Table 'youPHPTube.tags_has_videos' doesn't exist<br>
> SELECT u.*, v.*,  nv.title as next_title, nv.clean_title as next_clean_title, nv.filename as next_filename, nv.id as next_id, c.id as category_id,c.iconClass,c.name as category,c.iconClass,  c.clean_name as clean_category,c.description as category_description,c.nextVideoOrder as category_order, v.created as videoCreation,  (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = 1 ) as likes,  (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = -1 ) as dislikes , (SELECT `like` FROM likes as l where l.videos_id = v.id AND users_id = '1' ) as myVote  FROM videos as v LEFT JOIN categories c ON categories_id = c.id LEFT JOIN users u ON v.users_id = u.id LEFT JOIN videos nv ON v.next_videos_id = nv.id  WHERE 1=1  AND u.status = 'a'  AND v.status IN ('a','xmp4','xwebm','xmp3','xogg') AND (v.id IN (select videos_id FROM tags_has_videos LEFT JOIN tags as t ON tags_id = t.id AND t.name LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%' WHERE t.id is NOT NULL) OR ( v.title LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  CONVERT(CAST(v.title as BINARY) USING utf8) LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  v.description LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  CONVERT(CAST(v.description as BINARY) USING utf8) LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  c.name LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  CONVERT(CAST(c.name as BINARY) USING utf8) LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  c.description LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  CONVERT(CAST(c.description as BINARY) USING utf8) LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%' )) AND v.id != 1  ORDER BY RAND()  LIMIT 1
>                 )
> 
>         )
> 
>     [1] => Array
>         (
>             [file] => /var/www/html/YouPHPTube/objects/video.php
>             [line] => 693
>             [function] => readSql
>             [class] => sqlDAL
>             [type] => ::
>             [args] => Array
>                 (
>                     [0] => SELECT u.*, v.*,  nv.title as next_title, nv.clean_title as next_clean_title, nv.filename as next_filename, nv.id as next_id, c.id as category_id,c.iconClass,c.name as category,c.iconClass,  c.clean_name as clean_category,c.description as category_description,c.nextVideoOrder as category_order, v.created as videoCreation,  (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = 1 ) as likes,  (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = -1 ) as dislikes , (SELECT `like` FROM likes as l where l.videos_id = v.id AND users_id = '1' ) as myVote  FROM videos as v LEFT JOIN categories c ON categories_id = c.id LEFT JOIN users u ON v.users_id = u.id LEFT JOIN videos nv ON v.next_videos_id = nv.id  WHERE 1=1  AND u.status = 'a'  AND v.status IN ('a','xmp4','xwebm','xmp3','xogg') AND (v.id IN (select videos_id FROM tags_has_videos LEFT JOIN tags as t ON tags_id = t.id AND t.name LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%' WHERE t.id is NOT NULL) OR ( v.title LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  CONVERT(CAST(v.title as BINARY) USING utf8) LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  v.description LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  CONVERT(CAST(v.description as BINARY) USING utf8) LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  c.name LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  CONVERT(CAST(c.name as BINARY) USING utf8) LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  c.description LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  CONVERT(CAST(c.description as BINARY) USING utf8) LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%' )) AND v.id != 1  ORDER BY RAND()  LIMIT 1
>                 )
> 
>         )
> 
>     [2] => Array
>         (
>             [file] => /var/www/html/YouPHPTube/plugin/YouTube/view/modeYouTube.php
>             [line] => 51
>             [function] => getVideo
>             [class] => Video
>             [type] => ::
>             [args] => Array
>                 (
>                     [0] => 0
>                     [1] => viewable
>                     [2] => 
>                     [3] => 1
>                 )
> 
>         )
> 
>     [3] => Array
>         (
>             [file] => /var/www/html/YouPHPTube/view/index.php
>             [line] => 27
>             [args] => Array
>                 (
>                     [0] => /var/www/html/YouPHPTube/plugin/YouTube/view/modeYouTube.php
>                 )
> 
>             [function] => require
>         )
> 
> )
> 
> [04-Oct-2019 12:01:14 Europe/Berlin] [sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) Table 'youPHPTube.tags_has_videos' doesn't exist<br>
> SELECT u.*, v.*,  nv.title as next_title, nv.clean_title as next_clean_title, nv.filename as next_filename, nv.id as next_id, c.id as category_id,c.iconClass,c.name as category,c.iconClass,  c.clean_name as clean_category,c.description as category_description,c.nextVideoOrder as category_order, v.created as videoCreation,  (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = 1 ) as likes,  (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = -1 ) as dislikes , (SELECT `like` FROM likes as l where l.videos_id = v.id AND users_id = '1' ) as myVote  FROM videos as v LEFT JOIN categories c ON categories_id = c.id LEFT JOIN users u ON v.users_id = u.id LEFT JOIN videos nv ON v.next_videos_id = nv.id  WHERE 1=1  AND u.status = 'a'  AND v.status IN ('a','xmp4','xwebm','xmp3','xogg') AND (v.id IN (select videos_id FROM tags_has_videos LEFT JOIN tags as t ON tags_id = t.id AND t.name LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%' WHERE t.id is NOT NULL) OR ( v.title LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  CONVERT(CAST(v.title as BINARY) USING utf8) LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  v.description LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  CONVERT(CAST(v.description as BINARY) USING utf8) LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  c.name LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  CONVERT(CAST(c.name as BINARY) USING utf8) LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  c.description LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%'  OR  CONVERT(CAST(c.description as BINARY) USING utf8) LIKE '%3 Consagraciones al Sagrado Corazón de Jesús y una Oración de confianza%' )) AND v.id != 1  ORDER BY RAND()  LIMIT 1

**Comment by maxlinux2000** [comment]
apparently the error is in

[0] => [sqlDAL :: readSql] (mysqlnd) Prepare failed: (1146) Table 'youPHPTube.tags_has_videos' doesn't exist

**Comment by DanielnetoDotCom** [comment]
The tags_has_videos error you can fix installing the plugins table

![image](https://user-images.githubusercontent.com/18009293/66204459-438d1580-e681-11e9-8a52-374b0f792b7c.png)

**Comment by maxlinux2000** [comment]
Perfect!! tnx a lot!
