### ISSUE TITLE
Comments, display and editing

### ISSUE THREAD

**Issue by Donnerstein** [YouPHPTube/YouPHPTube#2115]
Hello,
If there are too many answering levels in the comments, there will be an error displaying them.
![image](https://user-images.githubusercontent.com/52116237/66246033-d9708100-e711-11e9-9a49-47b663230a57.png)

And another thing, a uploader can edit the comments of other users under his video, is that the intention?
I think a uploader should only be able to delete comments from others under his videos, but changing a comment should only be allowed to the owner or an admin.

greeting
Thunderstone.

**Comment by DanielnetoDotCom** [comment]
Thanks, I agree with you, and I just sent the updates

**Comment by Donnerstein** [comment]
Very good thank you.

Regarding the comments, I would have a suggestion.
Users who are not allowed to upload themselves, can not use the page /comments.
In my opinion, this is not very meaningful. Even if a user can not upload videos, he has to search each of his comments under the videos in order to be able to respond. I also think that Regular Nuter should be able to access this page.

greeting
Thunderstone.
