### ISSUE TITLE
 The encoding page is failing and requires updating to YouTube-DL

### ISSUE THREAD

**Issue by XemTube-TV** [YouPHPTube/YouPHPTube#2116]
The encoding page is failing and requires updating to YouTube-DL

![image](https://user-images.githubusercontent.com/50126312/66253173-3578eb00-e78e-11e9-98f4-77cfdddeb60c.png)

**Comment by DanielnetoDotCom** [comment]
this is the public encoder, it is highly used, the problem there is because this server already made too many requests in a short time. youtube block it for queries for today
