### ISSUE TITLE
General Reopening #2093

### ISSUE THREAD

**Issue by AntonG76** [YouPHPTube/YouPHPTube#2123]
You have PayPal donation link setup on your YouPHPTube demo site. So, where did you get the link? Can you not show me snapshots of where to get a donation link??? 

Why close my previous thread? 

Don't lose your patience. Not everyone knows where to get a donation link. I went to developers site. Its not showing me any donation link!

**Comment by XemTube-TV** [comment]
you see at this link https://www.paypal.com/vn/webapps/mpp/paypal-me?locale.x=vi_VN

**Comment by AntonG76** [comment]
I tried that. I paste the Pay.Me link and it did not work.

**Comment by XemTube-TV** [comment]
Have you activated your Palpal account successfully?

**Comment by AntonG76** [comment]
Yep

**Comment by XemTube-TV** [comment]
Please give me the link to link your Paypal for me to test the error from?

**Comment by DanielnetoDotCom** [comment]
For myself, I create a donation button and grab the email link

![image](https://user-images.githubusercontent.com/18009293/66399130-68e98e80-e9b5-11e9-923b-d158db04657c.png)

You will be redirected to here https://www.paypal.com/donate/buttons

**Comment by AntonG76** [comment]
Thanks guys. I got it figured out. :)
