### ISSUE TITLE
encoder login

### ISSUE THREAD

**Issue by fst24sx** [YouPHPTube/YouPHPTube#2130]
I cloned new site. but cannot log into the encoder because it either tells me 
"unable to find streamer site"
"this streamer site is now allowed"

which file to  manually fix allowed streamer site?

**Comment by fst24sx** [comment]
If only msql I do not have any mysql tools 

which mysql commands do I need to use to change streamer url?

**Comment by akhilleusuggo** [comment]
@fst24sx If you cloned the site ( and it does have a different domain name ) , of course the streamer site is unable . You need to add the streamer site to your encoder . Try to enter to your encoder , and type the name of your new site : 
![image](https://user-images.githubusercontent.com/52116577/66645367-f0d8ce00-ec2b-11e9-998c-f7fa85d81e06.png)

**Comment by fst24sx** [comment]
> @fst24sx If you cloned the site ( and it does have a different domain name ) , of course the streamer site is not allawed . You need to add the streamer site to your encoder . Try to enter to your encoder , and type the name of your new site :
> ![image](https://user-images.githubusercontent.com/52116577/66645367-f0d8ce00-ec2b-11e9-998c-f7fa85d81e06.png)

...yea I think you missed my point.
im unable to log in because it doesnt recognize the streamer URL. 
I need to edit these setting manually. so that i can actually log in.

**Comment by akhilleusuggo** [comment]
@fst24sx You can install phpmyadmin 
`sudo apt install phpmyadmin `
Follow the instruction ;
Once installed , you can go there tho your http://IP/phpmyadmin , or http(s)://domain.com/phpmyadmin
Go to encoder db , configuration , and you will be able to see the streamer site you had , you can change it from there

**Comment by fst24sx** [comment]
> @fst24sx You can install phpmyadmin
> `sudo apt install phpmyadmin `
> Follow the instruction ;
> Once installed , you can go there tho your http://IP/phpmyadmin , or http(s)://domain.com/phpmyadmin
> Go to encoder db , configuration , and you will be able to see the streamer site you had , you can change it from there

So I did this. however it does not show my database. it shows a phpmyadmin database. 

how do i make it show my youPHPTube database?
![php](https://user-images.githubusercontent.com/55811362/66710578-58784180-ed30-11e9-870b-707b48da6bb9.JPG)

**Comment by fst24sx** [comment]
ok well I figured it out by going in and changing the database that phpmyadmin was using and enabling .htaccess on that page,
