### ISSUE TITLE
 Support to fix the error "This site cannot provide a secure connection"

### ISSUE THREAD

**Issue by XemTube-TV** [YouPHPTube/YouPHPTube#2131]
I suddenly get an error today "
 "This site cannot provide a secure connection" ERR_SSL_PROTOCOL_ERROR . Can you check the cause and fix this error for me?

![image](https://user-images.githubusercontent.com/50126312/66642555-2ccd5c80-ec47-11e9-85d2-5b776372755b.png)

**Comment by akhilleusuggo** [comment]
This means that your site doesn't have a valid SSL , or better doesn't support SSL 
Try to access your site with http instead of https 

Edit : I see your site working fine . Try cleaning the SSL/Cache of your browser

**Comment by DanielnetoDotCom** [comment]
Looks like you are using a CDN (probably cloudflare)
![image](https://user-images.githubusercontent.com/18009293/66651683-09d08780-ec0a-11e9-8daa-b2da303dac36.png)

I have installed lets encrypt to you, and now you have a conflict.

If I am in your shoes I would disable the CDN and install the letsencrypt again
