### ISSUE TITLE
Ubuntu server config considerations

### ISSUE THREAD

**Issue by millzee01** [YouPHPTube/YouPHPTube#2142]
Hi,

I'm building a new ubuntu 18.4 vm server to just host videos and play them back.  no streaming required.  Before I install youPHPTube i was wondering if there is a specific server config I should use to make the server ready? 

Is there  requirement for nginx if streaming is not required?

do i just install the server then let youPHPTube do the rest or do I need to add anything before starting the youPHPTube install to harden it?

What is the recommendation for partitioning?  30gb for system and rest for data?

Many thanks

**Comment by DanielnetoDotCom** [comment]
please check this https://github.com/YouPHPTube/YouPHPTube/wiki/YouPHPTube-hadware-requirements

**Comment by maxlinux2000** [comment]
the ideal would be to have a couple of articles for ubuntu 18.04 and debian 10, in the style of the ispconfig team, entitled for example: "Ubuntu 18.04 - The Perfect Server for YouPHPTube"

for example:
https://www.howtoforge.com/tutorial/perfect-server-ubuntu-18.04-with-apache-php-myqsl-pureftpd-bind-postfix-doveot-and-ispconfig/2/

https://www.howtoforge.com/perfect-server-debian-10-buster-apache-bind-dovecot-ispconfig-3-1/

There you can include details about security, which are outside of YouPHPTube, but very important, such as the firewall, fail2ban, ssh login keys ...

**Comment by millzee01** [comment]
good idea,  i've done a document on our build from scratch which includes hardening, letsencrypt etc.  will review and post it.
