### ISSUE TITLE
CustomizeAdvanced-UTF8 issue

### ISSUE THREAD

**Issue by bluems** [YouPHPTube/YouPHPTube#2144]
My site doesn't work utf8Encode and Decode in CustomizeAdvanced.

DB, Table and Column are using utf8mb4_unicode_ci.

When using utf8_unicode_ci, same issue.

Where I check problem?

YouPHPTube: 7.7
PHP: 5.6
DB: MariaDB 5.5.60

**Comment by bluems** [comment]
Sorry, I found. 
problem is mariadb server.
I did not know so far because there was no problem in other programs using utf8.

**Comment by DanielnetoDotCom** [comment]
If you want to try we fixed a similar problem

Add the line below in the videos/configuration.php file

`$global['mysqli_charset'] = 'utf8';`
