### ISSUE TITLE
Security Concerns

### ISSUE THREAD

**Issue by millzee01** [YouPHPTube/YouPHPTube#2145]
Hi,

is there a reason for setting this:
<Directory   /var/www/>
Options Indexes FollowSymLinks
AllowOverride All
Require all granted
</Directory>

because doing so allows directory browsing,  i've removed indexes which stops it but wondered if this impacts youPHPTube operation anywhere?

**Comment by DanielnetoDotCom** [comment]
this is for the mod_rewrite only, if you remove and it still working you do not have to worry about it.

**Comment by millzee01** [comment]
thanks,  removing it from top level /var/www causes an issue so I had to create a directive for each folder.

/var/www/YouPHPTube and /var/www/YouPHPTube-Encoder

Seems to work now  thanks
