### ISSUE TITLE
API advice

### ISSUE THREAD

**Issue by millzee01** [YouPHPTube/YouPHPTube#2146]
Hi,

Is there a plugin that allows my users to stay on the streamer page when uploading a video to a private encoder?

or can you see any issues if I load the encoder page in a modal?

This is so I can keep my users on the streamer page instead of opening new tabs for each video upload.

thanks

**Comment by DanielnetoDotCom** [comment]
no, there is not such plugin

**Comment by millzee01** [comment]
Would you say this is doable with a custom plugin?

**Comment by DanielnetoDotCom** [comment]
If I understand correctly this will be pretty hard to build

**Comment by millzee01** [comment]
i'll have a go and post my results in case it helps anyone else :-) is it ok to do that?

**Comment by DanielnetoDotCom** [comment]
sure, this will be awesome

**Comment by millzee01** [comment]
Just for info, i managed to get this working with fancybox.  Will post what i've done once I iron a few bugs
