### ISSUE TITLE
smtp works on test php script but not in YouPHPTube

### ISSUE THREAD

**Issue by millzee01** [YouPHPTube/YouPHPTube#2147]
Hi,

i have a top level smtp server which sends emails fine.

I created a script to use ../YouPHPTube/objects/PHPMailer/PHPMailerAutoload.php

require "../YouPHPTube/objects/PHPMailer/PHPMailerAutoload.php";
$mail = new PHPMailer();
$mail->IsSMTP(); 
$mail->SMTPDebug = 2;
$mail->SMTPAuth = true;     // turn of SMTP authentication
$mail->Username = "no-reply@smtp.domain.com";  // SMTP username
$mail->Password = 'password'; // SMTP password
$mail->SMTPSecure = "tls";
$mail->Host = "smtp.domain.com"; // SMTP host
$mail->Port = 587;
$webmaster_email = "admin@smtp.domain.com";       //Reply to this email ID
$email="test@mydomain.com";                // Recipients email ID
$name="Carl";                              // Recipient's name
$mail->From = $webmaster_email;
$mail->FromName = "admin";
$mail->AddAddress($email,$name);
$mail->AddReplyTo($webmaster_email,"Admin");
$mail->WordWrap = 50;                         // set word wrap
$mail->IsHTML(true);                          // send as HTML
$mail->Subject = "subject";
$mail->Body = "Hi,
This is the HTML BODY ";                      //HTML Body 
$mail->AltBody = "This is the body when user views in plain text format"; //Text Body 

if(!$mail->Send()){
echo "Mailer Error: " . $mail->ErrorInfo;
}else{
echo "Message has been sent";
}

The script runs fine and sends the email.

When i put the info into the youPHPTube configuration:

Enable SMTP: Enabled
Enable SMTP Auth: Enabled
SMTP Secure: tls
SMTP Port: 587
SMTP Host: smtp.domain.com
SMTP Username: no-reply@smtp.domain.com
SMTP Password: ************

it says its sent an email (where does this email go?)

I save the config and try and do a forgot password then get the "Message could not be sent SMTP connect() failed." 

Which is strange because on the same box (ubuntu 18.4) my test script with exactly the same info works.

The log youphptube.log just says [15-Oct-2019 13:10:03 Europe/London] Sending SMTP Email

is tehre a file I can modify to get better info?

i.e I need to add 
echo "Mailer Error: " . $mail->ErrorInfo;

and get the correct error info.

thanks

**Comment by DanielnetoDotCom** [comment]
Please more details, also the log file

**Comment by millzee01** [comment]
sorry i pressed the wrong button :-)

**Comment by DanielnetoDotCom** [comment]
I can not see any problem , check your error log

**Comment by millzee01** [comment]
is youphptube.log the error log in the videos folder? because this only shows 
[15-Oct-2019 13:10:03 Europe/London] Sending SMTP Email

is there anywhere I can set smtp debug level to 2?

**Comment by DanielnetoDotCom** [comment]
Probably you will need to hard code it

**Comment by millzee01** [comment]
ok, 

i'll find the file that does the work and hard code it.

thanks

**Comment by millzee01** [comment]
HI, just following on from this strange issue:

i hard coded functions.php to log the $mail var just after setSiteSendMessage($mail) in sendSiteEmail()

the output was:
[15-Oct-2019 22:26:38 Europe/London] Sending SMTP Email
[15-Oct-2019 22:28:25 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined function ddosProtection() in /var/www/html/objects/include_config.php:50
Stack trace:
#0 /var/www/html/videos/configuration.php(29): require_once()
#1 /var/www/html/view/configurations.php(4): require_once('/var/www/html/v...')
#2 {main}
  thrown in /var/www/html/objects/include_config.php on line 50
[15-Oct-2019 22:28:34 Europe/London] Sending SMTP Email -> setSiteSendMessage

which seems to point to the ddos portection.

does this make any sense?

only modification I have made is the error_log(print_r($mail, true)); call.

**Comment by millzee01** [comment]
This issue was down to me putting the site into maintenance mode.  All is ok now.
