### ISSUE TITLE
Default home page

### ISSUE THREAD

**Issue by millzee01** [YouPHPTube/YouPHPTube#2148]
Hi, is there a way I can set the default page on load as "My Channel"? instead of home?

or redirect home to my channel?

**Comment by DanielnetoDotCom** [comment]
I guess you are talking about this.

![image](https://user-images.githubusercontent.com/18009293/66852248-ecc1ee80-ef52-11e9-86e5-2dfcc6b3e65d.png)

**Comment by millzee01** [comment]
awesome! thank you
