### ISSUE TITLE
Saving account issue/bug

### ISSUE THREAD

**Issue by millzee01** [YouPHPTube/YouPHPTube#2149]
Hi,  

there are a couple of issues I have encountered with the edit account page.

#1.  New password being auto added.  Suspect this is because the type is set to "password", the browser auto fills this in so when you press "save" it asks for the password confirmation (which is blank) because we don't want to change our password.  To resolve this I set the type as "new-password".  Granted it doesnt show ****** but this isn't an issue.

#2 When logged in as admin,  if I upload an mage and background then hit save it asks me to fill in the search field so I cant update my profile.

have attached screenshot below:
![edit-account-issue](https://user-images.githubusercontent.com/28105720/66850378-9c598980-ef70-11e9-9d6e-4998a2be1016.jpg)

**Comment by DanielnetoDotCom** [comment]
I just send a fix for error 1, but I could not reproduce error 2.

can you please try on the demo site?

**Comment by millzee01** [comment]
the demo site doesnt do #2.  I suspect it mught be down to the theme i am using (youtube2)

will do some more testing and post back
