### ISSUE TITLE
forgot password bug - happens on demo site as well

### ISSUE THREAD

**Issue by millzee01** [YouPHPTube/YouPHPTube#2150]
to replicate on demo site:

type user1234 as user name on site
click forgot password

enter captcha (in fact it makes no difference if you put a captcha in or not)

click "Yes send it"

the progress bars stays active and nothing else.  

You then need to reload the page to start again.

there also seems to be an issue when resetting admin password as well as clicking the btnReloadCapcha where it doesnt do anything.

**Comment by DanielnetoDotCom** [comment]
Thanks for that, the bug is fixed
