### ISSUE TITLE
Since Update to Version 7.7 all Videos are public

### ISSUE THREAD

**Issue by soenkekueper** [YouPHPTube/YouPHPTube#2151]
I've updated our YouPhpTube to version 7.7 last weekend. Since then all videos are public (i.e. on home page you can see them). Starting Video is not possible. Public Media is disabled for the videos.

**Comment by DanielnetoDotCom** [comment]
try this option 

![image](https://user-images.githubusercontent.com/18009293/66938237-3aa02a80-f017-11e9-87ff-9bd38e3af70c.png)

**Comment by soenkekueper** [comment]
Hey,

thanks for the hint, but it didn't work.
Option was not set, but didn't change anything.

**Comment by DanielnetoDotCom** [comment]
Sorry but I can not fix if I can not reproduce the error

**Comment by soenkekueper** [comment]
Now it works... Perhaps any caching issue when changing the gallery settins?
I've previously just logged out and did an refresh...
Thanks for the hint!
