### ISSUE TITLE
reset password link redirects to https://domain/user

### ISSUE THREAD

**Issue by millzee01** [YouPHPTube/YouPHPTube#2152]
Hi,

i have setup smtp and when i get the recovery password link, when i click the "Reset password" which points to: https://domain.com/recoverPass?user=carl.miller@ntlworld.com&recoverpass=dab5220b03295c9cc6dd9c5f73793725

for some reason this auto redirects to https://domain.com/user

should there be a route to the recoverPass script i am missing?

**Comment by DanielnetoDotCom** [comment]
the URL https://domain.com/recoverPass?user=carl.miller@ntlworld.com&recoverpass=dab5220b03295c9cc6dd9c5f73793725 is correct.

Why do you think it should be different

**Comment by millzee01** [comment]
Yes the link is correct its when I click the link it just redirects to https://domain.com/user and shows the login prompt not the reset password page.

When i test on the demo site the link in the url stays as https://domain.com/recoverPass?user=carl.miller@ntlworld.com&recoverpass=dab5220b03295c9cc6dd9c5f73793725 not https://domain.com/user and presents the change password screen.  

this doesn't happen on my site

**Comment by DanielnetoDotCom** [comment]
Sorry but I can not fix if I can not reproduce the error

**Comment by millzee01** [comment]
no probs, i'm just going though disabling plugins to track it down.  Will post when i find the problem.

**Comment by millzee01** [comment]
Hi, 

i have just tried resetting my password on the demo site and now i get a json page appearing:

https://demo.youphptube.com/recoverPass?user=millzee&recoverpass=f1204338f395c4cb0f6cf5f47792cb56

maybe linked to my issue?

**Comment by DanielnetoDotCom** [comment]
No, it is nothing to do with your error.

I just sent a fix for this error (demo site)

**Comment by millzee01** [comment]
Hi,

If you enable the "userMustBeLoggedIn" in customize user plugin it causes the issue reported.

Disable the setting and the page shows as it should.

**Comment by DanielnetoDotCom** [comment]
Thanks, can you please update and try again?

**Comment by millzee01** [comment]
Spot on! nice fix
