### ISSUE TITLE
Enable Live(Link) Plugin

### ISSUE THREAD

**Issue by TLCReuver** [YouPHPTube/YouPHPTube#2153]
Hi Daniel,

Since the last update i can't enable & disable the Live & LiveLink plugin (also on demosite)
It jumps back to the last state and no errors found in the logs.

![Snap1](https://user-images.githubusercontent.com/39981177/66960967-e83e2880-f06d-11e9-95e8-536953118906.jpg)
![Snap2](https://user-images.githubusercontent.com/39981177/66960983-f1c79080-f06d-11e9-8d5f-a5f3a1fc378e.jpg)

**Comment by XemTube-TV** [comment]
The error occurs on all plugins. It is not possible to change its on or off status.

**Comment by DanielnetoDotCom** [comment]
Thanks for the notice, can you please update and try again?

**Comment by TLCReuver** [comment]
Thankz, that problem is fixed but when:

Live = DISABLED  ==> "Live" is still in top_page
![Snap1](https://user-images.githubusercontent.com/39981177/66982311-0cbdf300-f0b6-11e9-9ce1-d81207b1efc7.jpg)
![Snap2](https://user-images.githubusercontent.com/39981177/66982329-18111e80-f0b6-11e9-8020-833866a1a891.jpg)

Live = ENABLED  ==> "Live" is **double** in top_page
![Snap3](https://user-images.githubusercontent.com/39981177/66982429-5c042380-f0b6-11e9-9a85-4f55d0a1c592.jpg)
![Snap4](https://user-images.githubusercontent.com/39981177/66982439-61fa0480-f0b6-11e9-8207-d4aecc12acf3.jpg)

**Comment by DanielnetoDotCom** [comment]
I am not sure, I have never seen that

It looks like your plugin table messed up something due to the previews bug.

do you mind to truncate/clean your plugins table?

it must be done manually

**Comment by TLCReuver** [comment]
Cleaning the Plugin_table resolved this problem.
Thanks.
