### ISSUE TITLE
API

### ISSUE THREAD

**Issue by millzee01** [YouPHPTube/YouPHPTube#2155]
Hi, 
does the api allow group creation and adding users to groups / categories?

and is there built in functionality that allows me to only show categories based on group membership?

or is there a plugin that does this?

if not, can you pm me with a cost to create a plugin/customization to add the following to the navbar:

I am automatically generating groups and categories (with the same name) based on user types and would like an option to

#1 Only show users personal channel videos when they click "My Channel" (not group/category videos even if they are a member of a group)

#2 Have a new "channel type view" showing same group videos only

#3 Give a group member the ability to add videos to a group channel / catelog

#4 Allow group admins to add/delete sub groups to main group so members can place and catalog videos in the group channel

I basically want to to add functionality where I allow users to share videos based on group / catalog membership.  And restrict this videos to anyone else.

**Comment by DanielnetoDotCom** [comment]
Our API does not generate Groups or Categories yet, you can check here more API details

https://github.com/YouPHPTube/YouPHPTube/wiki/API

**Comment by millzee01** [comment]
thanks for info
