### ISSUE TITLE
Configure your homepage name

### ISSUE THREAD

**Issue by XemTube-TV** [YouPHPTube/YouPHPTube#2156]
I just installed the new YouPHPTube. How to configure the domain homepage path from http://xemhaivl.online/YouPHPTube to the link http://xemhaivl.online.

**Comment by DanielnetoDotCom** [comment]
For my self I use apache virtual hosts.

you should be able to find something about it on Google

also you can move all the files and dir to the html directory

**Comment by fst24sx** [comment]
step 1. change name of video directory folder from "YouPHPTube" to whatever you want or move the videos to the html directory
step 2. sudo nano /var/www/html/NEWDIRECTORYNAME/videos/configuration.php
- change directory path accordingly
-save file

you can do the same thing with the encoder. make sure to change proper URL in the configuration page of admin panel.
