### ISSUE TITLE
can not login

### ISSUE THREAD

**Issue by codelabinf** [YouPHPTube/YouPHPTube#2157]
Hello, my query is because I modified the login options from the plugins as admin and when I want to re-enter I can't do it. It tells me that I have to register and it does not allow me to register since I canceled it. Obviously I made several mistakes when setting up. Could someone tell me how to enter again as admin? Thank you so much!
------------------------------------------------------------------------------------------------------------------------------
Hola, mi consulta es porque modifiqué las opciones de login desde los plugins como admin y al querer reingresar no lo puedo hacer. Me dice que me tengo que registrar y no me permite registrarme ya que esto lo anulé. Evidentemente cometí varios errores al configurar. ¿Alguien me podría decir cómo poder inresar de nuevo como admin? Muchas Gracias!

**Comment by DanielnetoDotCom** [comment]
try to truncate your plugins table, all plugins will be reset and you may be able to login again

**Comment by codelabinf** [comment]
Thank you! How should i do that? What file should I modify?

**Comment by DanielnetoDotCom** [comment]
First thing, you MUST know how to deal with MySQL

then truncate the table (IT IS NOT A FILE CHANGE)

If you do not know how to do, google to see how to truncate a table

**Comment by codelabinf** [comment]
Thank you so much!

**Comment by codelabinf** [comment]
It worked perfect!
With "TRUNCATE TABLE plugins;"
Thank you so much!
