### ISSUE TITLE
Autoplay Livestremin

### ISSUE THREAD

**Issue by mikweb2017** [YouPHPTube/YouPHPTube#2160]
Hi Daniel,
Can Yon Autoply for livestreming Again Fix?

https://demo.youphptube.com/plugin/Live/?c=HillsongUNITED

![autoply](https://user-images.githubusercontent.com/30271757/67073477-79ed8900-f187-11e9-874c-9c028c105197.PNG)

**Comment by DanielnetoDotCom** [comment]
the autoplay was never removed, I also update a double check to autoplay, but I am pretty sure it is a browser that is blocking the autoplay and this is expected. Browsers now will not autoplay by default anymore, unless the video is muted

**Comment by DanielnetoDotCom** [comment]
but now looks like it is autoplaying, at least the demo site in my browser is working.

**Comment by mikweb2017** [comment]
yes  only  Firefox  dont workt

**Comment by DanielnetoDotCom** [comment]
I tested it in firefox and it works with the demo site

**Comment by mikweb2017** [comment]
![live](https://user-images.githubusercontent.com/30271757/67096405-6870a500-f1b8-11e9-9dc5-aef564f285b6.PNG)

for me dont work

**Comment by mikweb2017** [comment]
ok  i understandt my Problem
