### ISSUE TITLE
Urdu translations

### ISSUE THREAD

**Issue by Lablnet** [YouPHPTube/YouPHPTube#2161]
Is am allow to translate to URDU?

and should only i have to translate ```..\locale\us.php```?

**Comment by DanielnetoDotCom** [comment]
this will be a pleasure to add this translation

I am not sure what file is the most complete, but if you find something that is not translated, you just need to add it into the file.

**Comment by Lablnet** [comment]
ok sure, assign me to that issue

**Comment by DanielnetoDotCom** [comment]
Hi, I am not sure how to "transfer to you" but feel free to make a pull request.
