### ISSUE TITLE
UserControl Plugin

### ISSUE THREAD

**Issue by Donnerstein** [YouPHPTube/YouPHPTube#2165]
Hi.
Probably it is not a bug, but after installing the UserControl plugin, the "Ban" button will not appear on the user management page. Is there an extra option for this?

![image](https://user-images.githubusercontent.com/52116237/67143629-ad0a4800-f26d-11e9-84c5-141c38e55e1e.png)

![image](https://user-images.githubusercontent.com/52116237/67143672-18541a00-f26e-11e9-81dd-b601a707f9d3.png)

greeting
Thunderstone

**Comment by DanielnetoDotCom** [comment]
is the plugin enabled and tables installed?

**Comment by Donnerstein** [comment]
yes

**Comment by DanielnetoDotCom** [comment]
Are you running the YouPHPTube version 7.7?

And is the UserControll enabled?

**Comment by Donnerstein** [comment]
Yes
![image](https://user-images.githubusercontent.com/52116237/67147048-675f7680-f291-11e9-868a-bae285e9e284.png)

and Yes
![image](https://user-images.githubusercontent.com/52116237/67147060-7e9e6400-f291-11e9-9784-4cf2c881a6e1.png)

**Comment by Donnerstein** [comment]
I have a guess.
The UserControl plugin will generate 2 tables if I understand it correctly. Namely "bans" and "users_login-History"
I have selected the button to install the tables, it behaves as usual, the "Processing ..." dialog is displayed and ends, no errors.
But in the database, these tables do not exist, but it may also be that I do not understand it correctly, so here's the list of tables.
I installed the Chat2 plugin a few hours earlier, this works without problems. So it should not be a problem with the database system.

![image](https://user-images.githubusercontent.com/52116237/67147241-8ced7f80-f293-11e9-9bfe-9ab1f33b85c5.png)

**Comment by XemTube-TV** [comment]
You must purchase the User Control plugin to have the Ban function

**Comment by Donnerstein** [comment]
@XemTube-TV 
I know, I bought it, otherwise I would not have been able to instal it.

**Comment by Donnerstein** [comment]
I installed the "install.sql" file with phpmyadmin into the database. That worked. But the ban button is still missing and the logins are not recorded in the table "users_login-History".

**Comment by DanielnetoDotCom** [comment]
Hi, the logins will only be there after the logins attempt, after the plugin is installed.

you can not recover the IPs from the logins that were made before the plugin installation


is the ban button still missing?

**Comment by Donnerstein** [comment]
Yeah, I know that it can not look into the past :)
I have already tested this on the demo page.
But no, Even with new logins, the data is not recorded, and the ban button is still not available.
What else does this plugin do except install the tables, if I know I can do it by hand.

greeting

**Comment by DanielnetoDotCom** [comment]
Hi, I found the bug, please update your streamer, turn off and turn on the plugin again.

**Comment by Donnerstein** [comment]
Worked.
Man gets an impression of how much work you have with the Projeckt

Thank you very much
