### ISSUE TITLE
Chat2 pictures

### ISSUE THREAD

**Issue by Donnerstein** [YouPHPTube/YouPHPTube#2167]
In chat2 Plugin Can not load pictures into the chat when you are in a one-to-one conversation, the error is also on the demo page.

greeting
Thunderstone

![image](https://user-images.githubusercontent.com/52116237/67149116-9f71b400-f2a7-11e9-8fbf-e4456218ea0a.png)

**Comment by DanielnetoDotCom** [comment]
Thanks for the report, I just sent a fix for that, please download your Chat plugin again
