### ISSUE TITLE
ClipBucket V4.2 RC1 Dashboard

### ISSUE THREAD

**Issue by felipe5512** [YouPHPTube/YouPHPTube#2181]
Dashboard options do not appear in admin area

**Comment by felipe5512** [comment]
See here the error


http://felipedesenvolvimento.site.com.br/wp-content/uploads/sites/277710/2019/10/Screenshot_2019-10-23-11-33-11.png

**Comment by DanielnetoDotCom** [comment]
OMG, what are you talking about?

**Comment by felipe5512** [comment]
![Screenshot_2019-10-23-11-33-11](https://user-images.githubusercontent.com/51463977/67412657-0e942480-f596-11e9-99fe-31b08de102e0.png)
No options appea

**Comment by felipe5512** [comment]
![Screenshot_2019-10-23-13-10-15](https://user-images.githubusercontent.com/51463977/67412914-924e1100-f596-11e9-92f2-5291ab5b66ba.png)
No options appea

**Comment by felipe5512** [comment]
I installed this version but no options appear

**Comment by DanielnetoDotCom** [comment]
Here is YouPHPTube project, you are screenshot the Clipbucket software, we have nothing to do with them.

it is a completely different app

**Comment by felipe5512** [comment]
OK sorry

**Comment by felipe5512** [comment]
And I could not install youphptube then I tried this other
