### ISSUE TITLE
Update doesn't work.

### ISSUE THREAD

**Issue by TLCReuver** [YouPHPTube/YouPHPTube#2185]
The Update function in the Admin_panel doesn't work anymore (also on Demo_site)

Regards, Theo.

**Comment by akhilleusuggo** [comment]
same here , not working

**Comment by DanielnetoDotCom** [comment]
Hi, sorry about that.

I just sent a new update.

Please update your files and try again

**Comment by TLCReuver** [comment]
The Update_function is  correct now.

Thanks
