### ISSUE TITLE
Unknown error on new install.

### ISSUE THREAD

**Issue by inferno-prime** [YouPHPTube/YouPHPTube#2189]
I seem to be getting an unkwon error on a brand new install. I told the database to only create the tables (which the previous versions had no trouble doing).

**Comment by DanielnetoDotCom** [comment]
can you please share your apache2/error.log ?

**Comment by inferno-prime** [comment]
just checked but nothing is listed from last night. What can I do ?

**Comment by DanielnetoDotCom** [comment]
when you try a new install, and rises an error.

should be something in your error.log file

**Comment by XemTube-TV** [comment]
> just checked but nothing is listed from last night. What can I do ?

@inferno-prime 
please try reinstalling and capture the error during the installation process. If you need assistance installing YouPHPTube on your service, you can contact me.
