### ISSUE TITLE
Embed Videos are not working with the Theatre View Plugin

### ISSUE THREAD

**Issue by JoshWho** [YouPHPTube/YouPHPTube#2197]
I cannot compress the video player when it is embedded from youtube or other places. 

<img src="https://static.buddylist.co/x/nooption.png" style='width:100%;' border="0" alt="Null">

**Comment by DanielnetoDotCom** [comment]
I just sent an update that I am expecting to add the button on embed IF you have the disableYoutubePlayerIntegration = false in the Customize advanced

**Comment by JoshWho** [comment]
Working good now. Thank you Daniel.
