### ISSUE TITLE
Embedded Live Stream shows chat over half of the player. 

### ISSUE THREAD

**Issue by JoshWho** [YouPHPTube/YouPHPTube#2206]
When people embed their live streams on their website the chat blocks half of it.
<img src="https://static.buddylist.co/x/chatlive.png" border="0" alt="Null">

**Comment by DanielnetoDotCom** [comment]
Did you see this?

![image](https://user-images.githubusercontent.com/18009293/68023253-6b25cc80-fc85-11e9-82e3-0ebb376130b2.png)

**Comment by JoshWho** [comment]
I already have it set that way. This is not a issue with normal embeds, this is only the Live Stream Player that is showing it when embedded.

**Comment by DanielnetoDotCom** [comment]
Hi

I found the problem, it is related to Livestream videos correct?

I have an update on Chat2 plugin to fix it.

**Comment by JoshWho** [comment]
Yes. Live videos that are embedded on external sites

**Comment by JoshWho** [comment]
Fixed
