### ISSUE TITLE
I want to limit access to users being able to select the encoder from the Encoder Network

### ISSUE THREAD

**Issue by JoshWho** [YouPHPTube/YouPHPTube#2207]
Users keep using both encoders on the Encoder Network page at the same time. 

I want to eliminate that by hiding the other encoder that is not being used.

Let the Encoder Network Select which encoder to use and only show that one.

From this
<img src="https://static.buddylist.co/x/encoder1.png" border="0" alt="Null">

To this
<img src="https://static.buddylist.co/x/encoder2.png" border="0" alt="Null">

**Comment by DanielnetoDotCom** [comment]
try to use your configuration like this

![image](https://user-images.githubusercontent.com/18009293/68023409-c9eb4600-fc85-11e9-87ca-0c3ce553d36c.png)

**Comment by JoshWho** [comment]
That is the setting I have selected.

**Comment by JoshWho** [comment]
Well I came up with a simple solution. I added a New DIV to the encoder part on the left and have achieved exactly what I was looking for. May not look the best but it is exactly what I was wanting. Now users do not see there is 2 encoders and can't use both at the same time any more.

This is the New code for file /var/www/html/YouPHPTube/Network/view/index.php

Somewhere under line # 186 add <div style="display: none;"> and the Close Tag </div> after the line

```
<span id="maxfilesize<?php echo $value['id']; ?>" class="label label-default">Max File Size 0Mb</span>
                                            </div>

                                        </div>
                                    </li>
```
Example:

```
<div style="display: none;">
                                            <div data-target="#l<?php echo $value['id']; ?>" data-toggle="tab">
                                            <div class="ellipsis">
                                                <span class="account-type">JoshWho TV</span>
                                                <span id="recommended<?php echo $value['id']; ?>" class="label label-success recommended" style="display: none;"><i class="fa fa-check"></i> Recommended</span><br/>
                                                <span id="label<?php echo $value['id']; ?>" class="label label-danger">Offline</span> <span class="account-amount" id="queuesize<?php echo $value['id']; ?>" >Queue Size 0</span><br/>
                                                <a href="https://www.joshwhotv.com" class="account-link">https://www.joshwhotv.com</a><br>
                                                <span id="ping<?php echo $value['id']; ?>" class="label label-default">Searching Ping ...</span>
                                                <span id="maxfilesize<?php echo $value['id']; ?>" class="label label-default">Max File Size 0Mb</span>
                                            </div>

                                        </div>
                                    </li>
</div>
```

And Now I have exactly what I was looking for.
<img src="https://static.buddylist.co/x/encoderfixed.png" style='width:100%;' border="0" alt="Null">

**Comment by JoshWho** [comment]
Would like to figure out how to expand the right part to the full screen but this works for now.

Please have a look at it @DanielnetoDotCom when u get a chance so u can see the change on my site. Works good and now I know the encoders won;t get maxed all by one person.

**Comment by JoshWho** [comment]
I found it. I edited this line and changed the width to 115%

`<iframe src="<?php echo $value['siteURL']; ?>?noNavbar=1&webSiteRootURL=<?php echo urlencode($_SESSION["login"]->streamer); ?>&user=<?php echo $_SESSION["login"]->user; ?>&pass=<?php echo $_SESSION["login"]->pass; ?>" frameborder="0" style="overflow:hidden;height:100%;width:115%;" height="10%" width="115%"></iframe>
`

**Comment by JoshWho** [comment]
Now it looks really good on mobile and desktop .

**Comment by DanielnetoDotCom** [comment]
I am still confused about what you want, but I do not think it is a good solution.

Why dont access the encoder directly instead accesss the network (but the network will decide what encoder access).

**Comment by JoshWho** [comment]
How I have it right now is what I was looking for. I am not understanding what you mean by Use the encoder directly.

I am thinking if I just use the encoder url then all uploads will just go to the one encoder.

**Comment by DanielnetoDotCom** [comment]
Based on the screenshots you post here you are in the Encoder tetwork with out the left menu

**Comment by JoshWho** [comment]
Correct. Exactly. And also without the ping. This makes it to where the user uploading now only has one choice and it is what gets selected by the aggregator.
