### ISSUE TITLE
Uploading Avatar / Banner Returns as error Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by ChisdealHD** [YouPHPTube/YouPHPTube#2211]
Error getting threw Apache2 threw Ubuntu 18.04 LTS:

was working fine yesterday and now turns round error this way Today. any ideas for Fix this backtrace issue from uploading own images.

This error i think knowned since people getting uploading issues from my side of company, LiveHQ and few other places that on my Projects. i wondering if something up prevent this issue or is it Server basses issue.

`[Fri Nov 01 10:37:02.912214 2019] [core:error] [pid 10384] [client ip:port] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to on' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
`

**Comment by DanielnetoDotCom** [comment]
For me looks like a DNS or a apache configuration error

does not looks like an PHP error for me

**Comment by ChisdealHD** [comment]
so thinking its DNS issue?

**Comment by ChisdealHD** [comment]
this only happens when uploading image

**Comment by DanielnetoDotCom** [comment]
The problem is I can not reproduce this error.

If you can reproduce it on demo site it will help to find a solution.

**Comment by ChisdealHD** [comment]
you could try on our site, since i have no clue will happen your demo 1.

**Comment by DanielnetoDotCom** [comment]
In your site does not work, I don't know what did you install on it and how did you install the YouPHPTube

On demo site I know what exactly modules and configurations I have.

**Comment by ChisdealHD** [comment]
its working all stuff was working yesterday just today logo , banner uploads broken

**Comment by ChisdealHD** [comment]
im might found out, it was cache issue that cloudflare didn't like files. but something i cant fix because lack of not solving that issue and tried switch server / VPS provider but i have no details that fixed it. because keeps cache self.

so i going close this ticket because its cloudflare issue.
