### ISSUE TITLE
Videos doesn't play

### ISSUE THREAD

**Issue by TLCReuver** [YouPHPTube/YouPHPTube#2218]
Hi Daniel,

Since the last video.php_update from Saturday videos doesn't play anymore (also on Demosite)

![Snap1](https://user-images.githubusercontent.com/39981177/68104633-1c25a480-fedc-11e9-9b29-1a52685e946c.jpg)

Regards,
Theo

**Comment by DanielnetoDotCom** [comment]
I am so sorry, you were right, it was a conflict with the new update and the SecureDirectory plugin.

but it should work now.

**Comment by TLCReuver** [comment]
Okay, videos are playing now.

Thanks.
