### ISSUE TITLE
Embed video description

### ISSUE THREAD

**Issue by angelawong** [YouPHPTube/YouPHPTube#2224]
I have no problems embedding the video onto a web page but is there a way to embed the description of the video as well? Any help or advice would be most appreciated. Thanks so much.

**Comment by DanielnetoDotCom** [comment]
We do not have an embed description page.

to create it, it will require some code. you can do it by yourself (Must Know PHP of course)

or you can hire us to create this feature for you (if you want, email us for a quote).

**Comment by angelawong** [comment]
Thanks so much, Daniel. I am going to take a stab at it and see how it goes.

Cheers,
Angela
