### ISSUE TITLE
Unknown Error!

### ISSUE THREAD

**Issue by jackwander** [YouPHPTube/YouPHPTube#2226]
Does anyone encounter an error saying **Sorry! Unknown error!**?

This is when i click install now. 

Im following this guide: https://github.com/YouPHPTube/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-YouPHPTube-version-4.x-or-newer

OS: Ubuntu 18.04.3 LTS
RAM: 4GB

![error](https://user-images.githubusercontent.com/32908963/68303797-8a868480-00df-11ea-824f-23820e1f57b6.jpg)

**Comment by XemTube-TV** [comment]
try reinstalling with a new database name to see if it succeeds. If you need help, please contact me again.

**Comment by DanielnetoDotCom** [comment]
Check your apache error log for some clue.

**Comment by jackwander** [comment]
> try reinstalling with a new database name to see if it succeeds. If you need help, please contact me again.

I can submit now the error is in the php but now this is what i got when i submit it.

![Selection_013](https://user-images.githubusercontent.com/32908963/68306527-a9d3e080-00e4-11ea-8521-16d83978b4a4.png)

**Comment by DanielnetoDotCom** [comment]
a blank page?

again, check your log file

**Comment by DanielnetoDotCom** [comment]
Check your apache error, looks like you have to fix something in your DNS


FYI, your server dows not looks like the recomended Ubuntu server.

**Comment by jackwander** [comment]
Will do that.
> Check your apache error, looks like you have to fix something in your DNS

What's the recommended Ubuntu server sir?
> FYI, your server dows not looks like the recomended Ubuntu server.

**Comment by DanielnetoDotCom** [comment]
Ubuntu 16.04 or 18.04

The tutorial you have mention above is for Ubuntu 18.04

**Comment by jackwander** [comment]
Yes sir, my OS is Ubuntu 18.04.3.

> Ubuntu 16.04 or 18.04
> 
> The tutorial you have mention above is for Ubuntu 18.04

**Comment by jackwander** [comment]
I solved it. I just delete the project file and redo the setup.
