### ISSUE TITLE
I have uploaded a video on my phptube www.gappedtube.com and only thing that happened is go to blank page

### ISSUE THREAD

**Issue by ucmafialtd** [YouPHPTube/YouPHPTube#2233]
have uploaded a video on my phptube www.gappedtube.com

**Comment by DanielnetoDotCom** [comment]
Hi, please check your Apache error log file for some clue

**Comment by ucmafialtd** [comment]
How do I do that

**Comment by DanielnetoDotCom** [comment]
https://lmgtfy.com/?q=how+to+find+apache+error+log+on+ubuntu&s=g

**Comment by ucmafialtd** [comment]
It's showing no error you click on the video and it just goes to a blank white page

**Comment by DanielnetoDotCom** [comment]
we can try to find what is the problem when you share your apache error log file here

**Comment by ucmafialtd** [comment]
jquery-3.3.1.min.js:2 Uncaught TypeError: $(...).flagStrap is not a function
    at HTMLDocument.<anonymous> (?type=all:368)
    at l (jquery-3.3.1.min.js:2)
    at c (jquery-3.3.1.min.js:2)
(anonymous) @ ?type=all:368
l @ jquery-3.3.1.min.js:2
c @ jquery-3.3.1.min.js:2
setTimeout (async)
w.readyException @ jquery-3.3.1.min.js:2
(anonymous) @ jquery-3.3.1.min.js:2
l @ jquery-3.3.1.min.js:2
c @ jquery-3.3.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
fire @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
c @ jquery-3.3.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
fire @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
ready @ jquery-3.3.1.min.js:2
_ @ jquery-3.3.1.min.js:2
jquery-3.3.1.min.js:2 Uncaught TypeError: $(...).webuiPopover is not a function
    at HTMLDocument.<anonymous> (?type=all:578)
    at l (jquery-3.3.1.min.js:2)
    at c (jquery-3.3.1.min.js:2)
(anonymous) @ ?type=all:578
l @ jquery-3.3.1.min.js:2
c @ jquery-3.3.1.min.js:2
setTimeout (async)
w.readyException @ jquery-3.3.1.min.js:2
(anonymous) @ jquery-3.3.1.min.js:2
l @ jquery-3.3.1.min.js:2
c @ jquery-3.3.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
fire @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
c @ jquery-3.3.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
fire @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
ready @ jquery-3.3.1.min.js:2
_ @ jquery-3.3.1.min.js:2
?type=all:550 Uncaught TypeError: $(...).btsListFilter is not a function
    at Object.success (?type=all:550)
    at u (jquery-3.3.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.3.1.min.js:2)
    at k (jquery-3.3.1.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery-3.3.1.min.js:2)
5:56 pm
Just now.

**Comment by DanielnetoDotCom** [comment]
this is NOT your apache log

**Comment by ucmafialtd** [comment]
[Wed Nov 06 00:10:50.651493 2019] [ssl:warn] [pid 26447] AH01909: localhost:445:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 00:10:50.651845 2019] [ssl:warn] [pid 26447] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 00:10:50.695926 2019] [ssl:warn] [pid 26448] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 00:10:50.696288 2019] [ssl:warn] [pid 26448] AH01909: localhost:445:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 00:10:50.696627 2019] [ssl:warn] [pid 26448] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 00:10:50.699723 2019] [mpm_prefork:notice] [pid 26448] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2t configured -- resuming normal operations
[Wed Nov 06 00:10:50.699746 2019] [core:notice] [pid 26448] AH00094: Command line: '/usr/sbin/apache2'
[Wed Nov 06 06:25:01.878438 2019] [mpm_prefork:notice] [pid 26448] AH00171: Graceful restart requested, doing restart
[Wed Nov 06 06:25:01.937916 2019] [ssl:warn] [pid 26448] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 06:25:01.938386 2019] [ssl:warn] [pid 26448] AH01909: localhost:445:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 06:25:01.938781 2019] [ssl:warn] [pid 26448] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 06:25:01.938956 2019] [mpm_prefork:notice] [pid 26448] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2t configured -- resuming normal operations
[Wed Nov 06 06:25:01.938963 2019] [core:notice] [pid 26448] AH00094: Command line: '/usr/sbin/apache2'
[Thu Nov 07 03:05:41.639381 2019] [ssl:error] [pid 29880] [client 104.248.210.29:52502] AH02042: rejecting client initiated renegotiation
[Thu Nov 07 06:25:01.241871 2019] [mpm_prefork:notice] [pid 26448] AH00171: Graceful restart requested, doing restart
[Thu Nov 07 06:25:01.287970 2019] [ssl:warn] [pid 26448] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Thu Nov 07 06:25:01.288347 2019] [ssl:warn] [pid 26448] AH01909: localhost:445:0 server certificate does NOT include an ID which matches the server name
[Thu Nov 07 06:25:01.288689 2019] [ssl:warn] [pid 26448] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
[Thu Nov 07 06:25:01.288832 2019] [mpm_prefork:notice] [pid 26448] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2t configured -- resuming normal operations
[Thu Nov 07 06:25:01.288838 2019] [core:notice] [pid 26448] AH00094: Command line: '/usr/sbin/apache2'

**Comment by ucmafialtd** [comment]
sorry im new

**Comment by DanielnetoDotCom** [comment]
no clue looks like is nothing about your PHP code, I can not see any PHP error

maybe something about your server configuration

**Comment by ucmafialtd** [comment]
[Tue Nov 05 03:45:32.900299 2019] [mpm_prefork:notice] [pid 568] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2l configured -- resuming normal operations
[Tue Nov 05 03:45:32.900357 2019] [core:notice] [pid 568] AH00094: Command line: '/usr/sbin/apache2'
[Tue Nov 05 03:45:46.298308 2019] [mpm_prefork:notice] [pid 568] AH00169: caught SIGTERM, shutting down
[Tue Nov 05 03:45:46.366782 2019] [ssl:warn] [pid 2537] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 03:45:46.367093 2019] [ssl:warn] [pid 2537] AH01909: localhost:445:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 03:45:46.367341 2019] [ssl:warn] [pid 2537] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 03:45:46.409783 2019] [ssl:warn] [pid 2538] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 03:45:46.410050 2019] [ssl:warn] [pid 2538] AH01909: localhost:445:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 03:45:46.410288 2019] [ssl:warn] [pid 2538] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 03:45:46.413213 2019] [mpm_prefork:notice] [pid 2538] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2l configured -- resuming normal operations
[Tue Nov 05 03:45:46.413231 2019] [core:notice] [pid 2538] AH00094: Command line: '/usr/sbin/apache2'
[Tue Nov 05 03:45:53.004664 2019] [mpm_prefork:notice] [pid 2538] AH00169: caught SIGTERM, shutting down
[Tue Nov 05 03:45:53.067166 2019] [ssl:warn] [pid 3727] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 03:45:53.067479 2019] [ssl:warn] [pid 3727] AH01909: localhost:445:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 03:45:53.067747 2019] [ssl:warn] [pid 3727] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 03:45:53.109801 2019] [ssl:warn] [pid 3728] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 03:45:53.110068 2019] [ssl:warn] [pid 3728] AH01909: localhost:445:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 03:45:53.110313 2019] [ssl:warn] [pid 3728] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 03:45:53.113289 2019] [mpm_prefork:notice] [pid 3728] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2l configured -- resuming normal operations
[Tue Nov 05 03:45:53.113310 2019] [core:notice] [pid 3728] AH00094: Command line: '/usr/sbin/apache2'
[Tue Nov 05 03:46:22.887457 2019] [mpm_prefork:notice] [pid 3728] AH00169: caught SIGTERM, shutting down
[Tue Nov 05 03:46:52.743724 2019] [ssl:warn] [pid 19164] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 03:46:52.744023 2019] [ssl:warn] [pid 19164] AH01909: localhost:445:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 03:46:52.744288 2019] [ssl:warn] [pid 19164] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 03:46:52.793371 2019] [ssl:warn] [pid 19165] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 03:46:52.793633 2019] [ssl:warn] [pid 19165] AH01909: localhost:445:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 03:46:52.793899 2019] [ssl:warn] [pid 19165] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 03:46:52.796878 2019] [mpm_prefork:notice] [pid 19165] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2t configured -- resuming normal operations
[Tue Nov 05 03:46:52.796895 2019] [core:notice] [pid 19165] AH00094: Command line: '/usr/sbin/apache2'
[Tue Nov 05 03:47:02.859589 2019] [mpm_prefork:notice] [pid 19165] AH00169: caught SIGTERM, shutting down
[Tue Nov 05 03:48:56.666662 2019] [ssl:warn] [pid 516] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 03:48:56.668009 2019] [ssl:warn] [pid 516] AH01909: localhost:445:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 03:48:56.668258 2019] [ssl:warn] [pid 516] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 03:48:56.817970 2019] [ssl:warn] [pid 670] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 03:48:56.818231 2019] [ssl:warn] [pid 670] AH01909: localhost:445:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 03:48:56.818484 2019] [ssl:warn] [pid 670] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 03:48:56.825218 2019] [mpm_prefork:notice] [pid 670] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2t configured -- resuming normal operations
[Tue Nov 05 03:48:56.825247 2019] [core:notice] [pid 670] AH00094: Command line: '/usr/sbin/apache2'
[Tue Nov 05 23:33:18.671271 2019] [mpm_prefork:notice] [pid 670] AH00169: caught SIGTERM, shutting down
[Tue Nov 05 23:33:18.739994 2019] [ssl:warn] [pid 21909] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 23:33:18.740290 2019] [ssl:warn] [pid 21909] AH01909: localhost:445:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 23:33:18.740536 2019] [ssl:warn] [pid 21909] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 23:33:18.780412 2019] [ssl:warn] [pid 21910] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 23:33:18.780681 2019] [ssl:warn] [pid 21910] AH01909: localhost:445:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 23:33:18.780928 2019] [ssl:warn] [pid 21910] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 23:33:18.784109 2019] [mpm_prefork:notice] [pid 21910] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2t configured -- resuming normal operations
[Tue Nov 05 23:33:18.784128 2019] [core:notice] [pid 21910] AH00094: Command line: '/usr/sbin/apache2'
[Tue Nov 05 23:39:57.651085 2019] [mpm_prefork:notice] [pid 21910] AH00169: caught SIGTERM, shutting down
[Tue Nov 05 23:39:57.723789 2019] [ssl:warn] [pid 22027] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 23:39:57.724076 2019] [ssl:warn] [pid 22027] AH01909: localhost:445:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 23:39:57.724326 2019] [ssl:warn] [pid 22027] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 23:39:57.763019 2019] [ssl:warn] [pid 22028] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 23:39:57.763276 2019] [ssl:warn] [pid 22028] AH01909: localhost:445:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 23:39:57.763510 2019] [ssl:warn] [pid 22028] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 05 23:39:57.766591 2019] [mpm_prefork:notice] [pid 22028] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2t configured -- resuming normal operations
[Tue Nov 05 23:39:57.766608 2019] [core:notice] [pid 22028] AH00094: Command line: '/usr/sbin/apache2'
[Tue Nov 05 23:46:45.915358 2019] [mpm_prefork:notice] [pid 22028] AH00169: caught SIGTERM, shutting down
[Wed Nov 06 00:09:38.421783 2019] [ssl:warn] [pid 25170] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 00:09:38.422091 2019] [ssl:warn] [pid 25170] AH01909: localhost:445:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 00:09:38.422332 2019] [ssl:warn] [pid 25170] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 00:09:38.461038 2019] [ssl:warn] [pid 25171] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 00:09:38.461304 2019] [ssl:warn] [pid 25171] AH01909: localhost:445:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 00:09:38.461535 2019] [ssl:warn] [pid 25171] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 00:09:38.464705 2019] [mpm_prefork:notice] [pid 25171] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2t configured -- resuming normal operations
[Wed Nov 06 00:09:38.464724 2019] [core:notice] [pid 25171] AH00094: Command line: '/usr/sbin/apache2'
[Wed Nov 06 00:10:00.187628 2019] [mpm_prefork:notice] [pid 25171] AH00169: caught SIGTERM, shutting down
[Wed Nov 06 00:10:05.323092 2019] [ssl:warn] [pid 25813] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 00:10:05.323390 2019] [ssl:warn] [pid 25813] AH01909: localhost:445:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 00:10:05.323633 2019] [ssl:warn] [pid 25813] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 00:10:05.364010 2019] [ssl:warn] [pid 25814] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 00:10:05.364272 2019] [ssl:warn] [pid 25814] AH01909: localhost:445:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 00:10:05.364513 2019] [ssl:warn] [pid 25814] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 00:10:05.367595 2019] [mpm_prefork:notice] [pid 25814] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2t configured -- resuming normal operations
[Wed Nov 06 00:10:05.367613 2019] [core:notice] [pid 25814] AH00094: Command line: '/usr/sbin/apache2'
[Wed Nov 06 00:10:48.447295 2019] [mpm_prefork:notice] [pid 25814] AH00169: caught SIGTERM, shutting down
[Wed Nov 06 00:10:50.651096 2019] [ssl:warn] [pid 26447] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 00:10:50.651493 2019] [ssl:warn] [pid 26447] AH01909: localhost:445:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 00:10:50.651845 2019] [ssl:warn] [pid 26447] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 00:10:50.695926 2019] [ssl:warn] [pid 26448] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 00:10:50.696288 2019] [ssl:warn] [pid 26448] AH01909: localhost:445:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 00:10:50.696627 2019] [ssl:warn] [pid 26448] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 00:10:50.699723 2019] [mpm_prefork:notice] [pid 26448] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2t configured -- resuming normal operations
[Wed Nov 06 00:10:50.699746 2019] [core:notice] [pid 26448] AH00094: Command line: '/usr/sbin/apache2'
[Wed Nov 06 06:25:01.878438 2019] [mpm_prefork:notice] [pid 26448] AH00171: Graceful restart requested, doing restart
[Wed Nov 06 06:25:01.937916 2019] [ssl:warn] [pid 26448] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 06:25:01.938386 2019] [ssl:warn] [pid 26448] AH01909: localhost:445:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 06:25:01.938781 2019] [ssl:warn] [pid 26448] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 06 06:25:01.938956 2019] [mpm_prefork:notice] [pid 26448] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2t configured -- resuming normal operations
[Wed Nov 06 06:25:01.938963 2019] [core:notice] [pid 26448] AH00094: Command line: '/usr/sbin/apache2'
[Thu Nov 07 03:05:41.639381 2019] [ssl:error] [pid 29880] [client 104.248.210.29:52502] AH02042: rejecting client initiated renegotiation
[Thu Nov 07 06:25:01.241871 2019] [mpm_prefork:notice] [pid 26448] AH00171: Graceful restart requested, doing restart
[Thu Nov 07 06:25:01.287970 2019] [ssl:warn] [pid 26448] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Thu Nov 07 06:25:01.288347 2019] [ssl:warn] [pid 26448] AH01909: localhost:445:0 server certificate does NOT include an ID which matches the server name
[Thu Nov 07 06:25:01.288689 2019] [ssl:warn] [pid 26448] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
[Thu Nov 07 06:25:01.288832 2019] [mpm_prefork:notice] [pid 26448] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2t configured -- resuming normal operations
[Thu Nov 07 06:25:01.288838 2019] [core:notice] [pid 26448] AH00094: Command line: '/usr/sbin/apache2'

**Comment by DanielnetoDotCom** [comment]
No PHP error, looks like something regarding your SSL

look this error : `rejecting client initiated renegotiation`

**Comment by ucmafialtd** [comment]
thanks looking into that appreciate it, you think thats the problem

**Comment by JedMeister** [comment]
Hi @DanielnetoDotCom 

As a bit of background context; my name is Jeremy and I work with [TurnKey Linux](https://www.turnkeylinux.org). We have a (community submitted) [TurnKey YouPHPTube appliance](https://www.turnkeylinux.org/youphptube) that is built on top of our [LAMP appliance](https://www.turnkeylinux.org/lamp). @ucmafialtd is currently a TurnKey user with his server running on AWS. I reviewed the YouPHPTube appliance build code and did manual pre-release smoke testing (running the server locally) and all seemed fine (although in fairness, I didn't do exhaustive testing). However the community member who submitted the appliance said that he'd done extensive testing on his home lab set up and all was working well. Unfortunately though, @ucmafialtd has had issue after issue with his server. Obviously some of these are just due to our tests not being exhaustive (e.g. #2234 - which I'll explicitly post on shortly). But others, such as this one I have no idea how/why they occurred.

After investigating this issue, it appears to have been caused by a corrupted (or incorrectly edited) `site.xml` file. Does that sound like it could possibly be the cause of this issue? Please excuse my ignorance, I know a little PHP and have lots of experience installing and setting up webapps, but my strength is general Linux sysadmin rather than webapp toubleshooting.

FWIW I only noticed it as I did an update of YouPHPTube (the version that we ship with is a little out of date) and git complained that the file had been edited. When I viewed it, it looked like it had been edited with Windows Notepad (it had Windows line endings).

Regardless, this issue is now resolved, so the issue can be closed IMO.

**Comment by DanielnetoDotCom** [comment]
Hi, @JedMeister 

thanks for your communication here.

the only issue I am aware of sitemap.xml is the video limit, some times it is too big and takes time to generate it.

the video limit can be edited here 

![image](https://user-images.githubusercontent.com/18009293/68585439-09254e00-0461-11ea-9ab5-3cda8f443dd2.png)

**Comment by JedMeister** [comment]
@DanielnetoDotCom - Ah ok, so perhaps that wasn't the issue and it was something else?! Regardless, the videos now appear to play ok.

**Comment by ucmafialtd** [comment]
Hey brotha it's saying my ip address is the same server it was before 
![IMG_20191113_170729](https://user-images.githubusercontent.com/53587701/68818517-0f225700-063a-11ea-8c2a-8aee343e2414.jpg)

**Comment by JedMeister** [comment]
He @ucmafialtd - are you not planning on using TurnKey anymore? If not, that's fine, no hard feelings or any of that. Especially considering that you had such a crappy run trying to get things up and running...

Although as you say, the TurnKey server is still running (so is still costing you money on AWS) and you are still on the TurnKey free trial which will expire in a few days. Please hit me up via support@turnkeylinux.org so I can help you shut your server and account down so that you don't get hit with fees!

Re getting your domain to migrate to a new server, you'll need to adjust the nameservers with your domain registrar to point to whatever new nameservers you are using. Otherwise, you'll need to create an A record to point to your server's IP.

**Comment by ucmafialtd** [comment]
Yo brotha I been trying to get ahold of you all day on both GitHub and email! None of my SSH keys work to login to my backend I've even made a new private key and none of them have worked! Can you please send me the SSH key that you have used please so I can finally work on my stuff

**Comment by ucmafialtd** [comment]
I'm really starting to get fucking irritated been trying to get in touch with @DanielnetoDotCom all flipping day for how many hours who knows fuck man come on I need to get my shit done and can't without the ssh key that you used to login so can you please send me a email with the ssh key that works!!

**Comment by DanielnetoDotCom** [comment]
I am not planning to use your turnkey
