### ISSUE TITLE
How do I make encoder

### ISSUE THREAD

**Issue by ucmafialtd** [YouPHPTube/YouPHPTube#2234]
How can and make my own encoder on AWS for my site

**Comment by DanielnetoDotCom** [comment]
This video may help you https://tutorials.youphptube.com/video/streamer-and-encoder

Also this https://github.com/YouPHPTube/YouPHPTube-Encoder/wiki/How-to-install-LAMP,--FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x---For-YouPHPTube-Encoder

**Comment by ucmafialtd** [comment]
I'm new to all this my head going to explode

**Comment by DanielnetoDotCom** [comment]
you always can hire us to install it for you https://www.youphptube.com/services

**Comment by ucmafialtd** [comment]
what about if you already have the server up and youphptube and a few of the plugin bought installed

**Comment by ucmafialtd** [comment]
maybe you and i can talk about some affiliate marketing and like stuff help each other out

**Comment by JedMeister** [comment]
As hinted in my recent post on another issue, the problem with this was the Encoder port that we were using by default was not working on AWS. As I noted on the [issue on our tracker](https://github.com/turnkeylinux/tracker/issues/1374) we were using port 445, but for some reason that wasn't working on AWS (even with the port opened in the security group). Changing the encoder port to 8443 appears to have resolved the issue.

This issue can be closed IMO.
