### ISSUE TITLE
Video Page slowly to be opened 

### ISSUE THREAD

**Issue by abamilod** [YouPHPTube/YouPHPTube#2235]
Hello all,
Has anyone here experiences the YPT starts to show video page slower when the content videos more than a few thousand. Open the root page can be fast (with cdn or ssd) but when we want to open 
 `https://domain.com/video/video_name` then it may take a few seconds. 
The more video uploaded the more slower video page it is shown. Which part causing this and can we disable it?

**Comment by DanielnetoDotCom** [comment]
Are you using the latest version?

I am asking this because we always  release performance update

**Comment by abamilod** [comment]
Yes i am using the latest version almost everyday update if available. I also hv seen YPT used in some university video page loading 20+ seconds. But there is a medical site done with YPT loads video page 1+ sec (very short videoclip). I know using cache can make it load fast but time limit and outdated info is the handicap. Maybe function like restoring last viewed timeframe of the video causing this delay?

**Comment by DanielnetoDotCom** [comment]
Yes maybe.


Are you using Backblaze to store your videos?

Are you using the video thumbnails plugin?

**Comment by abamilod** [comment]
No thumbnails plugin but i m using aws S3 with minio for video storage but in the same server (done this for future plan just in case i want to change streamer server location)

**Comment by DanielnetoDotCom** [comment]
If you try the same slow video in a incognito browser the load speed is different?

**Comment by abamilod** [comment]
Interesting. Using incognito browser i get less 2 sec faster loading.

**Comment by abamilod** [comment]
After tried a few times i got average the same time loading. Web server on nvme ssd and minio video storage on hdd inside the same server. I guess this setup is bad for YPT because YPT reads video content when it wants to open video page.

**Comment by DanielnetoDotCom** [comment]
What I think....

When you use an incognito browser your video will start to play from 0.

When you are logged in and you try to watch a video it will start from the last viewed position . Looks like your s3 is trying to download all the video until the last position.

I saw this happening before on Backblaze but maybe this has something to do with the cdn.

I know Apache has something that reads a partial portion of the video without download it all. I am not sure how your s3 is dealing with it.

I already saw Amazon S3 and wasabi S3 working normally with large videos , that is why I guess is something to do with the cdn

**Comment by abamilod** [comment]
I hv another site YPT inside the same server with less 2k videos. The video page loads less 2 second. Which make me thinking maybe minio S3 causing this or mysql

**Comment by DanielnetoDotCom** [comment]
I really do not think it is a Mysql issue the heaviest Mysql page is the first page, if it is working fine it should be something else

**Comment by abamilod** [comment]
I see. Thank you for ur input. I will continue trying to find the solution as my site keep growing bigger everyday

**Comment by DanielnetoDotCom** [comment]
I am glad to hear you are growing , just to make sure you can try this...

Inspect the source code and grab your video source URL (direct to your S3) open the direct URL in your browser and try to skip the video to the end.

I guess it will take a while because it will try to download all video

**Comment by DanielnetoDotCom** [comment]
Or maybe it will just try to download your video instead open to play

P.s. when I say direct URL I mean a URL directly to your MP4 file

**Comment by abamilod** [comment]
When i tried open the video direct url it loads very fast (blank page browser). Playing the video is no problem only even inside the site. The only problem is to load the video page 7-9 sec. After that playing the video is smooth.

**Comment by abamilod** [comment]
I hv tried before copy the videos from minio to local video folder but the video page loading still takes time.

**Comment by abamilod** [comment]
After that i deleted 2k of videos and when i open one of the video page it loads faster

**Comment by DanielnetoDotCom** [comment]
OMG, let's see if I understand ...

if you have over 2k videos only large videos are slow? or small videos are also slow?

makes no difference store it in the S3 or locally, both are slow?

the last test, if you open the embed video URL does it still slow? 

I am asking the embed part to see if we can detect what is slowing down. if is something on the page or if is just the video load query.

**Comment by abamilod** [comment]
I dont hv embed  video (not test yet). YPT has no problem playing video locally or S3 even site more 5k of videos (long or short). But the more videos uploaded  will cause video page loading slow. The ratio to my server 2000 video 2 sec, 6000 video 6 sec. Tried on other dedi server also the same. Loading video page slow (6-8 sec) then playing the video is fast. The more visitor will effect also the loading time

**Comment by DanielnetoDotCom** [comment]
Hi, I do not mean an embed video, I mean try to play your video on embed mode

for example, here is an embed link for one of our local videos https://demo.youphptube.com/videoEmbed/high-five-etiquette-2

if you do the same in your page does it load faster?

**Comment by abamilod** [comment]
Ok understood. If i do embed or open video direct on browser, the video will loading fast. I think this way the site script is not been used much (raw video).

**Comment by DanielnetoDotCom** [comment]
for example 

24k videos https://live.karaoke.od.ua/
15k videos https://www.diytube.video/
10k videos https://xemtube.tv/
10k videos https://www.joshwhotv.com/

**Comment by DanielnetoDotCom** [comment]
What do you mean "I think this way the site script is not been used much (raw video)"?

**Comment by abamilod** [comment]
For example i open this video page
https://live.karaoke.od.ua/video/the-jackson-5-shake-your-body-down-to-the-ground-karaoke-

It took 5 sec to loading the page before i can play it. This is what i mean the delay.

**Comment by abamilod** [comment]
I see there r other sites more 10k of videos with better loading video page time. This is interesting. Maybe my videos mostly big (30-60 min) causing this. Thank you so much for ur time. Sorry to make u worry

**Comment by DanielnetoDotCom** [comment]
this is very important for me

currently, the most important things for me are:

1st - Security
2nd - Performance

**Comment by abamilod** [comment]
Let me do more test and share my finding.

**Comment by abamilod** [comment]
I did another test with very very short video and the video page loads very fast. So its confirm the video size can slow down the video page loading. I guess YPT/Apache tries to load more than small partial in my server.

**Comment by DanielnetoDotCom** [comment]
the default behavior of YPT/Apache is to load only a partial portion of the video.

something in your configuration is trying to load everything, maybe a CDN or your S3

this is the capability to the server handle the header "Content-Range"

check this https://stackoverflow.com/questions/13043816/html5-video-and-partial-range-http-requests
