### ISSUE TITLE
Weird video looking after update

### ISSUE THREAD

**Issue by akhilleusuggo** [YouPHPTube/YouPHPTube#2239]
The location of the video are looking weird after I updated . 
![image](https://user-images.githubusercontent.com/52116577/68526823-cba1b300-02f0-11ea-83d5-31b97aba45bc.png)

**Comment by DanielnetoDotCom** [comment]
Hi, 

please make sure you do not have this enabled

![image](https://user-images.githubusercontent.com/18009293/68527610-874ded00-02c7-11ea-870f-5dc048d02213.png)

**Comment by akhilleusuggo** [comment]
That was the problem . Looks like you updated that option too , and changed mine by default
