### ISSUE TITLE
Gallery Theme Bug with Categories Row Number

### ISSUE THREAD

**Issue by JoshWho** [YouPHPTube/YouPHPTube#2246]
Seems like it is only going off the row count to the next above listing enabled. 

For example, I have Most Viewed enabled and set for 6 videos 

So now categories are showing 6 rows on the home page but it is cutting off half of the categories.

 <img src="https://static.buddylist.co/x/cat1.png" style='width:100%;' border="0" alt="Null">
<img src="https://static.buddylist.co/x/cat2.png" style='width:100%;' border="0" alt="Null">

**Comment by DanielnetoDotCom** [comment]
I just sent an update, can you please update your files and try again?

**Comment by JoshWho** [comment]
500 Error now.

**Comment by JoshWho** [comment]
ALl fixed. Thank you
