### ISSUE TITLE
Pictures and cache

### ISSUE THREAD

**Issue by Donnerstein** [YouPHPTube/YouPHPTube#2250]
If a user changes his profile or banner image, this change will not be displayed immediately because the images are in the browser's cache
and are cached in Cloudflare or other CDN systems that users like to check the new look of their channel, which does not work and they then suspect a mistake. The same is true with the thumbnails of the videos. A change is not accepted immediately. What less technically knowledgeable users are constantly coming to suspect that the change has not been adopted.
I would suggest adding the current date of creation to the filename of the user images and thumbnails.
In this way, changes will be applied immediately and the images will still be cached.

greeting
Donnerstein

**Comment by DanielnetoDotCom** [comment]
We have the modified date on the images you mention, but maybe we miss it in some places.

also make sure you have the latest youPHPTube

**Comment by Donnerstein** [comment]
I mean a date and time in the file name. So if you change the files, the URL to the images always changes, and you can bypass the carche.
Also on the demo site, the URLs stay the same when you change an image.

By keeping the URL the images are used in the carche when a change is made. And the change does not occur immediately. If you change the file name each time you save it, only images from the carche will be loaded if they have not been changed since the user was last visited.
I made a video to understand what I want to say.

![image](https://user-images.githubusercontent.com/52116237/68687143-0fa0ec00-056d-11ea-9300-6827eecacfd1.png)



[video.zip](https://github.com/YouPHPTube/YouPHPTube/files/3837109/video.zip)

**Comment by DanielnetoDotCom** [comment]
the filename is the same, but if you inspect the code you will see a get variable to avoid the cache

![image](https://user-images.githubusercontent.com/18009293/68690829-71535d00-0551-11ea-88a1-d49e54ad2992.png)

**Comment by Donnerstein** [comment]
Yes, for the logo. That will also be renewed immediately if you change it, that works. But for the user pictures, so banners and profile pictures not so. A user who changes his profile picture, or a preview image to the video, can not immediately see this change. And then upload it again, and try again because the change was apparently not adopted.

![image](https://user-images.githubusercontent.com/52116237/68692499-e769bb00-0575-11ea-8a87-ca1a02c666d0.png)

![image](https://user-images.githubusercontent.com/52116237/68692538-f3ee1380-0575-11ea-8f91-8513b15ae557.png)

**Comment by DanielnetoDotCom** [comment]
I just sent an update that may help

**Comment by Donnerstein** [comment]
Yes, that works Thank you.
