### ISSUE TITLE
"What groups can see this video" setting doesn't save

### ISSUE THREAD

**Issue by Intermo101** [YouPHPTube/YouPHPTube#2265]
I can set the user group that can see that video, save it, close out of the form, go back and have my changes gone

**Comment by DanielnetoDotCom** [comment]
please check your log file for errors.

**Comment by Intermo101** [comment]
> please check your log file for errors.

nothing in the log file

**Comment by Intermo101** [comment]
Sorry im stupid, the option "Public media" was still checked
