### ISSUE TITLE
Can bypass "only logged in users can view site" by just doing "localhost/youphptube" instead of "localhost/youphptube/user"

### ISSUE THREAD

**Issue by Intermo101** [YouPHPTube/YouPHPTube#2266]

**Comment by DanielnetoDotCom** [comment]
I do not understand

**Comment by Intermo101** [comment]
> I do not understand

I checked the "hide website to users who are not logged in" option in the customize users plugin, but I can view the site without logging in by just going to site.com/youphptube instead of site.com/youphptube/user(login page)

**Comment by DanielnetoDotCom** [comment]
can you please screenshot where do you find "hide website to users who are not logged in"?

**Comment by Intermo101** [comment]
> can you please screenshot where do you find "hide website to users who are not logged in"?

here
![image](https://user-images.githubusercontent.com/57767008/69093812-8b100b00-0a4f-11ea-907d-713650198cca.png)

**Comment by DanielnetoDotCom** [comment]
Ok, please disable your cache plugin and try to access it from an incognito browser.

**Comment by Intermo101** [comment]
It worked thanks
