### ISSUE TITLE
SendRecordedToEncoder plugin and YouPHPTube-Encoder-Network?

### ISSUE THREAD

**Issue by maxlinux2000** [YouPHPTube/YouPHPTube#2268]
I have a problem with the Live feature with the SendRecordedToEncoder plugin, and the YouPHPTube-Encoder-Network with 3 YouPHPTube-Encoder.

If I put you in the preferences of youphptube, the url of the YouPHPTube-Encoder-Network, this works, but if I do a Live with android it does not work for me the recording of the live because it goes is encoded in another server encoder instead of doing it in local.

How do I make the network encoder server work but at the same time the SendRecordedToEncoder utilize plugin is a local encoder?

**Comment by DanielnetoDotCom** [comment]
Hi

thanks for your question...

I am a bit confused, it should be no difference who is your publisher. if is the mobile, the OBS or something else.

the YouPHPTube site will decide where to send it.

can you please give more details what are you doing?

are you using our mobile app? a Whitelabel one? a third party app?

**Comment by maxlinux2000** [comment]
OK, My fault!
The problem was caused from a ffmpeg misconfiguration. 
The system is now working perfectly even if the video record of a live, was encoded in a external encoder.

sorry for the confusion
closing
