### ISSUE TITLE
Meta Tag appearing in body of Video Play Page causing error on bot views

### ISSUE THREAD

**Issue by JoshWho** [YouPHPTube/YouPHPTube#2283]
Found this code in the body of a video playing

<meta itemprop="uploadDate" content="2019-11-23 07:21:14" />

 <img src="https://static.buddylist.co/x/metatagbody.png" style='width:100%;' border="0" alt="Null">

**Comment by JoshWho** [comment]
This is causing issues with bots collecting the video info to index. Needs moved to the header.

**Comment by JoshWho** [comment]
<meta itemprop="uploadDate" content="2019-11-23 07:21:14" />

**Comment by JoshWho** [comment]
<meta itemprop="uploadDate" content="2019-11-23 07:21:14" />

**Comment by JoshWho** [comment]
<img src="https://static.buddylist.co/x/metatagbody2.png" style='width:100%;' border="0" alt="Null">

**Comment by JoshWho** [comment]
<img src="https://static.buddylist.co/x/metatagbody2.png" style='width:100%;' border="0" alt="Null">

**Comment by JoshWho** [comment]
<img src="https://static.buddylist.co/x/metatagbody2-.png" style='width:100%;' border="0" alt="Null">

**Comment by DanielnetoDotCom** [comment]
Ok, I see the meta is in the wrong place, should be on the head, but I can not move it to the head because the itemprop is for ta specific HTML item.

so I change the meta for span, you should not have this error anymore

**Comment by JoshWho** [comment]
Sweet. Thank you
