### ISSUE TITLE
Upload Problem.

### ISSUE THREAD

**Issue by inferno-prime** [YouPHPTube/YouPHPTube#2303]
I changed the upload limits in my php.ini but am still not able to finish the upload. Is there anything else I need to check.

**Comment by DanielnetoDotCom** [comment]
what is the error?

please screenshot the error and also check your log file

**Comment by inferno-prime** [comment]
After updating to 8.0 I have getting this error in the avideo.log file.

`[03-Dec-2019 12:25:09 America/Los_Angeles] PHP Warning:  filectime(): stat failed for /home/tv/videos/20191015210604_5de3293c8e05d1.69057065_thumbsSmallV2.jpg in /home/tv/objects/video.php on line 2255
`

**Comment by DanielnetoDotCom** [comment]
this is a warning not an error

**Comment by inferno-prime** [comment]
That's all thats in the log. I don't get any kind of error when uploading. The only thing that happens is the name of the video turns from white while uploading to red when its suppose to be done.

**Comment by DanielnetoDotCom** [comment]
the log you sent is a streamer log, but you probably are talking about the encoder

**Comment by inferno-prime** [comment]
How do I check that then ? My webhost has ffmpeg.

**Comment by DanielnetoDotCom** [comment]
the encoder log is into the encoder/videos/avideo.log

or encoder/videos/youphptube.log for older version

**Comment by inferno-prime** [comment]
I am getting a 404 on the github download page for the encoder. also Does the encoder plugin use ffmpeg or how does that work ?

**Comment by DanielnetoDotCom** [comment]
what exactly link is giving you a 404?

the encoder is not a plugin is another site (https://github.com/YouPHPTube/YouPHPTube-Encoder) and yes it uses FFMPEG

**Comment by inferno-prime** [comment]
Well I am not using the encoder at all I am only using direct upload.

**Comment by DanielnetoDotCom** [comment]
I see, sorry, we are in transition to this link.

for now, use the one I gave you above.

**Comment by inferno-prime** [comment]
Alright but what if something happens to the public encoder ?

**Comment by DanielnetoDotCom** [comment]
to be able to use the public encoder you need to update your streamer to version 8.0

**Comment by inferno-prime** [comment]
Alright I guess I will wait until the transition is done.

Thanks for all your help.

**Comment by DanielnetoDotCom** [comment]
the transition is done, you can update now.

**Comment by inferno-prime** [comment]
> 
> 
> the transition is done, you can update now.

I updated my version earlier today. 

I just tried the link again to download the encoder again but still says 404

**Comment by DanielnetoDotCom** [comment]
I mean, download it from here https://github.com/YouPHPTube/YouPHPTube-Encoder

this URL will be moved to the WWBN/AVideo-Encoder

**Comment by DanielnetoDotCom** [comment]
This link will be 404 and we will not change it now https://github.com/WWBN/AVideo-Encoder

you MUST use this link to get the encoder https://github.com/YouPHPTube/YouPHPTube-Encoder
