### ISSUE TITLE
Need to disable Email Sharing - This is flagging my smtp alert 

### ISSUE THREAD

**Issue by JoshWho** [YouPHPTube/YouPHPTube#2306]
The Email Share tab under the video player needs disabled. 

Problem is it is sending the emails trying to use the user that sent it email account. I do not want my server sending emails with unauthorized email domains.  My SMTP rules stop this but the user sharing it thinks it is being sent. It just winds up being a complete hassle in the long run.

**Comment by DanielnetoDotCom** [comment]
done, and will be added in the next release.

will be an option in customizeAdvanced plugin called disableEmailSharing
