### ISSUE TITLE
REQUEST: Unique image file names for every thumbnail and other image uploads

### ISSUE THREAD

**Issue by JoshWho** [YouPHPTube/YouPHPTube#2309]
We need a way to bypass the cache so it is easy for images to stay in cache longer without needing overwritten.

Everytime I upload a new video thumbnail it keeps the exact same file name so I have to force clear cache for it to show.

Can you make it to where it just gives all images a unique name every upload. I do not want it to replace the file I want it to just create a new one.

**Comment by DanielnetoDotCom** [comment]
I  just send an update that may help with that.

Before Update do not forget ... 

**Important Information: We are updating our video system. It is important that your video system and plugins are up to date, everything must be updated after 2019-12-02. The new plugins will not work with the system before 8.0, so if you just got plugins and your installation is old, you must update your site.
If you have updated your site to version 8.0, your old plugins will not work, just download them again and you should be fine.**

**Comment by JoshWho** [comment]
Good deal Works great,
