### ISSUE TITLE
Email Verification is no longer working!!!!!!!!

### ISSUE THREAD

**Issue by JoshWho** [YouPHPTube/YouPHPTube#2311]
None of the email codes are activating accounts anymore. I tried creating a test account and the verification code just keeps erroring.

**Comment by JoshWho** [comment]
So far i had to manual verify 20 accounts,

**Comment by JoshWho** [comment]
I think I have it fixed now. It might have been a Cache issue.

**Comment by JoshWho** [comment]
I think I figured it out. It might have been Cache locking on to something. 
I purged it and changed some rules and was able to verify my test account.

**Comment by JoshWho** [comment]
OK nevermind it is still doing it. I just made a second test account and it is doing the same thing again.

**Comment by JoshWho** [comment]
It is giving the same Verification code to everyone and not changing.

**Comment by akhilleusuggo** [comment]
I'm having the same problem already 2 months . People reporting that is not working

**Comment by DanielnetoDotCom** [comment]
I think I found the bug, please try again

**Comment by JoshWho** [comment]
Thank you. Working good now. Test account got verified on the first try.
