### ISSUE TITLE
Encoder issues

### ISSUE THREAD

**Issue by inferno-prime** [YouPHPTube/YouPHPTube#2320]
Just installed encoder. 

Heres log:
[04-Dec-2019 20:10:44 America/Los_Angeles] Get Login fail, try again
[04-Dec-2019 20:10:44 America/Los_Angeles] PHP Warning:  file_get_contents(tv/login): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden
 in /home/tv/encoder/objects/Login.php on line 41
[04-Dec-2019 20:10:44 America/Los_Angeles] Error on Login context
[04-Dec-2019 20:10:44 America/Los_Angeles] /tv/login
[04-Dec-2019 20:10:44 America/Los_Angeles] 
 When trying to login to the encoder I am getting : 

Sorry!
We could not find your streamer site! 

I am using https I hope that wont be a problem.

**Comment by DanielnetoDotCom** [comment]
this error is really strange, can you please screenshot your login page?

for me looks like the Streamer site is wrong

**Comment by inferno-prime** [comment]
How can I fix this then ?

**Comment by DanielnetoDotCom** [comment]
what makes me confused is this 

`[04-Dec-2019 20:10:44 America/Los_Angeles] PHP Warning: file_get_contents(tv/login): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden in /home/tv/encoder/objects/Login.php on line 41`

the URL the encoder received was "tv/login" when it suppose to be a full URL with http://...

so you got a 403 Forbidden, I am not sure where in your server you misconfigured the URL

**Comment by inferno-prime** [comment]
Well I'm not sure what is going on. I just found out that I can't even upload a file over 50MB and I made sure I set those in the php.ini file.
