### ISSUE TITLE
Encoder doesn’t upload 

### ISSUE THREAD

**Issue by barrunning** [YouPHPTube/YouPHPTube#2325]
Add file to encoder. Start upload. Sharing queue shows file being encoded. After encoding is complete. Nothing is submitted to barrunningvideos.com. All was fine until 11/27/2019

**Comment by DanielnetoDotCom** [comment]
Important Information: We are updating our video system. It is important that your video system and plugins are up to date, everything must be updated after 2019-12-02. The new plugins will not work with the system before 8.0, so if you just got plugins and your installation is old, you must update your site.
If you have updated your site to version 8.0, your old plugins will not work, just download them again and you should be fine.

**Comment by barrunning** [comment]
So I need to update php to 8.0. Then download the plugins? Or the youphptube needs to be updated to 8.0? As you set it up so I have no idea what any of that means or how to do it. 

Barrunning

**Comment by barrunning** [comment]
I click update on my site and nothing happens. It shows 7.7 and says it is up to date. How do you update to version 8.0?

**Comment by DanielnetoDotCom** [comment]
To update your site you must follow this:

https://github.com/YouPHPTube/YouPHPTube/wiki/How-to-Update-your-YouPHPTube

to update the purchased plugins you must download them again and update your site.

**Comment by barrunning** [comment]
Update worked
