### ISSUE TITLE
Storage full

### ISSUE THREAD

**Issue by guitarpound** [YouPHPTube/YouPHPTube#2327]
Hi,

I have main storage that install the Linux and YouPHPTube and additional storage point to /media/video/

But after I check disk space the main storage is Full.
So, I tried testing clear all video files from Web GUI.
But the main storage still full.

![1575694777880](https://user-images.githubusercontent.com/57282919/70369378-fd576b00-18ea-11ea-9cbb-b96649dd7b76.jpg)

So, I want to know which part directory in the main storage that I can clear the files without impact to the system.

Could you please kindly help.

Thanks & BR

**Comment by XemTube-TV** [comment]
Please check in / HLS / Live and delete the files with .ts extension if available

**Comment by JoshWho** [comment]
look for your tmp folder before the /YouPHPTube

Might need to manually delete live streams.

**Comment by guitarpound** [comment]
Hi,

I already clear in the /HLS/Live and /tmp.
It working well.

Thanks & BR

**Comment by DanielnetoDotCom** [comment]
Next time use `du -h --max-depth=1` to find what directory is using mutch space
