### ISSUE TITLE
 Error of not displaying images of live video streaming. I waited for it for 1 hour but it still didn't show any images.

### ISSUE THREAD

**Issue by XemTube-TV** [YouPHPTube/YouPHPTube#2330]
Error of not displaying images of live video streaming. I waited for it for 1 hour but it still didn't show any images.

![image](https://user-images.githubusercontent.com/50126312/70375331-344f7000-192f-11ea-8f90-8f9bdf529ae5.png)

**Comment by XemTube-TV** [comment]
![image](https://user-images.githubusercontent.com/50126312/70375541-6b268580-1931-11ea-96e3-594c2fcef70e.png)

After I upgraded, there was an error of not showing the background image for live streaming videos. Can you guide me on Fix it.

**Comment by JoshWho** [comment]
You need to upgrade your encoders also. Latest version is 3.0

**Comment by JoshWho** [comment]
in terminal go to your encoder directory and type: git pull

Then go to your encoder and click the update

**Comment by XemTube-TV** [comment]
I am using a public encoder. I don't think the error comes from the encoder. Because Video Live streaming does not go through the encoder.

**Comment by XemTube-TV** [comment]
@DanielnetoDotCom 
You can check and guide me on how to fix the error that does not show thumbnails on the Live Video. I do not know where the error comes from after I upgraded to version 8.0.

**Comment by XemTube-TV** [comment]
I fixed it. Thank for all !
