### ISSUE TITLE
Encoding on Streams and Uploads are stuck

### ISSUE THREAD

**Issue by venwebsites** [YouPHPTube/YouPHPTube#2339]
The Encoder is stuck on uploads and streams. My network is on fibre on a 1 GIG pipe so there should be no lag in uploads
<img width="837" alt="encoding" src="https://user-images.githubusercontent.com/58635493/70472737-9e862300-1a9d-11ea-95e3-5c1ae812d37f.PNG">

**Comment by DanielnetoDotCom** [comment]
Looks like you clicked to direct submit a video and you did not submit anything.

you can secure just delete them

**Comment by venwebsites** [comment]
these uploads were not made by me. these are user videos

**Comment by DanielnetoDotCom** [comment]
someone did it for sure, I bet you can find it out in your apache access log

**Comment by venwebsites** [comment]
ok
