### ISSUE TITLE
User Friendly issues

### ISSUE THREAD

**Issue by venwebsites** [YouPHPTube/YouPHPTube#2342]
When a user creates an account they have to go back into their account and change the channel name. How can we put an option during sign up to name their channel

In the user dashboard there is no area where a user can enter their payment information to be monetized (ads, super chats) How do we enable that

**Comment by DanielnetoDotCom** [comment]
Channel name is a good idea, we may implement this in the future.

Donation links

![image](https://user-images.githubusercontent.com/18009293/70483407-13218780-1ac7-11ea-97f1-785521473ce2.png)

Ads Overlay https://github.com/YouPHPTube/YouPHPTube/wiki/AD_Overlay-Plugin

![image](https://user-images.githubusercontent.com/18009293/70483445-2af90b80-1ac7-11ea-9498-02bb8088ca74.png)

**Comment by venwebsites** [comment]
Don't have that in the my account portal please see screenshot
<img width="1055" alt="donation link" src="https://user-images.githubusercontent.com/58635493/70484485-f7fc4b00-1ab9-11ea-980d-08c90c889fb1.PNG">

**Comment by DanielnetoDotCom** [comment]
Most of the configurations you need, you may find here

![image](https://user-images.githubusercontent.com/18009293/70484980-5af6dd80-1acc-11ea-95f6-d6f504cc138f.png)

**Comment by venwebsites** [comment]
Still not there. Somthing is missing. Were all the plugins I paid for installed

**Comment by DanielnetoDotCom** [comment]
all paid plugins are installed and look like you check the option but you did not save

![image](https://user-images.githubusercontent.com/18009293/70485717-79f66f00-1ace-11ea-863e-f42fc1face08.png)

Once I check and save it, I can see the option now

![image](https://user-images.githubusercontent.com/18009293/70485744-9b575b00-1ace-11ea-935a-63cc23dd0c57.png)

**Comment by venwebsites** [comment]
awesome. Where did you find that so I can make a note
