### ISSUE TITLE
channel users icon doesn't show up next to name

### ISSUE THREAD

**Issue by venwebsites** [YouPHPTube/YouPHPTube#2343]
The Image next to the channel name doesn't appear. please see screenshot. 
<img width="272" alt="name_issue" src="https://user-images.githubusercontent.com/58635493/70483529-c7ff7880-1ab6-11ea-96aa-f0eafe35f37e.PNG">

**Comment by DanielnetoDotCom** [comment]
please give me the link for this page, I want to check

**Comment by venwebsites** [comment]
https://prostreams.live/video/cadillac-slide-show

**Comment by DanielnetoDotCom** [comment]
I just look into your site and you miss a single quote

![image](https://user-images.githubusercontent.com/18009293/70485403-9e058080-1acd-11ea-8eb8-28ce9035fd20.png)
