### ISSUE TITLE
Fresh install. Admin user works, but newly signed up users fail with invalid password.

### ISSUE THREAD

**Issue by walt93** [YouPHPTube/YouPHPTube#2347]
I've tried multiple times, copy/pasted the password, tried resetting the password from the admin account in the user list, no luck.

I also note that I can't find anywhere in the admin user's control panel to delete users. 

What could have gone wrong in the installation to get here?

**Comment by akhilleusuggo** [comment]
Maybe you're using the email to log in , not the usernames

**Comment by walt93** [comment]
🤦🏻‍♂️... thank you!
