### ISSUE TITLE
JS-Err: Script error

### ISSUE THREAD

**Issue by millzee01** [YouPHPTube/YouPHPTube#2349]
Hi, 

i'm trying to make all uploaded video completely private,  when I use the option on video form "Public Media" i try and set this to off.

When i click "save changes" it just takes me back to the video and when i edit it again the "Public Media" option is still enabled.

looking in the log I can see:
[10-Dec-2019 10:19:59 UTC] [aEC] JS-Err: Script error. @ line 0 in file https://www.youphptube.com/plugins/plugins.json?jsonp=1

everything else works like a charm however for some reason this setting is trying to run the script from www.youphptube.com instead of local on my site.

looking at my site config i dont see anything out of place.

Any ideas?

thanks

**Comment by DanielnetoDotCom** [comment]
this line is where we get the store offers plugins 

I just notice the URL was not working but it is fixed now

![image](https://user-images.githubusercontent.com/18009293/70528953-2b78bd00-1b2e-11ea-9d69-6b4c3fcee17e.png)

**Comment by millzee01** [comment]
thanks
